### ISSUE TITLE
rozsirit WeirdBugError na dropdatadir

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#106]
ProcessFailedException (0) in Process.php line 226:
The command "sudo docker run --volume=/tmp/docker/run-584a1031ab3ec9.85128998/data:/data alpine sh -c 'chown 501 /data -R'" failed.

Exit Code: 125(Unknown error)

Working directory: /

Output:
================

Error Output:
================
docker: Error response from daemon: devicemapper: Error running deviceResume dm_task_run failed.
See 'docker run --help'.

in Process.php line 226
at Process->mustRun() in DataDirectory.php line 57
at DataDirectory->dropDataDir() in Runner.php line 263
at Runner->runComponent('220396804', 'keboola.ex-google-drive', '1') in Runner.php line 236

**Comment by ondrejhlavacek** [comment]
Fixed by #110
