### ISSUE TITLE
devmapper retry na builder

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#111]
https://connection.keboola.com/admin/utils/logs?file=2016/12/24/05/2016-12-24-05-19-26-585df74e8a2c9-exception

**Comment by odinuv** [comment]
Solved by #113

**Comment by ondrejhlavacek** [comment]
baflo to na nás zas
https://connection.keboola.com/admin/utils/logs?file=2017/01/29/20/2017-01-29-20-00-17-588e3bc1e67d6-exception

**Comment by odinuv** [comment]
Fixed by https://github.com/keboola/docker-bundle/commit/7f1e69caf4ad03c0512dde95fe6d81ff469e24d6
