### ISSUE TITLE
uploading table >5gb should give an user error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#112]
https://connection.keboola.com/admin/utils/logs?file=2016/12/13/03/2016-12-13-03-56-34-584f63624d451-exception

**Comment by ondrejhlavacek** [comment]
and a file too!

**Comment by ondrejhlavacek** [comment]
detekovat před začátkem uploadu (neslicovaný tabulky a soubory) a vyhodit lidsky čitelnej error.

**Comment by pivnicek** [comment]
related connection issue: https://github.com/keboola/connection/issues/752

**Comment by odinuv** [comment]
https://github.com/keboola/docker-bundle/issues/155https://github.com/keboola/docker-bundle/commit/07b91e8e9b07c164865e18c75bb54d60e1b1fbf4
