### ISSUE TITLE
encrypt - detect invalid json

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#122]
and throw user exception that request is not a valid JSON 

https://connection.keboola.com/admin/utils/logs?file=2017/01/24/10/2017-01-24-10-04-22-588718962010a-exception

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/docker-bundle/commit/d1e14eb47fbb0cad6fc251887076218a637b1e63
