### ISSUE TITLE
propagate oauth api errors as user exception

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#123]
https://connection.keboola.com/admin/utils/logs?file=2017/01/29/11/2017-01-29-11-56-04-588dca4491a8d-exception

https://connection.keboola.com/admin/utils/logs?file=2017/01/30/10/2017-01-30-10-44-38-588f0b06be3cb-exception

**Comment by odinuv** [comment]
fiixed in 4261783cf5db051099458693f614da40d88b460f
