### ISSUE TITLE
oauth authorization - allow store whole authorization object

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#126]
https://developers.keboola.com/extend/common-interface/oauth/

This is supported now:
```
{

    "storage": { ... },
    "parameters": { ... },
    "authorization": {
        "oauth_api": {
            "id": "{OAUTH_API_ID}"
        }
    }
}
```
`authorization` object is replaced by response from Keboola OAuth API.

It should also support this for testing purposes and OAuth applications registred by clients
```
{
  "authorization": {
    "oauth_api": {
      "credentials": {
        "#data": "{\"oauth_token\":\"xx\",\"oauth_token_secret\":\"xxx\",\"x_auth_expires\":\"0\"}",
        "appKey": "xx",
        "#appSecret": "xxx"
      }
    }
  },
  "parameters": {}
}
```

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/docker-bundle/pull/127?

**Comment by ondrejhlavacek** [comment]
@Halama přijde ti tohle jako srozumitelný vysvětlení v dokumentaci?

![image](https://cloud.githubusercontent.com/assets/497675/22555182/267ec402-e963-11e6-82f5-6c0843e56b04.png)

**Comment by Halama** [comment]
@ondrejhlavacek jo myslim ze to je dobry takhle
