### ISSUE TITLE
injected oauth credentials do not decrypt properly

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#130]
https://connection.keboola.com/admin/projects/232/extractors/ex-generic-v2/232743152

**Comment by Halama** [comment]
Už to asi mám Imho se to rozšifruje už tady https://github.com/keboola/docker-bundle/blob/b5548d2ca55dc6e808bb61728826f40b3e26146a/Job/Executor.php#L154 a tím pádem se to potom snaží rozšifrovat podruhé v té autorizaci a na tom to failne.

**Comment by ondrejhlavacek** [comment]
jojo, to bude vono

**Comment by odinuv** [comment]
fixed in 945f53ff95d5ec601243dcda417dc6b287bb5004
