### ISSUE TITLE
Root partition - out of space

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#133]
50GB root partition:
![image](https://cloud.githubusercontent.com/assets/903531/22727696/8e2bef1e-edda-11e6-83b0-d9299518e063.png)

Zpusobil to jeden job ktery sypal neustale bordel na stdout. Potom co byl terminovan se vše uklidnilo.

```
{
message: 
Warning: Invalid argument supplied for foreach() in /home/main.php on line 66

Warning: fgetcsv() expects parameter 1 to be resource, null given in /home/main.php on line 62

Warning: Invalid argument supplied for foreach() in /home/main.php on line 66

W
level: 200
component: keboola.custom-science-php
app: docker
cliCommand: /www/syrup-router/components/docker/releases/20170207104057/vendor/keboola/syrup/app/console syrup:run-job 233393750 --env=prod
job: {
id: 233393750
}
runId: 233393751
pid: 20530
priority: INFO
token: {
id: 63490
description: 
owner: {
id: 1820
name: 
}
}
```

![image](https://cloud.githubusercontent.com/assets/903531/22727736/bac0ad26-edda-11e6-9ec0-6a5eb1a1e1af.png)

Je potřeba zkusit nasimulovat a zjistit kde to kynulo. 
Zároven by asi bylo dobré zavést i limit na velikost log výstupu komponenty.

**Comment by ondrejhlavacek** [comment]
`docker run --log-opt max-size=### ...`

**Comment by odinuv** [comment]
to se toho tyka kdyz to bleje na stdout/stderr ?

**Comment by Halama** [comment]
Debuguju to za chvili dam vedet.

**Comment by Halama** [comment]
Jo takze to bude tim. Kdyz je log driver nastaveny na `json-file` tak to uklada do `/var/lib/docker/containers/...` ktery lezi na root 50GB partition.

```
docker inspect f2ecbbb1cf9b
[
    {
        "Id": "f2ecbbb1cf9b6a6e8e053f3b0dd85f13df859cd379d09748cf196a6909cad659",
        "Created": "2017-02-08T08:33:29.679612708Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "while true; do echo hello world; sleep 1; done"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1196,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-02-08T08:33:30.214676554Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:f49eec89601e8484026a8ed97be00f14db75339925fad17b440976cffcbfb88a",
        "ResolvConfPath": "/var/lib/docker/containers/f2ecbbb1cf9b6a6e8e053f3b0dd85f13df859cd379d09748cf196a6909cad659/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/f2ecbbb1cf9b6a6e8e053f3b0dd85f13df859cd379d09748cf196a6909cad659/hostname",
        "HostsPath": "/var/lib/docker/containers/f2ecbbb1cf9b6a6e8e053f3b0dd85f13df859cd379d09748cf196a6909cad659/hosts",
        "LogPath": "/var/lib/docker/containers/f2ecbbb1cf9b6a6e8e053f3b0dd85f13df859cd379d09748cf196a6909cad659/f2ecbbb1cf9b6a6e8e053f3b0dd85f13df859cd379d09748cf196a6909cad659-json.log",
        "Name": "/pedantic_perlman",
```

Resenim je bud nastavit `log-driver` na `none` nebo nechat `json-file` a nastavit `max-file` a `max-size`. Oboje se da nastavit bud pri volani `docker run` nebo v nastaveni daemona https://github.com/keboola/cookbook-keboola-syrup/blob/master/files/default/docker-daemon.json

Asi bych byl pro to nastavit globalne a omezit `max-file` a `max-size`.

**Comment by Halama** [comment]
Pokud to ale tim logem zasekalo 40GB na disku tak je divny ze do SAPI event to poslalo "jenom" 40K event. To nam taky pekne mohlo zasekat ES nebo tam je nejaky zahazovani?
Ten sber na stdout a posilani do SAPI by taky chtelo nejak limitovat, to je to co jsem myslel puvodne.

**Comment by Halama** [comment]
@ondrejhlavacek Mohl by si ty logy opet natahnout z PT do SNFLK imho to tech hlasek vygeneroval mnohem vic nez je v SAPI Eventech.

**Comment by odinuv** [comment]
no muze tam hrat roli bufferovani, pokud to posilalo hodne rychle za sebou, tak ty eventy jsou slity takze jich bude v sapi min

**Comment by ujovlado** [comment]
Toto sa nam uz stalo viac krat ale tie SAPI eventy to nezahltilo. Imho to bude tym, ze to do toho container logu slo mrte rychlo.

**Comment by ujovlado** [comment]
napr. kedy pustim `yes` tak na stdout ide len `y`, no v logoch mam:

```
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526266726Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526269194Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.52627154Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526274005Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526276674Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526279012Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.52628135Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526283738Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.52628608Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526288467Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526290826Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526293153Z"}
{"log":"y\r\n","stream":"stdout","time":"2017-02-08T08:47:40.526295484Z"}
```

**Comment by odinuv** [comment]
udelat limit na to, aby docker runner treba po 10k eventech ten job kilnul je asi celkem v pohode

**Comment by Halama** [comment]
ted jsme se o tom bavili s najlosem a fakt to bude tim ze to truncatuje ty eventy a zaroven to sapi urcite nestihalo odebrat.

Dohodli jsme se ze nastavime globalne to omezeni json-file na instanci.

A co se tyce throttlingu event tak o to by se melo postarat SAPI, mame v PB.

**Comment by Halama** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by odinuv** [comment]
je teda potreba jeste zkusit jak ten container potom skonci, aby to napsalo nejakou rozumnou chybu ven

**Comment by Halama** [comment]
ten pojede normalne dal

**Comment by odinuv** [comment]
a neni to blby? kdyz potom chcipne s nejakou chybou tak tam nebude ne?

**Comment by Halama** [comment]
vzdyt ty logy ve FS se vubec nepouzivaji ne? Nechame je tam jenom pro to kdyby chtel clovek rucne debug. A ono to odroluje takze posledni tam budou.

**Comment by Halama** [comment]
na stdout ktery zpracovava runner to poleze porad

**Comment by ondrejhlavacek** [comment]
používá se tam `docker inspect` (detekce OOM a restarty terminovanejch kontejnerů) a ten by to snad ovlivnit nemělo

**Comment by Halama** [comment]
jo tyka se to jenom volani `docker logs`

**Comment by ondrejhlavacek** [comment]
no a jestli ty logy rolujou, tak je to úplná pohoda - takže ono to zahodí aktuální soubor a vytvoří novej prázdnej, kam to povalí dál, žejo?

**Comment by Halama** [comment]
jj, je potreba omezit `max-files` ale

**Comment by ondrejhlavacek** [comment]
nedává mi asi moc smysl nastavovat `max-files` na něco jinýho než 1, protože `docker logs` stejně bere jen ten poslední soubor.

**Comment by Halama** [comment]
jo

**Comment by odinuv** [comment]
jasne, tak to jsem vubec nepochopil, oukej

**Comment by ondrejhlavacek** [comment]
tak se to chová přesně tak

**Comment by ondrejhlavacek** [comment]
nasazeno
