### ISSUE TITLE
Write metadata - default and component defined in output manifests. 

### ISSUE THREAD

**Issue by pivnicek** [keboola/docker-bundle#137]
We can start with writing for each output table the keys `KBC:author:configuration:id`, `KBC:author:component:id`, `KBC:author:token:id` which expanded out would look like:
```
"KBC": {
    "author": {
        "configuration": {
            "id": "my-funny-new-configuration"
        },
        "component": {
            "id": "keboola.ex-generic-v2"
        },
        "token": {
            "id": 1234
        }
    }
}
```
Each component, however, could theoretically declare that it will provide additional metadata to the table.  for example, an output table manifest for a natural language processing app could have defined metadata as follows:
```
metadata: [
    {
        "key": "language",
        "value": "cz" 
    },
    {
        "key": "usedBeta",
        "value": false
    }
],
columnMetadata: {
    "columnA" : [
        {
            "key": "average:sentiment"
            "value": -1.23455667
        },
        {
             "key": "topic.label",
             "value": "Science and Technology"
        },
        {
             "key": "topic.confidence",
             "value": 0.527163
        }
    ]
}
```

**Comment by pivnicek** [comment]
I suppose that the metadata section could be tacked onto the current table manifest.  Otherwise, I suppose it could have its own manifest file.

**Comment by ondrejhlavacek** [comment]
I think we can utilize (cc @ujovlado) current table manifest

How would the two examples translate into metadata api responses?

**Comment by pivnicek** [comment]
responses?  the format above is the same structure (minus a couple of elements such as `provider` and `timestamp`) as you get when calling table detail with include `metadata,columnMetadata`.  But I'm not sure I understand the question.  The bundle imho would use the sapi client to write these values.
http://docs.keboola.apiary.io/#reference/metadata/createupdatelist-bucket-metadata/metadata-list-for-object
There isn't a direct GET on metadata yet.

**Comment by Halama** [comment]
Table detail response:
```
"metadata": [
  {
    "key": "KBC:configuration:id":,
    "value": "my-funny-new-configuration",
    "provider": "docker-runner"
  },
  {
     "key": "KBC:component:id":,
     "value": "keboola.ex-generic-v",
    "provider": "docker-runner"
 } ,
{
        "key": "language",
        "value": "cz" ,
   "provider": "docker-runner"
    },
    {
        "key": "usedBeta",
        "value": "false",
   "provider": "docker-runner"
    }
]
```

**Comment by pivnicek** [comment]
yo, except the 
```
{
        "key": "language",
        "value": "cz" ,
   "provider": "the-language-app-component"
    }
```

**Comment by Halama** [comment]
yes I wasn't sure about the provider of custom metadata from components. Component id makes sense here.

**Comment by ondrejhlavacek** [comment]
The keys would be `KBC.component.id`, and the provider `keboola.docker-bundle`? Or what is the mapping between provider and component in Storage?

**Comment by pivnicek** [comment]
provider is an nullable FK to componentId

**Comment by pivnicek** [comment]
so, metadata from the UI would need to have prefixed key as `KBC.UI.whatever`  and provider would be null.

**Comment by ondrejhlavacek** [comment]
Metadata from UI is name, description, etc?

**Comment by pivnicek** [comment]
treba

**Comment by pivnicek** [comment]
so, the keys defined in the manifest by the component would have provider as that componentID.  And the default keys given to every output by docker runner such as `KBC.configuration.id` will have provider `docker-runner`

**Comment by Halama** [comment]
so provider `docker-runner` also doesn't make sense because it is not component. We were speaking about some `system` provider od `keboola` provider for common stuff?

**Comment by ondrejhlavacek** [comment]
that's what i was trying to say :-)

**Comment by pivnicek** [comment]
hold on, `docker` is a component, no?

**Comment by odinuv** [comment]
it dependes whether we want to distinguish between metadata written by e.g. storage, docker-runner, provisioning, if not, we may store it as provider system and don't care

**Comment by odinuv** [comment]
it is, but we're going to delete it probably :) it's a fake

**Comment by pivnicek** [comment]
ah, it's a good fake!  totally got me :-)

**Comment by pivnicek** [comment]
ok, I'm cool with using a generic system provider

**Comment by pivnicek** [comment]
hmmm,  it's kind of the same issue as with the UI.  could it be useful to know whethere SAPI or DR or TAPI wrote the meta?  probably

**Comment by pivnicek** [comment]
key namespacing could resolve that for our system keys

**Comment by Halama** [comment]
so isn't the `provider`  unnecessary?

**Comment by pivnicek** [comment]
yes, it can be `null` for KBC keys.

**Comment by odinuv** [comment]
finished in a66f2a63d34744a82ba082f73113b7757392426a
