### ISSUE TITLE
missing oauth credentials - user error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#138]
https://connection.keboola.com/admin/utils/logs?file=2017/02/22/13/2017-02-22-13-07-42-58ad7f0e85ba7-log
https://connection.keboola.com/admin/utils/logs?file=2017/02/22/13/2017-02-22-13-07-42-58ad7f0e711cc-exception

**Comment by odinuv** [comment]
fixed in 4261783cf5db051099458693f614da40d88b460f
