### ISSUE TITLE
name of file in input mapping

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#14]
When creating input mapping for file{storage->input->files}, docker-bundle downloads the file into the /data/in/files under the name of its id `$fileInfo["id"]`. Would be great if its name was appended as well i.e `$fileInfo["id"]_$fileInfo["name"]`

https://github.com/keboola/docker-bundle/blob/8a8aae53d7f9aef67e7e7fcd7cdad04e3bc37858/Docker/StorageApi/Reader.php#L85

example: 
file was downloaded under name **12345678.tde** into the folder, the desired name would be **12345678_in.c_main.data.tde**

**Comment by odinuv** [comment]
Fixed in 18e326098bb83f4e33dbed9b690aed1f618fe06a
