### ISSUE TITLE
Test passing errorneously

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#141]
This doesn't catch the right exception (or message) https://github.com/keboola/docker-bundle/blob/master/Tests/Functional/DataLoaderTest.php#L184
and actually tries to load data from sapi, which it shoudn't, the errornous configuration is not being catched

**Comment by odinuv** [comment]
also use a more stupid name than 'test' for the table name :)

**Comment by ondrejhlavacek** [comment]
or use a fresh project for tests :-)

**Comment by Halama** [comment]
na zacatku kazde test metody by se mel cistit ne?

**Comment by odinuv** [comment]
naopak, to nema vubec s tabulkama operovat!

**Comment by ondrejhlavacek** [comment]
to jo, ale jen věci relevantní pro ten test, což tabulka ani bucket není.

**Comment by odinuv** [comment]
fixed in 567fc7fe7df90721a361ddb0f5175a0afd956e25
