### ISSUE TITLE
input mapping add changedSince parameter

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#142]
sapi podporuje export dat na zaklade filtru changedSince co je vstupom php fce `strtotime`. Docker runner to umoznuje v input mappingu zadat cez `days` parameter. Bolo by super aby umoznil presne specifikovat `changedSince` a tym by bolo mozno filtrovat data s mensou granularitou napr. po hodinach

**Comment by ujovlado** [comment]
mne sa zda sa sme to vyhadzovali prave :)

**Comment by ujovlado** [comment]
Related to? https://github.com/keboola/docker-bundle/issues/43

**Comment by odinuv** [comment]
@kacurez @ondrejhlavacek - co tady s tim ? budem to vracet zpatky (BC break) nebo podporovat oboji?

**Comment by kacurez** [comment]
snazim sa dohladat kde sme to riesili ze by bolo fajn mat podporu `changed_since` ale nenasiel som nic :( No obcas pride niekto stym ze napr 2 hodinovy inkrement. 
Ak by sa vyriesil a implementoval adaptivny incremental input mapping tak sa tato issue moze zavriet
https://keboola.productboard.com/feature-board/6271-planning/features/100882

**Comment by odinuv** [comment]
tak to tady zavrem a projedem pres PB ?

**Comment by odinuv** [comment]
nechavam teda na https://keboola.productboard.com/feature-board/6271-planning/features/100882
