### ISSUE TITLE
Staging storage - not documented

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#143]
Asi by mělo být tady https://developers.keboola.com/extend/common-interface/config-file/#tables ?
Nikde jsem k tomu nic nenašel, jde o:
```
"staging_storage": {
          "input": "s3"
        }
```

**Comment by odinuv** [comment]
Tyjo mel jsem pocit, ze to @ondrejhlavacek  nekam psal, ale taky to nemuzu najit

**Comment by Halama** [comment]
jj je to divny dokumentace vetsinou vznika s tou featurou posledni dobou...

**Comment by odinuv** [comment]
Fixed in https://github.com/keboola/developers-docs/commit/be17b0ad1a604cdefa22703fc5c854172b325618
