### ISSUE TITLE
actions user exceptions

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#146]
actions user exceptions should return plain strings and docker runner will transform it into na json response.

backward compatibility - parse output from the user exception and if it is a valid json, just use the json

**Comment by ondrejhlavacek** [comment]
tak omyl, chová se to správně, fixnul jsem dokumentaci
https://github.com/keboola/developers-docs/commit/9ee7140c586a8ca1ed0ecc5a91c21b47455bb138

**Comment by odinuv** [comment]
to je super :)
