### ISSUE TITLE
filter files by runId via query parameter

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#15]
SAPI  allows to filter file uploads by *runId*, the query would look like:
`https://connection.keboola.com//v2/storage/files?q=runId:12345678`
or this should work the same as well
`https://connection.keboola.com//v2/storage/files?runId=12345678`

Docker-bundle currently implements this feature by filtering files that contains tags with format `runId-12345678`
https://github.com/keboola/docker-bundle/blob/8a8aae53d7f9aef67e7e7fcd7cdad04e3bc37858/Docker/StorageApi/Reader.php#L109

The reason to filter files by `runId` parameter and not by tags with desired format is that it respects runIds hierarchy, so if a file is uploaded with runId *xxx.yyy*, then filter via `?q=runId:xxx` would return this file and also automatically other files underlying the xxx runId(xxx.zzz, xxx.aaa.bbb etc.)

**Comment by odinuv** [comment]
fixed in 0776502b7ecaf58a619861a353744270e326d3c7

**Comment by kacurez** [comment]
It does filter files via sapi client `runId` parameter but actual **runId** value that is used is wrong, it should be parentId and not current job runId.
The fix is very simple imho
this line here:
https://github.com/keboola/docker-bundle/blob/master/Docker/StorageApi/Reader.php#L111
I kindly reccomend to change to:
`$options->setRunId($this->getParentRunId());`

**Comment by odinuv** [comment]
So now it takes files with current job runId and parent job runId - like so:
https://github.com/keboola/docker-bundle/blob/master/Tests/Docker/StorageApiReaderTest.php#L174

is that ok, or shall I remove the current job id altogether?

**Comment by odinuv** [comment]
@kacurez  I'd like to rename it to `filter_by_run_id` so that it follows the convention of `processed_tags` can i?

**Comment by kacurez** [comment]
resume: the docker-bundle is using getParentRunId method and the param name is `filter_by_run_id`
