### ISSUE TITLE
Multi-row configs

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#150]
# Use Case

Narážíme na pomalou adopci nového S3 extraktoru, protože umí stahovat pouze jeden soubor. Generuje příliš mnoho bucketů a v každém z nich pouze jednu tabulku. Rozšířit extraktor v současné podobě by znamenalo buď

a) veškerou funkcionalitu procesorů přesunout do přímo extraktoru (a tím je defakto prohlásit za mylný koncept), nebo
b) rozšířit procesory tak, aby uměly zpracovávat víc logických toků zároveň (napříkad merge files by musel umět rozlišit mezi jednotlivými "tasky" s3 extraktoru); to by vyžadovalo předávání informací o datech ve směru pouštění komponent a procesorů

Podobný problém jsme pokoušeli adresovat v úvahách o repozitáři credentials (znovupoužití credentials mezi více konfiguracemi jedné komponenty), ale tenhle use case to neřeší. Přidání jedné nové konfigurace ze stejného S3 bucketu 

a) vyžaduje upravit všechny orchestrace, a ty možná ani neznám,
b) vytvoří nový bucket a tím roztrhává logické seskupení dat z jednoho zdroje
c) dělá bordel v seznamu konfigurací (podobně by teda musela být vlastní konfigurace pro každou tabulku writeru nebo query extraktoru)

# Řešení

Multi-row konfigurace defakto jen kopírují mechanismus, který používají transformace (bucket konfigurací), GoodData writer (konfigurace).

Vzorová konfigurace transformací vypadá cca takhle

```
{
  "name": "Demo Config",
  "description": "",
  "configuration": {},
  "rows": [
    {
      "id": "1",
      "configuration": {
        "output": [...],
        "queries": [...],
        "input": [...]
      }
    },
    {
      "id": "2",
      "configuration": {
        "output": [...],
        "queries": [...],
        "input": [...]
      }
    }
  ]
}
```

Mechanismus, jak se to pouští je celkem jasnej. Docker Runner by v rámci jednoho svého Syrup jobu mohl jednotlivé řádky pouštět jako vlastní kontejner, i s případnými procesory. Iterace řádků configu by se přenesla z komponenty do Docker Runneru.

Jaký jsou výhody, pokud něco takového bude podoporovat i Docker Runner?

### 1) Zjednodušení komponent. 

Komponenty budou vždy řešit exekuci jednoho dotazu (jedné `row`), nikdy nebudou muset na vstupu umět nic víc, žádné iterace. To stejné platí pro procesory - ty budou řešit jednoduchej tok dat.

### 2) Sdílení konfigurace. 

Pokud v kořenovém uzlu `configuration` budou nějaká data, budou se mergovat do konfigurací jednotlivých řádků. Tam můžou bejt třeba credentials platné pro všechny řádky.

Např.
```
{
    "name": "Demo Config",
    "description": "",
    "configuration": {
        "parameters": {
            "token": "KBC:Encrypted=="
         }
    },
    "rows": [
        {
            "id": "1",
            "configuration": {
                "parameters": {
                    "queries": [...]
                }
                "storage": {...},
                "processors": {...}
            }
        }

    ]
}
```

by se při pouštění řádku 1 merglo např. na 

```
{
    "parameters": {
        "queries": [...],
        "token": "KBC:Encrypted=="
    }
    "storage": {...},
    "processors": {...}
}
```

Můžeme ještě navíc říct že v top level configu můžou být jen `parameters` a můžeme ty top level `parameters` třeba ještě zabalit do nějakého vlastího uzlu (`parameters.parent`?).

### 3) Postupné nahrávání dat.

Data budou nahrávána do Storage po každém řádku. Menší nároky na disk za běhu komponenty, rozložení zatížení v čase.

### 4) Jednoduché puštění jednoho řádku.

Doteď to musela umět komponenta. Teď to bude řešit Docker Runner. 

### ~5) Definované řídící atributy.~

Hotovo, `disabled` je uložený u row.

### 6) Změny v API

Bude to jen jednoduché přidání atributu `row` do těla API call při zakládání jobu.

#### Create a job
```
## Create a job [/{component}/run]

Create an execution job on a specified component.

+ Parameters
    + component (string) ... KBC component Id

### Run job [POST]

+ Request Stored configuration (application/json)
    + Headers

            X-StorageApi-Token: 123456

    + Body

            {
                "config": "next-order-1"
            }
```
=>
```
## Create a job [/{component}/run]

Create an execution job on a specified component.

+ Parameters
    + component (string) ... KBC component Id

### Run job [POST]

+ Request Stored configuration (application/json)
    + Headers

            X-StorageApi-Token: 123456

    + Body

            {
                "config": "next-order-1",
                "row": "my-row"
            }
```

#### Create a job with image

```
## Create a job with image [/{component}/run/tag/{tag}]

Create an execution job on a specified component while using a specific image tag.

+ Parameters
    + component (string) - KBC component Id
    + tag (string) - docker image tag to be used

### Run job [POST]

+ Request Stored configuration (application/json)
    + Headers

            X-StorageApi-Token: 123456

    + Body

            {
                "config": "next-order-1"
            }
```
=>
```
## Create a job with image [/{component}/run/tag/{tag}]

Create an execution job on a specified component while using a specific image tag.

+ Parameters
    + component (string) - KBC component Id
    + tag (string) - docker image tag to be used

### Run job [POST]

+ Request Stored configuration (application/json)
    + Headers

            X-StorageApi-Token: 123456

    + Body

            {
                "config": "next-order-1",
                "row": "my-row"
            }
```

### 7) ES mapping
```
{
    "params": {
        "dynamic": "strict",
        "properties": {
            "component": {
                "type": "string"
            },
            "config": {
                "type": "string"
            },
            "configData": {
                "type": "object",
                "enabled": "false"
            },
            "mode": {
                "type": "string"
            },
            "tag": {
                "type": "string"
            },
            "format": {
                "type": "string"
            }
        }
    }
}
```
=>
```
{
    "params": {
        "dynamic": "strict",
        "properties": {
            "component": {
                "type": "string"
            },
            "config": {
                "type": "string"
            },
            "row": {
                "type": "string"
            },
            "configData": {
                "type": "object",
                "enabled": "false"
            },
            "mode": {
                "type": "string"
            },
            "tag": {
                "type": "string"
            },
            "format": {
                "type": "string"
            }
        }
    }
}
```

### 8) Metadata

Tabulky vytvořené row budou podepsané configem i row. To ničemu nevadí, zpětně kompatibilní to je stoprocentně.

`KBC.createdBy.configurationRow.id` nebo `KBC.createdBy.configuration.row.id`? Za mě asi spíš `KBC.createdBy.configurationRow.id`.

### State

State je na úrovni celé konfigurace, což by pro komponenty s multi-row konfiguracemi byl problém. State by se v Storage mohl rozšířit i na konfigurační řádek. Dokud nenarazíme na komponentu, která potřebuje multi-row config a state, nebylo by nutné implementovat.

### ~Chybějící vhodné atributy `row` konfigurace~

Hotov, řádek má `name`, `description` a `isDisabled`.

**Comment by odinuv** [comment]
hele to vypada fakt dobre, prevalim to jeste poradne v hlave - melo by to nejakej api call na spusteni jen jednoho radku ?

**Comment by ondrejhlavacek** [comment]
Myslím, že vlastní api call na to nebude potřeba, bude stačit parametr v api callu na založení jobu.

**Comment by ondrejhlavacek** [comment]
Tak, mám zádrhel - pořadí rows (určuje zobrazení v UI a pořadí pouštění v aplikaci) - viz https://github.com/keboola/transformation-bundle/issues/59. Pouštění jednoho řádku je jednoduché, to bude přes id row, nikoliv přes index.

**Comment by ondrejhlavacek** [comment]
Dneska jsem narazil na další use case, kde by se multirow config hodil.

https://keboola.zendesk.com/agent/tickets/6699

Klient si přeje, aby FTP extraktor uměl mergovat soubory / poslat více souborů do jedný tabulky. David Ešner musí upravit extraktor aby to udělal, nebo aby vytvořil manifest pro sliced file. 

Kdyby to bylo v multirow režimu, tak jediný, co se udělá je, že se pro danej soubor / řádek konfigurace zapne procesor na merge souborů nebo procesor, co z více souborů udělá sliced file + manifest. Celý by to byla jen změna v UI.

**Comment by ondrejhlavacek** [comment]
`parameters.parent` mi teď přijde jako blbost (komponenta by musela vědět, že je dělaná na řádky). Deep merge by tam asi měl bejt a row má vyšší prioritu než config.

**Comment by ondrejhlavacek** [comment]
Upravil jsem v popisku už hotový věci a přidal změnu na API a v ES mappingu.

**Comment by ondrejhlavacek** [comment]
Vyhodil jsem metadata ze sekce komplikací, když se podepíše založená tabulka i řádkem, ničemu to nevadí.

**Comment by ondrejhlavacek** [comment]
Jediný, co tam teda zbejvá v komplikacích, je `state`. Jdu se podívat, kde se používá state.

**Comment by ondrejhlavacek** [comment]
State po komponentách

![image](https://user-images.githubusercontent.com/497675/30774480-334a517e-a083-11e7-9ab3-89a6081ecb79.png)

Templaty nad genericem nás nezajímají, tak pak tam zbývá odhadem `htns.ex-salesforce`, `esnerda.ex-ftp`, `esnerda.ex-bingads`, `ex-youtube-reporting`, `keboola.ex-gmail`, `esnerda.ex-appnexus`, `esnerda.ex-leonardo`, `esnerda.ex-iceportal`, `esnerda.wr-intercom`, `apify.apify` a asi pár dalších, ale všech 50 jsem nekontroloval :-).


Tady jsou nějaký examply states, co si ukládaj:

### htns.ex-salesforce

```json
{"bulkRequests":{"Account":1504358024685,"Contact":1504358016701}}
```

to vypadá na nějaký async joby?

### esnerda.ex-ftp

```json
{"visitedFolders":[{"folderPath":"\/Eloqua-Production\/Lookups\/Contact\/","lastRun":1485381612607,"lastMapping":{"ftpPath":"\/Eloqua-Production\/Lookups\/Contact\/","sapiPath":"in.c-eloqua.ins_contact","isFolder":1,"incremental":1,"pkey":["ContactID"],"prefix":"INS_Contact_20","delimiter":"|","enclosure":"\"","extension":"txt","folder":true}}]}
```

netuším

### esnerda.ex-bingads

```
{"bulkRequests":[],"reportRequests":{"AdsPerformance":1473233444186}}
```

asi zase nějaký async joby?

### ex-youtube-reporting

```
{"content_owner_asset_annotations_a1":1506126548,"content_owner_asset_device_os_a1":1482326781,"content_owner_playlist_province_a1":1506126554,"content_owner_asset_device_os_a2":1506125127}
```

### keboola.ex-gmail
```
{"query-dates":{"from:petr@keboola.com":"2016-03-13 10:25:12"}}
```

### apify.apify
```
apify.apify
```

**Comment by ondrejhlavacek** [comment]
State by se teda mohl chovat tak, že by byl u každého řádku. State u configu by byl pouze pro komponenty, který nepracujou s řádkama. Ještě nevím, jak takové komponenty od sebe odlišit, ale mohli bychom paušálně říct, že ty, co mají něco v `rows` pojedou po řádcích, takže to bude čistě věc konfigurace.

**Comment by odinuv** [comment]
myslim, ze to rozlisi docker runner - kdyz bude v konfiguraci `rows` tak bude state ukladat postupne ke kazdemu radku jak je bude spoustet, kdyz tam rows nebude, tak to ulozi do rootu

**Comment by ondrejhlavacek** [comment]
jo, takhle si myslím, že to bude OK

**Comment by ondrejhlavacek** [comment]
A! Na jednu věc jsem zapomněl - usage. Můžeme si dovolit říct, že usage má pro všechny řádky stejnou metriku a value se prostě sečte?

**Comment by odinuv** [comment]
jop, stejne to @ujovlado  scita ne?

**Comment by ujovlado** [comment]
usage by som riesil per komponentu (tak je to vlastne teraz) ... t.j. ak by sa stalo ze mam config row a kazdy z nich ma inu metriku (vymyslim si, napr. keby gmail riesil pocet api calls a nasledne geneea pocet slov), tak vo vysledku by sme to zareportovali ako 2 metriky - co je myslim cajk.

zatial sa to teda nikde nescitava

**Comment by ondrejhlavacek** [comment]
no bude se to muset sečíst pro celej job. udělal bych to tak, že pokud v jobu už metrika je a bude se tam chtít zapsat nová s jinou metrikou, tak to vyfailuje. pokud bude stejna metrika, hodnoty se sečtou a uloží. pokud to bude nějaký komplikovanější (jak píše Ujo, a to navazuje spíš na https://github.com/keboola/docker-bundle/issues/175), tak se bude muset každá metrika identifikovat komponentou. proto bude možná jednodušší multi-component řešit na úrovni queue/storage, aby každá komponenta byla vlastní syrup job?

**Comment by odinuv** [comment]
no ale tady se bavime o multirow a to je porad jedna komponenta, v multi component to pak musi vratit usage pro kazdou komponentu zvlast

**Comment by ujovlado** [comment]
no ja som to pochopil tak, ze jeden row = jeden job :) ak to teda tak nie je, tak mozeme `usage` zapisovat per komponenta (1 row = jedna komponenta).

**Comment by ondrejhlavacek** [comment]
@ujovlado tím row myslíš co? config row? nebo něco u jobů?

**Comment by odinuv** [comment]
@ujovlado tady ted resime, ze jedna komponenta spusti vic 'jakoby konfiguraci' (nerika se v asii kvazikonfiguraci? :)) v jednom jobu, kazdopadne jde o jednu komponentu, ktera se ve vysledku projevi jako jeden syrup job, tak me prislo prirozeny to secist, ale dalo by se to vratit i jako pole hodnot - to by zjednodusilo tu #175

**Comment by ujovlado** [comment]
@ondrejhlavacek  Ano myslim tym config row. @odinuv Jasne, ja to chapem

Teraz to mame takto:

```json
{
  "usage": [
    {
      "metric": "API calls",
      "value": 150
    }
  ]
}
```

Ak by jeden job pokryval viac komponent, moze sa to:

1. bud priprdnut do toho pola (tam ale stracame kontext, kto to vytvoril)
2. alebo to rozsirime a bude to nieco taketo:

```json
{
  "usage": {
    "component-1": [
      {
        "metric": "API calls",
        "value": 150
      }
    ],
    "component-2": [
      {
        "metric": "Characters",
        "value": 1000
      }
    ]
  }
}
```

**Comment by ujovlado** [comment]
Ta 2. cast mi pride asi lepsia, inak v tom asi bude border. Lebo tie komponenty mozu mat podobne/rovnake metriky a to sa teda asi nebude dat spocitat.

**Comment by ujovlado** [comment]
A vlastne by slo toto:

```json
{
  "usage": [
    {
      "component": "component-1",
      "metric": "API calls",
      "value": 150
    }
  ]
}
```

**Comment by ujovlado** [comment]
Takze `usage` file by sa spracoval po kazdom behu a ulozil by sa do toho pola podla komponenty. :)

**Comment by odinuv** [comment]
no takze to v ramci mulitrow bude vrace:

```
{
  "usage": [
    {
      "component": "component-1",
      "metric": "API calls",
      "value": 150
    },
    {
      "component": "component-1",
      "metric": "API calls",
      "value": 581
    }
  ]
}
```

**Comment by ujovlado** [comment]
Ano, a ako to spocitame je myslim zatial sumak, resp. to mozeme nechat na konzumenta.

**Comment by ondrejhlavacek** [comment]
@odinuv ok! to zni asi nejlíp! podle mě můžem teda zatím `component` vynechat? nebo to mám dodělat i do queue? chtěl jsem se trochu vyvarovat salámování a multirow bude vždycky jen jedna komponenta.

**Comment by odinuv** [comment]
bych to zaitm vynechal

**Comment by ondrejhlavacek** [comment]
Koukám do zdrojáků a snažím se vymyslet, ja to co nejjednodušeji pojmout. Napadl mě adaptér mezi configama a Runnerem.

https://github.com/keboola/docker-bundle/blob/7c30532a39d1d84f976123d91c2c97cc8792fca4/Service/Runner.php#L201

Tady by se signatura metody změnila na 

```
public function run(ConfigurationCollection $configs, $action, $mode, $jobId)
```
Na začátku by byl cyklus, kterej by `ConfigurationCollection` proiteroval a uvnitř cyklu by se to rozdrobilo do původních proměnných `$componentData`, `$configId` a `$configData`.

Takhle by byla ConfigurationCollection uvnitř.

![image](https://user-images.githubusercontent.com/497675/31168981-87905130-a8f7-11e7-9ee8-cb7de4119c0d.png)

`ConfigurationCollection` by se naplňovala z `configData` (bez configId, rowId a verzí) nebo výstupem z `Components::getConfiguration()` (configIds, rowIds, verze) a řešila by asi i dekryptování? Tj část obou větví tohodle ifu:

https://github.com/keboola/docker-bundle/blob/7c30532a39d1d84f976123d91c2c97cc8792fca4/Job/Executor.php#L146

Tohle by podle mě umožnilo

a) transparentně řešit multirow vs no-rows configy
b) zjednodušit případný multicomponent configy
c) mít na jednom místě validaci a mergování configů z/do rows (snadno otestovatelný)

Jakýkoliv sandboxový cally by failovaly pro `count($configs) > 1`.

Co si o tom myslíš @odinuv?

**Comment by odinuv** [comment]
no tak ta collection nevim jesli ma smysl, zase bude muset nejak vytvaret a co z toho ze je iterable, bych na to sel nejak tak, ze bude trida ConfigProcessor($componentId, $configId, $configData), ktera bude mit metody getConfigs():  ProcessedConfig[] a ProcessedConfig bude mit metody getComponentData, getRowId, getRowData, run prejmenovat na runRow() (signatura zustava stejna) a pridat run, ktere iteruje pres getConfigs() pricemz getRowId a getRowData bude vracet configId a configData pro NEmultirow config (ale to si vyresi configProcessor interne), configProcesor pujde dobre otestovat

**Comment by ondrejhlavacek** [comment]
Oukej! To zní +- rozumně. Nenapadaj tě nějaký jiný názvy? Configů A processů už tam je dost. Co takhle `JobDefinition` a `JobDefinitionProcessor`?

**Comment by odinuv** [comment]
tywole nazvy, neco lehciho tam nemas? :)

**Comment by odinuv** [comment]
co treba JobCruncher ? :)

**Comment by odinuv** [comment]
a Crunchie

**Comment by ondrejhlavacek** [comment]
Něco šťavnatějšího? Squeezer!

**Comment by pivnicek** [comment]
`Ingredients` a `Cook`? :)

**Comment by odinuv** [comment]
to me pripomina Juicer a ten uz mame :)

**Comment by ondrejhlavacek** [comment]
To jsem právě chtěl držet linii :-)

**Comment by odinuv** [comment]
Owen a Cookies?

**Comment by odinuv** [comment]
budem tlusti!

**Comment by ondrejhlavacek** [comment]
No abych se vrátil zpět - budu ale určitě potřebovat udržovat rozdíl mezi `configId` a `rowId`, třeba kvůli ukládání state - musí se rozlišit, jestli se state ukládá k row nebo k configu. totéž kvůli metadatům.

**Comment by odinuv** [comment]
hmm, statefile i usagefile i dataloader se vytvari v run (tj. v runrow) kdyby se vytvarel v run, tak by se mu to dalo predat v ctoru aby vedel kam to ulozit, samotny runrow by to podle me rozlisovat nemelo

**Comment by odinuv** [comment]
potom by se teda to state, usage a dataloader melo predavat i v te run metode, protoze v this by to nebylo immutable

**Comment by ondrejhlavacek** [comment]
a co ty ostatní? `imageCreator`, `configFile`?  ty asi taky...

**Comment by ondrejhlavacek** [comment]
No asi z toho udělám subclassu, `RowRunner`?

**Comment by ondrejhlavacek** [comment]
PR ready na review https://github.com/keboola/docker-bundle/pull/196
