### ISSUE TITLE
days parameter IM problem

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#151]
V dokumentacii pise ze ak do IM parametru `days` zadam 0 tak sa stiahne cela tabulka(`(0 downloads all)`) tj ten filter sa vlastne neaplikuje ale v skutocnosti sa aplikuje a 0 vrati prazdne data(csv subor len s hlavickou). Problem je vtom ze v UI sa neda tento filter zmazat ak je uz raz nastaveny - je mozne nastavit ine cislo ale 0 to vlastne nerusi a naopak vyfiltruje prazdne data. Jedno z rieseni je zmazat tu informaciu z dokumentacie a upravit to na UI aby ten filter bolo mozne z IM zmazat.

dokumentacia:
https://help.keboola.com/manipulation/transformations/mappings/#input-mapping

priklad IM:
```
"input": {
       "tables": [
            {
                "source": "out.c-restaurants.restaurants_reviews",
                "destination": "out.c-restaurants.restaurants_reviews.csv",
                "days": 0
            } 
       ]
     }
```
exportny event sapi:
![image](https://cloud.githubusercontent.com/assets/1412120/24755288/dae97b42-1ad9-11e7-9060-c4a859dc0421.png)

**Comment by odinuv** [comment]
Tady https://github.com/keboola/input-mapping/blob/master/Reader/Reader.php#L269 by melo byt `!empty`

Soucasne je to ale podle me bug i na UI, protoze kdyz z UI smazu tu 0, tak to skonci na 
Invalid type for path "container.storage.input.tables.0.days". Expected int, but got NULL.

-> tj. posle to `days: null` misto toho aby to tam nedavalo vubec.

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/input-mapping/commit/008436fb87e8847bdd9dc0165560acbd3fcc5af9
and https://github.com/keboola/docker-bundle/commit/3acc86a91882e9b5e7dcee042fbdd8dbb6803808
