### ISSUE TITLE
[dca] git clone with retry mechanism

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#153]
Pocas run custom science appky obcas vyfailuje command **`git clone`** s hlaskou `Cannot access the Git repository...` Riesenim je zaviest retry mechanizmus:

**povodny git clone command:**
```
git clone -b {{version}} --depth 1 {{repository}} /home/ || (echo \"KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR\" && exit 1)
```

**template shell command** ktory neuspesne zavola error_command 4 krat zasebou s 5 sekundovym odstupnovanym delayom a vrati exit code != 0
```
(for i in 0 1 2 3; do sleep $((5 * $i)) && error_command && exit; done)
```

**vysledny git clone command** s retry mechanizmom:
```
(for i in 0 1 2 3; do sleep $((5 * $i)) && git clone -b {{version}} --depth 1 {{repository}} /home/ && exit; done) || (echo \"KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR\" && exit 1)
```
Zaroven by to bolo vhodne uviest v dokumentacii ako best practice.

Custom science apky ktore v definicii maju `git clone` command (podla https://connection.keboola.com/v2/storage):

Non Keboola apky:
- [ ] datamind.custom-r (nefunguje!)
- [x] dca-alook-analytics
- [x] fisa.app-gd-custom-colors
- [x] medio.custom-attribution

~- [ ] cleveranalytics.dca-custom-science-python~

Keboola apky:
- [x] dca-custom-science-python
- [x] dca-custom-science-python2
- [x] keboola.custom-science-php
- [x] dca-custom-science-r
- [x] dca-example-branch
- [x] dca-example-private
- [x] dca-python-text-splitter
- [x] dca-r-transpose
- [x] dca-r-tree
- [ ] docker-shiny-app-deploy
- [ ] keboola.shinyapp-deployment

~- [ ] testing.dca-custom-science-actions~ (not public)
~- [ ] dca-php-hierarchy~

**Comment by kacurez** [comment]
tak ten bashovy retry command je zreme chybovy
mam napr tento command u **dca-example-ranch**:
```
(for i in {0..3}; do sleep $((5 * $i)) && git clone -b {{impersonate}} --depth 1 {{repository}} /home/ && exit; done) || (echo "KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR" && exit 1)
```
ak pusti componentu tak hned spadne s hlaskou:
`Cannot access the Git repository https://github.com/keboola/r-custom-application-example-branch, please verify its URL, credentials and version (if tag or branch exists).`

any ideas?

**Comment by ondrejhlavacek** [comment]
To je divný, trochu jsem stripnul texty a tohle mi šlape
```
$ (for i in {0..3}; do sleep $((5 * $i)) && git clone aabb && exit; done) || (echo "user error" && exit 1)
fatal: repository 'aabb' does not exist
fatal: repository 'aabb' does not exist
fatal: repository 'aabb' does not exist
fatal: repository 'aabb' does not exist
user error
```

**Comment by ondrejhlavacek** [comment]
```
$ (for i in {0..3}; do sleep $((5 * $i)) && git clone -b {{impersonate}} --depth 1 {{repository}} /home/ && exit; done) || (echo "KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR" && exit 1)
fatal: repository '{{repository}}' does not exist
fatal: repository '{{repository}}' does not exist
fatal: repository '{{repository}}' does not exist
fatal: repository '{{repository}}' does not exist
KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR
```

**Comment by kacurez** [comment]
lokalne mi to funguje tiez ale ked to nastavim pod commands do komponenty tak to spadne.

**Comment by ondrejhlavacek** [comment]
zkoušels to pustit na nějakým workeru?

**Comment by kacurez** [comment]
neskusal, akurat som si otvoril shell cez docker container ktory bezne pouzivam. Vyskusam to este aj na workri

**Comment by ondrejhlavacek** [comment]
prdlajz worker, ten je tam zbytečnej...

**Comment by ondrejhlavacek** [comment]
tohle se totiž vloží do `Dockerfile`

**Comment by ondrejhlavacek** [comment]
Tady to je cca vidět - https://github.com/keboola/docker-bundle/blob/2172626cb680014f336a325ddcf2c7b46cfddc5a/Tests/Functional/ImageBuilderTest.php

**Comment by kacurez** [comment]
aha! good point!
ale zas ten command sa stejne pusta v shellu akurat cez docker nie? mozem sa nato este pozriet.

**Comment by odinuv** [comment]
no to je asi potreba zkusit, dockerfile neni uplne delany na psani shellovejch skriptu :)

**Comment by kacurez** [comment]
tak vypada ze problem je v zapise toho for cyklu: nevie zpracovat `{0..3};`, ak to zmenim na `0 1 2 3` tak to funguje:
RUN (for i in 0 1 2 3; do sleep $(($i * 5)) && git clone aabb && exit; done) || (echo "user error" && exit 1)
![image](https://cloud.githubusercontent.com/assets/1412120/25177045/b114ea64-2500-11e7-81d9-b7f64a18d9f4.png)

vyskusam to teraz na `dca-exmaple-branch` komponente.

**Comment by ondrejhlavacek** [comment]
Hm, tyjo, jestli `{}` nebude pro `Dockerfile` nějakej placeholder

**Comment by kacurez** [comment]
tak ta uprava zabrala - tj naklonuje git repo s retry mechanizmom podla commentu vyssie ^^.
Updatol som komponenty `dca-custom-science-python` a `dca-example-branch`, a povodny command popisany v tejto issue.

**Comment by kacurez** [comment]
@najlos vypada ze ten range vobec "nerozbalil":
![image](https://cloud.githubusercontent.com/assets/1412120/25177898/e81913a2-2503-11e7-864c-aa38ece5b4de.png)

**Comment by ondrejhlavacek** [comment]
Hm! Tak tam bude asi nějakej dost jednoduchej shellovej interpret?

**Comment by kacurez** [comment]
je to mozne ale hlavne ze to funguje :)
btw Vokurka znovu hlasi ze mu to pada, podla casov na obrazku nizsie vypada ze to ani necakalo:
![image](https://cloud.githubusercontent.com/assets/1412120/25224108/b944464a-25bd-11e7-9ca3-6d6455d38f64.png)
vyhodim chybovu hlasku z commands v definicii komponenty:
`|| (echo \"KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR\" && exit 1)`
tym sa zaloguje skutocna chyba ktoru build zahlasi.

**Comment by Halama** [comment]
Dnes to same na DCA PHP v shared configu https://connection.keboola.com/admin/projects/258/orchestrations/229790248/jobs/259833046
![image](https://cloud.githubusercontent.com/assets/903531/25263834/ba196802-2662-11e7-88c7-820ddd2be629.png)

**Comment by padak** [comment]
Ještě to jde zapsat jako for i in seq 1 3;...

**Comment by odinuv** [comment]
neni mozny ze nas nejak github blokuje?

**Comment by ondrejhlavacek** [comment]
Řekl bych, že ne, má docela dobrý chybový hlášky a napsal by to.

**Comment by Halama** [comment]
tady se ale zahazuje ta hlaska

**Comment by ondrejhlavacek** [comment]
Ah, jasně!

**Comment by Halama** [comment]
takze to klidne tak muze byt. Zaclo se to objevovat pomerne  nedavno takze by to mohlo souviset s tim ze poustime vic kontejneru najednou, zdvojnasobil jsem kapacitu workeru behem minuleho tydne postupne. Predtim to kolem druhe rani cekalo.

**Comment by Halama** [comment]
ha, tohle se stalo kolem druhe ranni :)

**Comment by Halama** [comment]
Výskyt hlášky "Cannot access the Git repository" za posledních 30 dní:

![image](https://cloud.githubusercontent.com/assets/903531/25268359/bb9cc55a-2678-11e7-86b9-887d946b2808.png)

**Comment by ondrejhlavacek** [comment]
Tak to je docela dost :-(

**Comment by ondrejhlavacek** [comment]
Budem asi muset založit nějakýho machine usera a udělat login.

**Comment by Halama** [comment]
zatím nevíme jestli je to tím, ale mohlo by.

**Comment by kacurez** [comment]
fyi custom-php nemal retry mechanizmus - tak som ho tam teraz pridal a vyhodil nami generovanu chybovu hlasku. Neviem ci to pomoze ale pre istotu
`"(for i in 0 1 2 3; do sleep $((5 * $i)) && git clone -b {{version}} --depth 1 {{repository}} /home/ && exit; done)"`

Viac kontajnerov == viac IP adries z ktorych sa pripaja na github/bitbucket?

**Comment by Halama** [comment]
ne IP adres je porad stejne.

**Comment by ondrejhlavacek** [comment]
Kontejnery běžej teď na dvou workerech.

**Comment by ondrejhlavacek** [comment]
Hodně dočasnej workaround by mohl bejt snížit výkon workeru a přidat jich víc na stejnej počet worker vláken.

**Comment by Halama** [comment]
zatim nevime jestli to tak je.

**Comment by Halama** [comment]
Za poslednich 24 hod to byly tyhle komponenty:
![image](https://cloud.githubusercontent.com/assets/903531/25269353/82442c5e-267c-11e7-9158-0922eb15646a.png)

**Comment by Halama** [comment]
A posledni dva dny:
![image](https://cloud.githubusercontent.com/assets/903531/25269396/c0675aba-267c-11e7-9351-d233deda9ffd.png)

**Comment by Halama** [comment]
V developer portalu by melo jit videt kdy se fixoval ten python.

**Comment by ondrejhlavacek** [comment]
@kacurez normální throttling. se ti nikdy u composeru nestalo, že ti to zařízli? :-)

**Comment by Halama** [comment]
ten python byl updatnutej Tomasem `2017-04-20T09:48:48.000Z` od te doby se to zatim nestalo.

**Comment by Halama** [comment]
a jde tam videt ze se to deje napric github, gitlab i bitbucket, zajimavy...

**Comment by kacurez** [comment]
composer mi padal len na pamati :)
retry do dca-custom-science-python som urcite daval aj 19.4. vid 
https://github.com/keboola/docker-bundle/issues/153#issuecomment-295227271
Den nato mi vokurka hlasil ze mu to znova spadlo tak som vyhodil tu chybovu hlasku a zatial sa nezoval. Vlastne vsetky moje kroky ako som robil som popisoval sem do issue.

**Comment by Halama** [comment]
tak mame verzovani v dev portalu

**Comment by odinuv** [comment]
@Halama do toho musis pocitat, ze se to deje casto proto, ze maji lidi blbe credentials, takze to je ok

**Comment by odinuv** [comment]
jeste by tam mohlo hrat roli to, jestli se nam nenakupily konfigurace s branch `master`, ktera neni cachovana

**Comment by Halama** [comment]
aha, ona tam neni ta hlaska:)

**Comment by odinuv** [comment]
no tu hlasku jsem ta daval proto, ze git napise nejakou debilni, neco jako "no such repository" (kdyz mas blby credentials) a protoze se na to furt nekdo ptal (jaktoze to pise ze neni kdyz je) tak je to tam tohle no :/

**Comment by Halama** [comment]
tomas ji ted prave dal pryc
![image](https://cloud.githubusercontent.com/assets/903531/25269770/5446bffe-267e-11e7-9b54-0a9fe36cfb90.png)

takze co to vraci ted.

**Comment by ondrejhlavacek** [comment]
Ta origoš debilní hláška z gitu by se mohla přilepit na konec tý naší.

**Comment by kacurez** [comment]
z custom-python som dal prec tu hlasku este vcera(20.4)
z custom-php dnes(21.4)
pozeram no vokurkove konfigy a ziadny tuto noc nespadol(custom-python/bitbucket).

**Comment by Halama** [comment]
a proc tu hlasku davas pryc? s ni to nefungovalo?

**Comment by kacurez** [comment]
chcel som vidiet co to presne hlasi a hlavne overit ten retry a podla tohto chybovy vystup vtom pripade je nahradeny uplne tou hlaskou:
https://github.com/keboola/docker-bundle/blob/master/Docker/Image/Builder/ImageBuilder.php#L437

**Comment by Halama** [comment]
super diky. Znamena to ze to potom tu chybu nikdy nehodilo? protoze na "Build failed" nic nenachazim.

**Comment by ondrejhlavacek** [comment]
Můžem search na tuhle hlášku hodit do Slacku, ať o tom hnedka víme

**Comment by kacurez** [comment]
podla toho kodu - tu chybu s hlaskou `Build failed (code:` by malo vyhodit aj v inych castiach failu buildu z dockerfilu, a to neviem ci sa deje resp. ako casto.

**Comment by odinuv** [comment]
nefunguje to https://keboola.slack.com/archives/C09U3R1J4/p1494403747729442

```
Not Found\nfatal: repository 'https:\/\/gitlab.com\/tvlk\/keboola-scripts.git\/' not found\n\u001b[0m\u001b[91mfatal: Could not get current working directory: No such file or directory\n\u001b[0m\u001b[91mfatal: Could not get current working directory: No such file or directory\n\u001b[0m\u001b[91mfatal: Could not get current working directory: No such file or directory\n\u001b[0m \/ The command '\/bin\/sh -c (for i in 0 1 2 3; do sleep $((5 * $i)) && git clone -b v1.0.4 --depth 1 https:\/\/gitlab.com\/tvlk\/keboola-scripts.git \/home\/ && exit; done)' returned a non-zero code: 128\n","code":0,"attachment":"https:\/\/connection.keboola.com\/admin\/utils\/logs?file=2017\/05\/10\/10\/2017-05-10-10-07-45-5912ca51ce43d-exception"},"attachment":"https:\/\/connection.keboola.com\/admin\/utils\/logs?file=2017\/05\/10\/10\/2017-05-10-10-07-45-5912ca51ddf93-log"}
```

**Comment by ondrejhlavacek** [comment]
@odinuv co když to tam ale fakt nebylo?

**Comment by odinuv** [comment]
no to tak asi fakt nebylo, ale produkuje to application error

**Comment by ondrejhlavacek** [comment]
teď na to koukám a v `dca-example-branch` je 

```
(for i in 0 1 2 3; do sleep $((5 * $i)) && git clone -b {{impersonate}} --depth 1 {{repository}} /home/ && exit; done) || (echo \"KBC::USER_ERR:Cannot access the Git repository {{repository}}, please verify its URL, credentials and version (if tag or branch exists).KBC::USER_ERR\" && exit 1)
```

a v `dca-custom-python` je 

```
(for i in 0 1 2 3; do sleep $((5 * $i)) && git clone -b {{version}} --depth 1 {{repository}} /home/ && exit; done)
```

chybí tam ten konec a na alpine (a devel-03) mi to hlásí 

```
/ # (for i in 0 1; do sleep $((5 * $i)) && git clone -b aabb --depth 1 ccdd /home/ && exit; done) || (echo \"KBC::USER_ERR:
Cannot access the Git repository aabb, please verify its URL, credentials and version (if tag or branch exists). KBC::USER_
ERR\" && exit 1)
/bin/sh: syntax error: unexpected "(" (expecting ")")
```

takže se tam imho musí escapovat ta závorka `(if tag or branch exists)`. Ten `dca-example-branch` je nějak otestovanej?

**Comment by ondrejhlavacek** [comment]
jj, musí se to escapovat

```
➜  docker-git-retry docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM alpine:latest
 ---> 02674b9cb179
Step 2/2 : RUN (for i in 0 1; do sleep $((5 * $i)) && git clone -b aabb --depth 1 ccdd /home/ && exit; done) || (echo \"KBC::USER_ERR:Cannot access the Git repository aabb, please verify its URL, credentials and version (if tag or branch exists). KBC::USER_ERR\" && exit 1)
 ---> Running in 8e3a0899f295
/bin/sh: syntax error: unexpected "(" (expecting ")")
The command '/bin/sh -c (for i in 0 1; do sleep $((5 * $i)) && git clone -b aabb --depth 1 ccdd /home/ && exit; done) || (echo \"KBC::USER_ERR:Cannot access the Git repository aabb, please verify its URL, credentials and version (if tag or branch exists). KBC::USER_ERR\" && exit 1)' returned a non-zero code: 2
```

```
➜  docker-git-retry docker build .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM alpine:latest
 ---> 02674b9cb179
Step 2/2 : RUN (for i in 0 1; do sleep $((5 * $i)) && git clone -b aabb --depth 1 ccdd /home/ && exit; done) || (echo \"KBC::USER_ERR:Cannot access the Git repository aabb, please verify its URL, credentials and version \(if tag or branch exists\). KBC::USER_ERR\" && exit 1)
 ---> Running in 657600c6df69
/bin/sh: git: not found
/bin/sh: git: not found
"KBC::USER_ERR:Cannot access the Git repository aabb, please verify its URL, credentials and version (if tag or branch exists). KBC::USER_ERR"
The command '/bin/sh -c (for i in 0 1; do sleep $((5 * $i)) && git clone -b aabb --depth 1 ccdd /home/ && exit; done) || (echo \"KBC::USER_ERR:Cannot access the Git repository aabb, please verify its URL, credentials and version \(if tag or branch exists\). KBC::USER_ERR\" && exit 1)' returned a non-zero code: 1
```

**Comment by ondrejhlavacek** [comment]
Gotcha, ještě jsem si chvíli hrál s escapováním, v builderu se to částečně escapuje samo. Pro `dca-custom-science-python` jsem to nahodil. Kde by to ještě mělo bejt?

```json
{
  "commands": [
    "(for i in 0 1 2 3; do sleep $((5 * $i)) && git clone -b {{version}} --depth 1 {{repository}} /home/ && exit; done) || (echo \"KBC::USER_ERR: Cannot access the Git repository aabb, please verify its URL, credentials and version (if tag or branch exists). KBC::USER_ERR\" && exit 1)"
  ]
}
```

**Comment by odinuv** [comment]
`Cannot access the Git repository aabb,` ?

**Comment by ondrejhlavacek** [comment]
kurvafix! :-( tak znovu :-)

**Comment by ondrejhlavacek** [comment]
dík, nahážu to tam!

**Comment by ondrejhlavacek** [comment]
![image](https://cloud.githubusercontent.com/assets/497675/25990538/65e9868c-3700-11e7-986f-0f0e091c73a6.png)

přidal jsem ještě {{version}} do závorky

**Comment by kacurez** [comment]
hmm nepamatam sa zeby som na podobnu chybu narazil predtym ajked som to tiez skusal buildovat lokalne. Tak super ze to je vyriesene spravne aj s logovanim :)

**Comment by ondrejhlavacek** [comment]
tak jsem fixnul tři appky a odbočil k https://github.com/keboola/docker-bundle/issues/160 
takže nejdřív fixnout #160 a pak můžem pokračovat v tomhle

**Comment by ondrejhlavacek** [comment]
`cleveranalytics.dca-custom-science-python` nepoužívá builder (!)

**Comment by ondrejhlavacek** [comment]
`datamind.custom-r` nefunguje

**Comment by odinuv** [comment]
datamind je nejakej zombac, nema to ani popis a imho to nikdy nebylo public ani to neni v `3rd Devel` - ja bych to smazal, ledaze by @padak rekl zene
