### ISSUE TITLE
remove configuration id for jobs created via configdata (skews metadata)

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#158]

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/docker-bundle/blob/b0f269af4a8bf7e7c2f79f24307da4a615fca02d/Controller/ActionController.php#L75

https://github.com/keboola/docker-bundle/blob/b0f269af4a8bf7e7c2f79f24307da4a615fca02d/Job/Executor.php#L170

**Comment by odinuv** [comment]
Fixed in a66f2a63d34744a82ba082f73113b7757392426a
