### ISSUE TITLE
builder ignores image tag

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#160]
and downloads always `latest` image

these are wrong definitions

```
"id": "dca-alook-analytics"
"uri": "quay.io/keboola/docker-custom-r:1.0.7"
```

```
"id": "dca-custom-science-python2",
"uri": "quay.io/keboola/docker-custom-python2:1.0.10",
```

```
"id": "dca-custom-science-r",
"uri": "quay.io/keboola/docker-custom-r:latest",
```

```
"id": "dca-python-text-splitter",
"uri": "quay.io/keboola/docker-custom-python:0.0.4",
```

```
"id": "dca-r-tree",
"uri": "quay.io/keboola/docker-custom-r:latest",
```

```
"id": "docker-shiny-app-deploy",
"uri": "quay.io/keboola/shiny:0.0.7",
```

```
"id": "fisa.app-gd-custom-colors",
"uri": "quay.io/keboola/docker-custom-python2:1.0.10",
```

```
"id": "keboola.shinyapp-deployment",
"uri": "quay.io/keboola/shiny:0.0.5",
```

```
"id": "medio.custom-attribution",
"uri": "quay.io/keboola/docker-custom-python:1.0.3",
```

```
"id": "testing.dca-custom-science-actions",
"uri": "quay.io/keboola/docker-custom-python:1.1.0",
```

to fix immediately after deploy

- [x] dca-alook-analytics
- [x] dca-custom-science-python2
- [x] dca-custom-science-r
- [x] dca-python-text-splitter
- [x] dca-r-tree
- [x] docker-shiny-app-deploy
- [x] fisa.app-gd-custom-colors
- [x] keboola.shinyapp-deployment
- [x] medio.custom-attribution
- [x] testing.dca-custom-science-actions

**Comment by odinuv** [comment]
ale proc jsou wrong - s tim uri to taky funguje ne?

**Comment by ondrejhlavacek** [comment]
Teď jo, ale ten fix tam explicitně dodává `:{{tag}}`, takže to začne ihned failovat. A bug je to proto, že všechny ostatný typy imagů to maj jinak.

**Comment by odinuv** [comment]
jo, uz to chapu

**Comment by odinuv** [comment]
kurnik mam porad nejakej neodbytnej pocit, ze to kvuli necemu tak bylo ale nemuzu si vzpomenout proc

**Comment by ondrejhlavacek** [comment]
Tak do deploye času dost, třeba si vzpomeneš :-D

**Comment by odinuv** [comment]
https://cdn.meme.am/cache/instances/folder772/68164772.jpg
![image](https://cloud.githubusercontent.com/assets/4319320/26001783/d1357d6a-372d-11e7-9c1e-6513113813eb.png)

**Comment by odinuv** [comment]
No mysilm, ze je to pozustatek z minulosti, kdyz to builder pouzival pro Git repozitar - tj. v dobre kdy jeste neumel parametry. Asi fakt neni duvod pro to aby to tak bylo.
