### ISSUE TITLE
staging_storage.input: none

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#165]
Mít možnost říct v nastavení komponenty ať neprovádí input mapping. Komponenta si ho pak provede sama. Use case - snowflake writer který provede IM do workspace.
Diskuze tady https://github.com/keboola/connection/issues/820#issuecomment-303043723

**Comment by odinuv** [comment]
Done in 471ea6e05c722222ccfa03adc6aa3c4cd9f950f0
