### ISSUE TITLE
Empty key in configuration is stored as _empty_

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#166]
via https://github.com/keboola/kbc-ui/issues/1021

**Comment by ondrejhlavacek** [comment]
nedělá to ani UI ani Connection

**Comment by ondrejhlavacek** [comment]
dělá to `json_decode`

```
var_dump(json_decode('{"":"value"}'));
# object(stdClass)#1 (1) { ["_empty_"]=> string(5) "value" } 

var_dump(json_decode('{"":"value"}', true));
# array(1) { [""]=> string(5) "value" }
```

**Comment by ondrejhlavacek** [comment]
https://bugs.php.net/bug.php?id=46600
Submitted:	2008-11-18 03:13 UTC	
Modified:	2016-06-23 19:15 UTC

**Comment by ondrejhlavacek** [comment]
https://keboola.zendesk.com/agent/tickets/6697

**Comment by odinuv** [comment]
Leave as is and fix in Generic https://github.com/keboola/generic-extractor/issues/68
