### ISSUE TITLE
missing / empty state file seems not to remove the state value

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#170]
https://keboola.slack.com/archives/C581KLPED/p1495785129490020

**Comment by ondrejhlavacek** [comment]
![state](https://cloud.githubusercontent.com/assets/497675/26496703/e482561c-4228-11e7-9a8d-1880a94f15a7.gif)

**Comment by odinuv** [comment]
Ha uz to mam https://github.com/keboola/storage-api-php-client/blob/master/src/Keboola/StorageApi/Components.php#L60

**Comment by odinuv** [comment]
https://github.com/keboola/storage-api-php-client/issues/134
