### ISSUE TITLE
private repository - special characters in password

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#179]
Komponenta která má dockerhub private repo:
![image](https://user-images.githubusercontent.com/903531/27540201-a27ee89c-5a7f-11e7-9f83-f0bda129b45f.png)

Pokud heslo obsahuje speciální znaky tak login neprojde, zřejmě je to špatně vyescapované.
Heslo se kterým login failoval: `x8lJz@&4rF^hDpaR@cA5`

https://connection.keboola.com/admin/utils/logs?file=2017/06/26/14/2017-06-26-14-36-59-5950ffeb7f146-log

https://keboola.zendesk.com/agent/tickets/6926

**Comment by ondrejhlavacek** [comment]
Jo, to bude `dind`em, tam je to celý ještě obalený v `sh -c`.
