### ISSUE TITLE
Remove saveConfigAction from ApiController

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#182]
Dělám teď podporu pro konfigurační řádky v UI (v nich bude potřeba taky šifrování) a ukládat konfigurace přes Docker Runner mi dneska přijde nešikovný. IMHO by Docker Runner měl konfiguraci jen zašifrovat a vrátit jí a UI by se mělo postarat o uložení. Musel bych teď Docker Runner rozšiřovat, dělat testy a při případný další změně znovu. Udělal bych radši nějakej (parametrizovatelnej) encryptor.

Rozšířil bych současnej `/{component}/encrypt` endpoint:

 - volitelně by uměl přijmout v hlavičce token (pro ComponentProject encryptor)
 - parametr v URL by řekl, jakej encryptor se má použít (Component/ComponentProject)

Pak bych to přebouchal v UI a mrknul se, jestli to ještě někdo někde nepoužívá napřímo (search v PT: https://papertrailapp.com/searches/26790882) a pak by se to mohlo celý vypnout.

**Comment by odinuv** [comment]
S ohledem na tohle https://github.com/keboola/docker-bundle/issues/92 bych urcite rekl, ze to ma byt jinej endpoint. POST na `/encrypt` by mel mit parametry:

**Comment by ondrejhlavacek** [comment]
Jak bude parametr `region` ladit s tímhle?

> Pokud vsechno souhlasi, rozsifruje payload KBC::Encrypted==... soucasnym wrapperem s klicem, ktery ma docker-bundle (kazdy stack bude mit svuj).

Imho neumíme zašifrovat pro jinej region, leda bychom to celý nějak předělali na asymetrický šifrování :-) (a to možná není blbej nápad, a mohlo by se to šifrovat na frontendu).

**Comment by odinuv** [comment]
aha, ja jsem vynechal tu vec, ze by to stalo nekde uplne bokem :)
Kdyby to sifrovani melo zustat v docker-runner, tak ten parametr region tam nebude

**Comment by Halama** [comment]
proč to docker runner rovnou neuloží, ta logika a víc requestů z UI se mi nelíbí

**Comment by ondrejhlavacek** [comment]
@Halama Přide mi dost divný, že Docker Runner musí kopírovat veškerý změny na Storage API. Když se to oddělí, na Docker Runneru už se to nebude muset nikdy měnit.

**Comment by ondrejhlavacek** [comment]
@odin, jdu na to, ale zatím bych vynechal parametr `configurationId`?

**Comment by odinuv** [comment]
budes to delat se starym sifrovanim ne? tak bych to udelal bez configId, to pridame az s novym sifrovanim

**Comment by ondrejhlavacek** [comment]
jj, se starým

**Comment by ondrejhlavacek** [comment]
will fix https://github.com/keboola/docker-bundle/issues/192

**Comment by odinuv** [comment]
odstranim spolecne s https://github.com/keboola/docker-bundle/issues/227

**Comment by odinuv** [comment]
waits for https://github.com/keboola/config-migration-tool/issues/18
