### ISSUE TITLE
pygelf not logging in expected format

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#189]
Latest version of pygelf (0.3.1) does not specify the `host` attribute, the payload looks like

```
array(
  'level' => '6', 
  'source' => 'a557e3ac972a', 
  'version' => '1.1', 
  '_some' => array('structured' => 'data'), 
  'timestamp' => '1503527709.861', 
  'short_message' => 'Reports requested:'
)
```

https://connection.keboola.com/admin/utils/logs?file=2017/08/24/01/2017-08-24-01-28-28-599e0f9c8398a-exception

The expected format is specified on http://docs.graylog.org/en/2.3/pages/gelf.html#gelf-payload-specification and there is no `source` attribute.

Pygelf was installed using instructions from our documentation (https://developers.keboola.com/extend/common-interface/logging/#python).

**Comment by ondrejhlavacek** [comment]
Maybe `host` was never in the pygelf payload:

![image](https://user-images.githubusercontent.com/497675/29643082-72c7d65c-8821-11e7-8cb5-d7c53a1538ab.png)

The Oct 8 commit (https://github.com/keeprocking/pygelf/commit/6bd275ae6b7b85950b44bc1f93be9e797fa30d2b) might have made it to https://pypi.python.org/pypi/pygelf/0.2.6.

**Comment by ondrejhlavacek** [comment]
Added a comment to https://github.com/keeprocking/pygelf/commit/348de66c1d06f40c5478af1635c1fd0e68edfa56.

**Comment by ondrejhlavacek** [comment]
Tried `logging_gelf`, that didn't work at all.

**Comment by ondrejhlavacek** [comment]
And couple more and here's the result https://github.com/keboola/docs-example-logging-python/pull/1

**Comment by ondrejhlavacek** [comment]
The only working library is `pygelf` in version 0.2.6, nothing else.

**Comment by odinuv** [comment]
nejdriv poresim tohle https://github.com/keboola/docs-example-logging-python/pull/1#issuecomment-325598581

**Comment by odinuv** [comment]
takze pygelf opravdu host neposila, ty ostatni loggery jo, je otazka jak resit teda ten ` Undefined index: host` - jsou tri moznosti:
- cely to skoncit fatalnim Apperorrem (aka oprav komponentu)
- zalogovat to jakoby se nechumelilo (v eventech bude JSON)
- vyhodit tu podminku pro kontrolu hosta

ja hlasuju pro 1)

**Comment by odinuv** [comment]
taky proto,ze je to celkem jasne proti specifikaci a nevim proc bysme to meli trpet http://docs.graylog.org/en/2.3/pages/gelf.html#gelf-payload-specification

**Comment by ondrejhlavacek** [comment]
Souhlas, je to nějaká haluz. Vycházel jsem z toho, že pygelf je v examplu v dokumentaci, jinak ten `host` param je tam spíš omylem a jen v jedný konkrétní verzi. Pokud můžem dát do dokumentace něco, co funguje v poslední verzi, bude to super :-)

**Comment by odinuv** [comment]
Ok, tak muzem odsud https://github.com/keboola/docs-example-logging-python/blob/master/main.py tne pygelf vyhodit dokud to nespravi, ty ostatni loggery podle me funguji (i kdyz s DB primo jsem to nezkousel), haluz spis je, ze jsem to delal zrovna na verzi ve ktere to nefungovalo :)

**Comment by ondrejhlavacek** [comment]
No hlavně z týhle, nebo to nějak aktualizovat: https://developers.keboola.com/extend/common-interface/logging/#python.

Potvrzuju, že teďka fungujou všechny tři korektní loggery, ale ten `invalid` se mi nějak nechce probojovat ven a vypsat se

![image](https://user-images.githubusercontent.com/497675/29990756-9735b73a-8f32-11e7-9407-34cbeb276302.png)

**Comment by odinuv** [comment]
jo jasne, ja jsem zapomnel tam pridat ten invalid handler! good catch, to jeste musim upravit

**Comment by odinuv** [comment]
fixed in b97344324752b300c8c6e4ae8bfb3148582d2db1

**Comment by odinuv** [comment]
docs fixed in https://github.com/keboola/developers-docs/commit/df42983e073b916d577cea854a2385c9aa9df55e

**Comment by ondrejhlavacek** [comment]
kua, furt ho tam nevidím! je pushnutá poslední verze mock serveru?

**Comment by odinuv** [comment]
pockej ty to nevidis na mock serveru nebo na docker runneru ?

**Comment by ondrejhlavacek** [comment]
na mock serveru

**Comment by ondrejhlavacek** [comment]
teď jsem to všechno zbuildil a pustil ručně, jestli to tam má bejt, tak to asi dělám blbě

```
docker build . -t quay.io/keboola/docs-example-logging-python
docker run --rm --env KBC_LOGGER_ADDR=log-server --env KBC_LOGGER_PORT=12202 --net bridge --link log-server quay.io/keboola/docs-example-logging-python:latest
```
```
docker build .
docker run --rm  --env SERVER_TYPE=tcp -P --net bridge --name log-server 86f44f06066f
```

**Comment by odinuv** [comment]
ok, tak tentokrat je to byl issue s mock-serverem 🙄  neopravil jsem to, protoze to za to nestoji, ale opravil jsem ten example https://github.com/keboola/docs-example-logging-python/commit/b0476b11eda314b770c798bfca71fcf95ef8d7e2 so it behaves

**Comment by ondrejhlavacek** [comment]
jo, šlape, díky!
