### ISSUE TITLE
Remove Phantom of the opera

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#190]
https://papertrailapp.com/groups/170211/events?q=%22Phantom%20of%20the%20opera%22 
Po upgradu dockeru to naštěstí už přestalo.
https://github.com/keboola/docker-bundle/blob/7c904a3d7c2f4c4f4fbad4ee1601fd101851aa31/Docker/Runner/DataDirectory.php#L92

**Comment by odinuv** [comment]
merged
