### ISSUE TITLE
Different response for PUT and GET

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#192]
Myslim, ze `GET` konfiguracie sa fixol, tak aby nevracalo `[]` (a tym padom v niektorych pripadoch nerozbijalo UI), co je parada.

Co som si ale vsimol, ze response PUT requestu to este vracia zle a mali by sme to fixnut aj tam.

```diff
--- 1.json      2017-09-25 21:39:09.545037600 +0200
+++ 2.json      2017-09-25 21:39:24.473042506 +0200
@@ -37,12 +37,12 @@
           "firstPage": 1
         }
       },
-      "config": []
+      "config": {}
     }
   },
   "rowsSortOrder": [],
   "rows": [],
-  "state": [],
+  "state": {},
   "currentVersion": {
     "created": "2017-09-25T21:30:52+0200",
     "creatorToken": {
```

1. je PUT na config, 2.ka nasledny GET.

**Comment by ondrejhlavacek** [comment]
@ujovlado co kdybychom `GET` úplně vyhodili a byl tam jen `PUT`?

**Comment by ondrejhlavacek** [comment]
A zkusil bych, aby se odpověď od Storage API v PUT requestu 1:1 použila jako odpověď Docker Runneru, bez parsování v PHP.

**Comment by ujovlado** [comment]
Akoze vyhodit GET z docker runneru a pouzival by sa GET zo sapi? Asi mozeme. Ale potom asi bude treba zabezpecit (myslim, ze na strane docker-runner) aby to do sapi poslalo dobre. Lebo ak tam budu namiesto prazdnych objektov polia, rozbije to opat par veci v UI. Netvrdim, ze UI si to nemoze osefovat, no prave sa mi paci ako to funguje teraz - spravne (posielam prazdu objekt, dostanem nazad objekt a nie pole). Co chcem fixnut aby ta response bola rovnaka (objekty).

**Comment by ondrejhlavacek** [comment]
Může za to tohle - https://github.com/keboola/storage-api-php-client/blob/75210f64c89625b007d27060f4a9dc380cc75ea9/src/Keboola/StorageApi/Client.php#L1895

S tím teď asi úplně snadno nehnu, je to tam ještě na dvou místech. Obcházet Storage API PHP klienta nechci. Workaround by měl být takovej, že se odpověď PUT requestu ignoruje a udělá se GET na Connection. A nebo nějakej fix v Storage API PHP klientovi. Co myslíš?

**Comment by ondrejhlavacek** [comment]
A nebo ideálně řešení viz https://github.com/keboola/docker-bundle/issues/182. Pro config rows bych to musel celé rozšiřovat, takže bych byl pro to smazat. API call na šifrování (`{component}/encrypt`) teď vrací data správně (https://github.com/keboola/docker-bundle/commit/277ebb196ac3d3e9692f8ec0f902af0604ec3dc5), takže bych to ideálně udělal jak je to popsaný v https://github.com/keboola/docker-bundle/issues/182.

**Comment by odinuv** [comment]
182 pls, upravou sapi klienta to rozmrdame nekde jinde :(

**Comment by ujovlado** [comment]
Related to: https://github.com/keboola/storage-api-php-client/issues/126
