### ISSUE TITLE
Input mapping with better resolution

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#200]
Nový atribut `changed_since`, kterej se převede přímo na API (`changedSince`). Kombinování `days` a `changed_since` nebude dovoleno.

**Comment by odinuv** [comment]
to changedSince neni vubec zdokumentovany - melo by to byt asi tady http://docs.keboola.apiary.io/#reference/tables/unload-data-asynchronously  ?

**Comment by ondrejhlavacek** [comment]
Je to o request výš - http://docs.keboola.apiary.io/#reference/tables/unload-data/export-table-into-csv

**Comment by odinuv** [comment]
omg, jdu to tam prepsat, vidim deprecated a automaticky preskakuju

**Comment by odinuv** [comment]
prdlacky, je to tam uplne spravne, akorat apiary je dementni a ja taky
