### ISSUE TITLE
Cannot run custom configuration for components with defaultBucket=true

### ISSUE THREAD

**Issue by ErikZigo** [keboola/docker-bundle#208]
All components with `defaultBucket` are failing on run configData with this error: 

`Configuration ID not set, but is required for default_bucket option.`

https://github.com/keboola/docker-bundle/blob/9294d534c3b565441b133ac72de016c5c99bf27f/Docker/Runner/DataLoader/DataLoader.php#L247

Maybe it is due some refactoring in https://github.com/keboola/docker-bundle/blob/master/Job/Executor.php

**Comment by ErikZigo** [comment]
How to reproduce

Create configuration of mongo db ex and then run only single query

https://connection.keboola.com/admin/projects/3117/extractors/keboola.ex-mongodb/319074384

**Comment by ondrejhlavacek** [comment]
Děje se to teď nově?

**Comment by ondrejhlavacek** [comment]
Nevíš, jestli se tomu předává v API callu config id? Jsme teď v autě. Jestli ne, tak se s tím nedá dělat vůbec nic a musí se počkat na config rows.

**Comment by ErikZigo** [comment]
Jo posila. Ale ne pod `configData`, ale vedle pod `config`.

Ty jsi tam zavadel `JobDefinitionParser` a ten s tim id configu nepracuje. V PT vidim errory 20. rijna prvni. Tak to by casove odpovidalo s touhle upravou.

**Comment by ondrejhlavacek** [comment]
Jasný, super, dík za debug, mrknu na to!

**Comment by ErikZigo** [comment]
`JobDefinitionParser::parseConfigData()`
