### ISSUE TITLE
Metadata upload errors as user exceptions

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#216]
https://connection.keboola.com/admin/utils/logs?file=2017/11/20/16/2017-11-20-16-43-28-5a12f820b1384-exception
https://connection.keboola.com/admin/utils/logs?file=2017/11/20/16/2017-11-20-16-43-28-5a12f820c85d9-log

**Comment by ondrejhlavacek** [comment]
Maybe it should be solved in https://github.com/keboola/db-extractor-pgsql/issues/19

**Comment by odinuv** [comment]
ja nevim, tohle je blby - to se muze stat v jakykoliv aplikaci a vubec nevim jak to vyresit :(

**Comment by ondrejhlavacek** [comment]
Instrukce pro developery (at si daj pozor na nazvy sloupcu) a pak to vracet jako user exception a nebo pro import v connection zavést nějakej flag `strictColumnNames` kterej je nebude "webalizovat" a to bude používat docker runner (asi to bude nastavení per komponenta).

**Comment by odinuv** [comment]
instrukce developerovi je naprd - pokud do komponent uzivatel vlozi takovou tabulku tak prece nemas sanci s tim neco udelat, vlastne ani s jistotou neumis sparovat sloupce importovane tabulky s tou novou

**Comment by ondrejhlavacek** [comment]
jak to myslíš?
> pokud do komponent uzivatel vlozi takovou tabulku

**Comment by odinuv** [comment]
no jakoze to bude extractor a vyextrahuje takovou tabulku

**Comment by ondrejhlavacek** [comment]
tak pokud k tomu budeš chtít dát sloupcový metadata, tak musíš znát strukturu, tj. měl bys bejt schopnej i ten sloupec přejmenovat podle toho, jak řeknem my (`webalize` se přesune do komponenty).

**Comment by odinuv** [comment]
no ano, pokud se webalize presune do komponenty - jinymi slovy storageapi prestane menit nazvy sloupcu a radsi je odmitne, tak pak je to v klidu
- maximalne me napada, ze by se to presunulo do storageclienta

**Comment by Halama** [comment]
Dnes opět v db ex, sloupce pojmenované s mezerama `The column \"in.c-keboola-ex-db-mysql-347166372.tab03.My%20Comment%20Is%20About%\" was not found.`

**Comment by Halama** [comment]
jaký je teda finální řešení. V SAPI parametr který vypne to přejmenování https://github.com/keboola/connection/issues/1086 ? A přejmenování se bud bude resit v komponente nebo se nebude resit a bude to koncit user errorem?

**Comment by ondrejhlavacek** [comment]
Jo, to mi přijde asi nejrozumnější. Navíc se dá postavit procesor, kterej zwebalizuje jak názvy sloupců, tak metadata pro sloupce. V manifestu to bude úplná hračka. 

Ale nejsem si jistej, jestli náhodou nezpůsobíme nějakej BC - některý existující konfigurace by na webalizaci sloupců mohly spolíhat :-(.

**Comment by Halama** [comment]
na to spoléhá imho hodně konfigurací.

**Comment by Halama** [comment]
mohlo by to být jako flag komponenty?

**Comment by ondrejhlavacek** [comment]
to mohlo. co to nejdřív začít logovat a zjistit, kde všude by to byl problém?

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/docker-bundle/commit/37c0a09e42398fac5d35115150599adda5c896eb
