### ISSUE TITLE
Large sliced file output mappings consume memory

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#217]
https://github.com/keboola/aws-s3-extractor/issues/9

**Comment by ondrejhlavacek** [comment]
https://papertrailapp.com/systems/kbc-us-east-1-syrup-docker-i-077c1665a428bca83/events?q=331748603&focus=869749498832883781

**Comment by ondrejhlavacek** [comment]
Mám tušení, že by za to mohly moct retrye v S3 clientovi. Bylo tak 1900 asi docela velkejch souborů. Zkusím nasimulovat.

**Comment by ondrejhlavacek** [comment]
A ještě se u toho objevilo tohle z `processor-move-files`

```
message: find: ./***/001181: No such file or directory
find: ./***/001182: No such file or directory
find: ./***/001183: No such file or directory
find: ./***/001184: No such file or directory
find: ./***/001185: No such file or directory
find: ./***/001186: No suc
```

to se mi vůbec nedaří nasimulovat

**Comment by ondrejhlavacek** [comment]
Retrye to zřejmě nejsou, nepodařilo se mi žádný vyvolat, ale paměť roste s počtem slajsů a velikostí souborů.

**Comment by ondrejhlavacek** [comment]
Interní S3 multipart upload tomu asi taky zakotlí (co do paměti).

**Comment by ondrejhlavacek** [comment]
Ale podle chybovýho stack trace https://connection.keboola.com/admin/utils/logs?file=2017/11/21/23/2017-11-21-23-01-02-5a14a21e05e5a-exception to k uploadu do S3 ani nedošlo. Další suspect - komprese.

**Comment by odinuv** [comment]
nesouvisi to s timhle https://github.com/keboola/connection/issues/867 ?

**Comment by ondrejhlavacek** [comment]
Nemělo by, tohle není table export. Musím se dostat přímo k tý konfiguraci
nebo něčemu, co failuje stejně...

**Comment by ondrejhlavacek** [comment]
Tak to je zajímavý, testovací job proběhl, ale produkční job nechce.

https://connection.keboola.com/admin/projects/232/extractors/keboola.ex-aws-s3/332424297

Testovací job má 2000x zduplikovanej 1 náhodnej soubor z produkčního jobu, běží na stejný infrastruktuře. Jediný, co se nějak zásadně liší, je S3 storage backend, kde produkční projekt má vlastní S3. Jdu si říct o tokeny :-/

**Comment by Halama** [comment]
Problém je v OM do S3 jo?

**Comment by ondrejhlavacek** [comment]
Asi! Poslední hláška, co v eventech vidím je `Uploaded file ***.csv`, což je podle mě API call Create File Resource. Pak se nic neděje, takže tam probíhá upload do S3 než začne import. V testovacím configu ten upload zabere cca minutu a pak to zahlásí, že je to >1000 slajsů, v projektu to jelo 40+ minut než jsem to stopnul.

**Comment by Halama** [comment]
To je teda dost zajimavý, protože jiný věci v tom projektu evidentě jedou v pohodě ne?

**Comment by ondrejhlavacek** [comment]
Jo no. A nebo je něco v datech, ale mám jen jeden vzorovej soubor.

**Comment by ondrejhlavacek** [comment]
Ostrý data v mým projektu prošly - https://connection.keboola.com/admin/projects/232/jobs/333789471

**Comment by ondrejhlavacek** [comment]
Ah, beru zpět, unáhlil jsem se, zatím jen byla vytvořená tabulka.

**Comment by ondrejhlavacek** [comment]
Je to chyba uploadu do S3, cyklí se to na jednom souboru. Jdu zjišťovat dál.

![image](https://user-images.githubusercontent.com/497675/33378873-96281fac-d516-11e7-8af9-680f5b5a1d3f.png)

**Comment by ondrejhlavacek** [comment]
Takhle vypadaj stažený soubory z S3

![image](https://user-images.githubusercontent.com/497675/33378931-c1a906be-d516-11e7-8fa4-9cd38c1e706e.png)

Jdu ověřit, jaká je jejich skutečná velikost v S3.

**Comment by ondrejhlavacek** [comment]
Soubory jsou skutečně o nulový velikosti

![image](https://user-images.githubusercontent.com/497675/33379139-8737726c-d517-11e7-8e3f-90a1371f6dc4.png)
