### ISSUE TITLE
Invalid manifest format - Application error

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#218]
Throws an Application exception. My Python code that broke it

```
with open('/data/out/tables/output.csv.manifest', mode='wt', encoding='utf-8') as out_file:
    out_file.write('destination: out.c-sliced.test\n')
    out_file.write('columns: [\'col1\']\n')    
    out_file.close()
```

Should be an user exception

**Comment by odinuv** [comment]
why? it really is an error of the application

**Comment by ondrejhlavacek** [comment]
Right, correct! I have created the manifest in my Python transformation,
which confused me.

On Nov 22, 2017 8:58 PM, "Ondrej Popelka" <notifications@github.com> wrote:

why? it really is an error of the application

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keboola/docker-bundle/issues/218#issuecomment-346458200>,
or mute the thread

**Comment by odinuv** [comment]
shouldn't we switch R/Python transformations into `no_applications_error` mode then?

**Comment by ondrejhlavacek** [comment]
That may be a good idea!

**Comment by odinuv** [comment]
Tak ne, tohle nepomuze, protoze ta chyba se tyka az zpracovani manifestu a samotna aplikace skonci bez chyby (cili no_applications_error) se nema kde uplatnit. Jediny reseni by bylo pridat na konec transformaci validaci manifestu, coz se me ani trosku nechce, protoze:
- mi to prijde zbytecny
- bude se tim dupllikovat kod z docker runner
- je to vsechno dohromady bad practicte, protoze mas pouzit funkci `writeFileManifest` a tim se celymu tomuhle problemu vyhneme

**Comment by ondrejhlavacek** [comment]
Souhlas se vším, jen u Python transformace to prostě snadno nezdebuguju :-( U komponent je to jasný, nevalidní manifest je aplikační chyba, ale u transformace je ta "aplikace" tvoje. Šlo by to udělat třeba přes nějakej flag komponenty, aby to blilo tyhle chyby jako user errory?

**Comment by odinuv** [comment]
tak slo by vsechno, ale prijde me to hodne divny, radsi bych to udelal v te transformaci, kdyz je a bude to jedina komponenta, ktere se to tyka

**Comment by ondrejhlavacek** [comment]
Ok! To by mohlo bejt.

**Comment by ondrejhlavacek** [comment]
Takže bych to nechal na nový transformace, co budou čistě přes Docker Runner.
