### ISSUE TITLE
OAuth Integration - Refresh token update

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#221]
Některé komponenty nemají refresh_tokeny s neomezenou platností. Je potřeba jej pravidelně po použití updatovat. Např. https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app#/Refreshing_the_access_token

Nový refresh token nemumíme zatím poslat zpět do OAuth komponenty.

## Jak by to mohlo fungovat
 - Komponenta po doběhnutí uloží Oauth response do `/data/out/authorization.json`
 - Docker runner vezme výstupní authorization soubor a jeho obsah pošle na nový resource `PATCH /oauth-v2/credentials/{componentId}/{id_credentials}` s telěm:
   - updatne pouze `#data` atribut credentials. Bude posílat v plain textu, zašifruje si to až oauth komponenta v moment příjmu
   - `id_credentials` - vezme se z konfigurace `authorization.oauth_api.id` https://developers.keboola.com/extend/common-interface/oauth/#initialize
```
{
  "data": {authorization_content}
}
```
 - Docker runner update provede vždy pokud bude `/data/out/authorization.json` nebo by se to mělo řídit nějakým flagem.

**Comment by Halama** [comment]
https://keboola.zendesk.com/agent/tickets/7578

**Comment by ondrejhlavacek** [comment]
Co když konfigurace komponenty během té doby neproběhne a tak expiruje sama? Nemohlo by to OAuth API dělat samo (přes sync akci komponenty, nebo úplně jinak...).

**Comment by Halama** [comment]
jo když neproběhne tak expiruje.

**Comment by Halama** [comment]
aby si to řešilo samo by asi šlo ale přijde mi to takový krkolomný.

**Comment by ondrejhlavacek** [comment]
Jak to bude řešený při async běhu komponenty? Vidím tam jeden zádrhel - je tam v odpovědi atribut `x_refresh_token_expires_in`, ale nemáme nikde referenci na čas, kdy ten refresh nebo úvodní autorizace proběhla, takže nedokážem určit, kdy to vyexpiruje. To by se asi dalo do OAuthu dodělat, ať to udržuje a vrací.

https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app#/Exchange_code_for_refresh_and_access_tokens

**Comment by ondrejhlavacek** [comment]
Přijde mi jen divný, že by async job komponenty řešil aktualizaci přihlášení. Autorizace se používá i pro sync akce. Představ si, že máš třeba nějakej DB extraktor, ke kterýmu se autorizuješ OAuthem a refresh_token se refreshuje při async jobu. Takže pokud nespustíš job, tak si třeba ani nevylistuješ tabulky nebo databáze.

**Comment by MiroCillik** [comment]
Znovu tuto temu otvoril Robin, ktory ma pri OneDrive API refresh token s platnostou len 14dni.

Pri tych sync akciach by som to riesil podobne ako pri obycajnom spusteni, bud by to ten novy refresh token vypisalo na vystup do json struktury ala:
```
"response": {
    // tohle se vrati jako response
},
"refresh_token": "sa ulozi do Oauth db"
```

Alebo sa to zapise do nejakeho output suboru, z ktoreho si to docker-runner vezme a ulozi do OAuth DB.

Tym ulozenim do OAuth DB mam na mysli, ze to zavola OAuth API call "PATCH credentials".

**Comment by ondrejhlavacek** [comment]
Doplním workaround - zašifrovat a uložit do state.

**Comment by odinuv** [comment]
No ja jak to vidim, tak me to prijde cely hrozne divny, zaprve to spoliha na to, ze se ty joby budou spoustet pravidelne, za druhe - ty sync akce? co kdyz se spusti sync akce a v prubehu async akce, ktera ji zrovna refreshne token? Podle me by se o to melo fakt starat OauthAPI - ze by se tam reklo, ze se ma neco volat a refreshovat a tam si to vyridit. To proste neni starost docker runneru premejslet nad tim, jestli ma upravovat credentials nebo ne, ten ma IDcko, na to se zepta a vysledek injecne do konfigurace a nazdar

**Comment by MiroCillik** [comment]
Dalo by sa to teda riesit tak, ze vzdy, ked si docker-runner vypyta credentials od OAuth bundlu, ten ich refreshne. 
Moze na to byt nejaky flag, ktorym pri registracii komponenty v oauth bundle oznacis, ci sa ma refreshovat aj refresh token. Aby pri komponentach, ktore to nepotrebuju nevznikal zbytocny overhead.

**Comment by odinuv** [comment]
No taky by tam mel bejt nejak zaznmenana ta expirace - docker runner se muze ptat klidne kazdejch 10 minut a kdyz to expiruje za tyden...tak je to furt slusnej overhead i pro komponentu, ktera to potrebuje

**Comment by MiroCillik** [comment]
To je prave problem, lebo refresh token casto nema v opdovedi expiraciu. Expirace byva len pri access tokene. Napr. u toho One Drive je to tak. Dalo by sa to spravit tak, ze by si tu expiraciu nastavil pri registacii komponenty spolocne s tym "refresh" flagom.

**Comment by odinuv** [comment]
Vsak to jsem myslel - ta expirace by byla vlastnost te komponenty stejne jako ten flag

**Comment by MiroCillik** [comment]
Ok, to by slo, pripravim to pak do noveho oauth-api

**Comment by odinuv** [comment]
Moving to https://github.com/keboola/docker-bundle/issues/221
