### ISSUE TITLE
Allow KBC_URL env var without forwardToken setting

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#231]
I think we can enable `KBC_URL` for all components, not only for those with `forwardToken` setting.

https://github.com/keboola/docker-bundle/blob/dba784ecb9a0756eb153e4c406b1939e07891709/Docker/Runner/Environment.php#L71-L74

**Comment by Halama** [comment]
ještě přemýšlím jestli tam rovnou nepřidat proměnnou `KBC_HOST` aby to uživatelé snadněji mohli použít jako identifikátor např. při ukládání do S3. 
V `KBC_URL` je např. `https://connection.keboola.com` v `KBC_HOST` by bylo pouze `connection.keboola.com`

**Comment by odinuv** [comment]
hmm, a nebylo by teda nakonec lepsi dat tam `stack_id` kdyz je to jen pro identifikaci?

**Comment by Halama** [comment]
jo to by bylo asi nejslepsi dat tam pro vsechny `KBC_STACK_ID` ve kterem bude ten host např. `connection.keboola.com`.

**Comment by odinuv** [comment]
no ve stack_id je ted aws region https://github.com/keboola/docker-bundle/blob/master/docker-tests/parameters.yml#L6

**Comment by Halama** [comment]
aws region urcite neni stack id. Stack ID je host sapi takze `connection.keboola.com`

**Comment by odinuv** [comment]
no tak to a) musime v tom parameteres.yml zmenit b) da se to odnekud vzit, nebo to tam proste napsat?

**Comment by Halama** [comment]
sapi url z ktré uděláš to `KBC_STACK_ID` v parametrech určitě máš.

**Comment by Halama** [comment]
nic víc bych tam nepřidával
