### ISSUE TITLE
OAuth Bundle version in component configuration

### ISSUE THREAD

**Issue by MiroCillik** [keboola/docker-bundle#232]
In order to launch new `OAuth API` https://github.com/keboola/oauth-api/issues/1, which will gradually replace current `OAuth Bundle v2`, we need to specify which one of these were used to authorize component configuration.

The version of the OAuth API used would be stored in component configuration `authorization` section.
From there, docker runner would know whether to use the old endpoint `https://syrup.keboola.com/oauth-v2/` or the new one, which could be `https://syrup.keboola.com/oauth-v3/`.

Example config:
```
"authorization": {
    "oauth_api": {
        "version": "3",
        "id": "12345"
    }
}
```

**Comment by pivnicek** [comment]
Maybe we should be careful with naming convention here.  I got immediately confused between keboola syrup oauth api v2 and OAuth v2.
maybe 
```
"authorization": {
    "keboola_oauth_api": {
        "version": "3",
        "id": "12345"
    }
}
```
?

**Comment by MiroCillik** [comment]
Yeah, but the `oauth_api` key already exists in our configurations so I'm not sure if changing that would be backward compatible.

**Comment by odinuv** [comment]
that might be solvable, but i'm not really sure what the correct name would be

**Comment by ondrejhlavacek** [comment]
what if the oauth api version is feature of the project, not the configuration?

**Comment by MiroCillik** [comment]
@ondrejhlavacek you can have "old" existing configurations with version 2 and new configurations with version 3 in the same project.

The point is to avoid migrating and duplicating records in the oauth DBs.

There would be a project feature which, when enabled, would use the new v3 oauth api for authorization.

**Comment by odinuv** [comment]
a budem to teda nejak prejmenovavat? ja stim soucasny pojmenovanim taky nejsem spokojenej ale popravde me zadny lepsi nenapada

**Comment by Halama** [comment]
ja bych to nechal jak to je

**Comment by odinuv** [comment]
je/bude pro ten oauthv3 nejakej PHP client, nebo pojedem pres guzzle?

**Comment by ondrejhlavacek** [comment]
určitě by měl bejt klient

**Comment by MiroCillik** [comment]
A existuje nejaky pre oauthv2? To API je totiz stejny

On 21 Jan 2018 13:51, "Ondřej Hlaváček" <notifications@github.com> wrote:

určitě by měl bejt klient

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keboola/docker-bundle/issues/232#issuecomment-359246109>,
or mute the thread

**Comment by odinuv** [comment]
existuje https://github.com/keboola/oauth-v2-php-client, takze jen jine base url ?

**Comment by MiroCillik** [comment]
Ano, malo by to tak byt

**Comment by Halama** [comment]
ono to prave nejspis bude mit uplne jiny URL

**Comment by odinuv** [comment]
no vsak to novy URL ze by bylo v services, to stary nechame dozit v parameters

**Comment by Halama** [comment]
aha zmatlo me to ` priplacl verzi`

**Comment by Halama** [comment]
v services to smysl dava pridam to tam potom jako `oauth`

**Comment by odinuv** [comment]
jj, s tou verzi to byl zkratik. Ouk, pripravim aby se to cetlo z tama
