### ISSUE TITLE
Container name in use

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#238]
```
docker: 
Error response from daemon: 
Conflict. The container name "350997366-350992293.350997368--0-gd-user-mgmt" is already in use by container a50684653cc5396b4f2cb1e20d92385f6d7bea52cf0ebe020f74a6729416a262. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'."
```

https://connection.keboola.com/admin/utils/logs?file=2018/01/30/02/2018-01-30-02-12-30-5a6fc67e4e4f4-exception

https://connection.keboola.com/admin/utils/logs?file=2018/01/30/02/2018-01-30-02-12-30-5a6fc67e5f59d-log

**Comment by odinuv** [comment]
a vis proc to udelalo? me nic zatim nenapadlo

**Comment by ondrejhlavacek** [comment]
Čumím do logu zatím, fakt se to pustilo dvakrát.

**Comment by odinuv** [comment]
Jakoby nefungoval zamek?

**Comment by ondrejhlavacek** [comment]
První run začal v `Jan 30 01:12:19` a komponenta skončila po hodině běhu (bez 2 vteřin) a pak to v `Jan 30 02:12:28` zahlásilo

```
Cannot remove container bizztreat/docker-gd-user-management:latest 350997366-350992293.350997368--0-gd-user-mgmt: The command "sudo docker rm -f '350997366-350992293.350997368--0-gd-user-mgmt'" failed.
Exit Code: 1(General error)
Working directory: 
Output:
================
Error Output:
================
Error response from daemon: No such container: 350997366-350992293.350997368--0-gd-user-mgmt
```

Druhej run začal v `Jan 30 02:12:19`, ale pod jiným PID, takže to musel bejt jinej proces fronty.

Run 1: https://papertrailapp.com/groups/23635/events?q=350997366%20AND%203723&focus=894787345084203061
Run 2: https://papertrailapp.com/groups/23635/events?q=350997366%20AND%2052951&focus=894802402602008582

**Comment by ondrejhlavacek** [comment]
```
Jan 30 01:12:19 kbc-us-east-1-syrup-docker-i-0007cafe928b1bcef queue:  {
message: Processing message started
context: {
jobId: 350997366
messageId: 3dfb851f-97fc-4eef-93bb-918d1060b9e3
command: php '/www/syrup-router/components/docker/releases/20180129104245/vendor/keboola/syrup/app/console' 'syrup:run-job' '350997366' --env=prod
}
level: 200
channel: app
extra: {
}
cliCommand: /www/syrup-router/components/queue/current/vendor/keboola/syrup/app/console syrup:queue:receive docker 31
component: queue
runId: null
pid: 123124
priority: INFO
}
```
=> pid `3723`

```
Jan 30 02:12:19 kbc-us-east-1-syrup-docker-i-0007cafe928b1bcef queue: {
message: Processing message started
context: {
jobId: 350997366
messageId: 3dfb851f-97fc-4eef-93bb-918d1060b9e3
command: php '/www/syrup-router/components/docker/releases/20180129104245/vendor/keboola/syrup/app/console' 'syrup:run-job' '350997366' --env=prod
}
level: 200
channel: app
extra: {
}
cliCommand: /www/syrup-router/components/queue/current/vendor/keboola/syrup/app/console syrup:queue:receive docker 37
component: queue
runId: null
pid: 43245
priority: INFO
}
```
=> pid `52951`

Takže ta terminace prvního jobu byla způsobená tím, že se zkusil pustit kontejner druhýho jobu a to neprošlo a cleanup zavolal `/usr/bin/docker rm -f 350997366-350992293.350997368--0-gd-user-mgmt` a tím sundal i první kontejner.

**Comment by ondrejhlavacek** [comment]
Takže to fakt vypadá, že nezafungovala fronta!

**Comment by ondrejhlavacek** [comment]
Filtr na message id 
https://papertrailapp.com/groups/23635/events?q=3dfb851f-97fc-4eef-93bb-918d1060b9e3

**Comment by odinuv** [comment]
Tak me to prijde vsechno celkem v poradku, az na to ze se to pustilo 2x :)

**Comment by ondrejhlavacek** [comment]
Zatím odkládáme, novej Docker Runner / fronta to vyřeší.

**Comment by ondrejhlavacek** [comment]
Pro evidenci bych to nechal otevřený, ok?

**Comment by odinuv** [comment]
Pro evidenci bych to zavrel, kdyz to nehodlame resit :) vyhledavat se da i v zavrenejch issues

**Comment by Halama** [comment]
jj taky jsem pro zavreni, kdyz zakladam nove hledam i v closed

**Comment by ondrejhlavacek** [comment]
Jasně, sorry!

**Comment by Halama** [comment]
Ted se stalo to same v EU ` Application error: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-mysql:2.2.11 container '514671-514672--0-keboola-ex-db-mysql' failed: (125) docker: Error response from daemon: Conflict. The container name "/514671-514672--`
V ten okamzik probehl `Multi-AZ instance failover` toho RDS ktere drzi zamky, takze to bylo tim.

**Comment by ondrejhlavacek** [comment]
To mě nenapadlo se podívat na locks db, sakra.
