### ISSUE TITLE
Error message truncated

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#239]
Není vůbec vidět v eventech celá, musím jít přes PT, abych viděl celej text chyby. Uživatel nevidí nic a nemůže s tím nic dělat.

https://connection.keboola.com/admin/projects/258/jobs/351198110

![image](https://user-images.githubusercontent.com/497675/35572141-4a900994-05d4-11e8-9add-9df2c705b89e.png)

![image](https://user-images.githubusercontent.com/497675/35572147-4ebdbaca-05d4-11e8-97d0-ee8ee46e244e.png)

![image](https://user-images.githubusercontent.com/497675/35572158-558c20da-05d4-11e8-9b5d-eef3347faea5.png)

**Comment by odinuv** [comment]
melo by to byt v detailu eventu, ale muzem tady https://github.com/keboola/docker-bundle/blob/master/Docker/Container.php#L310 zvednout ten limit

**Comment by ondrejhlavacek** [comment]
Právě že není. Jsem nějak zvyklej, že když to není v resultu jobu (kde to je imho správně trimovaný), tak to najdu v posledním eventu, ale tam je to oříznutý taky.

**Comment by odinuv** [comment]
ha, jo uz vim!

**Comment by odinuv** [comment]
@ondrejhlavacek melo by to byt fixnuty

**Comment by ondrejhlavacek** [comment]
Jo, je to tam!
![image](https://user-images.githubusercontent.com/497675/35670989-568489de-073a-11e8-96c5-eb00601a3bdb.png)
Díky
