### ISSUE TITLE
Chown timeout

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#241]
Dneska v noci zase vytimeoutovalo několik `/usr/bin/docker run --rm --volume=/tmp/docker/run-5a714b78d99661.63602931/data:/data alpine sh -c chown 501 /data -R && chmod -R u+wrX /data` commandů. 

Nic jinýho netimeoutovalo (inspect, rm, ...), na EBSku byl v tu dobu delší IO peak, stalo se to až na jeho úplným konci. Command se 3x zopakoval a pak umřel.

![image](https://user-images.githubusercontent.com/497675/35615028-43a779c6-0671-11e8-8dcd-75c7b66f12ce.png)

Koukal jsem do starších issues, pouštet kontejner pod jiným userem zřejmě nepůjde (https://github.com/keboola/docker-bundle/issues/198#issuecomment-335432737), ale možná by to šlo ještě přes `--group-add` (https://docs.docker.com/engine/reference/run/#additional-groups).

Pokud by ani tohle nevyšlo, dal bych víc retries a mezi nima nějakou relativně velkou pauzu (pár minut), nebo můžem zkusit nechat tomu commandu víc času. Podle času těch retries mi přijde, že Symfony/Process stejně chytne timeout až po ukončení procesu a že to trvalo pod dvě minuty. 

![image](https://user-images.githubusercontent.com/497675/35615201-baae1ad4-0671-11e8-9cae-0dfbce74ab9c.png)

Related: https://github.com/keboola/syrup-router/issues/64, https://github.com/keboola/docker-bundle/issues/198

**Comment by Halama** [comment]
poustel bych to pod jednim userem bez sudo a mohlo by se to vyresit

**Comment by ondrejhlavacek** [comment]
to jsem právě myslím zkoušel v https://github.com/keboola/docker-bundle/issues/198#issuecomment-335432737

**Comment by ondrejhlavacek** [comment]
vyřeší se v #198
