### ISSUE TITLE
sync action result [] treated as invalid json

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#244]
```
"message": "Decoding JSON response from component failed",
"context": {
"exception": {},
"exceptionId": "docker-501970e64da2b8da875451eaf3b5a55a",
"data": {
"message": "[]"
}
},
"level": 400,
"level_name": "ERROR",
"channel": "app",
```

deje sa to napr u ex instagram kde sa na vyber ig accountov pouziva sync akce a ak user nema ziadny account tak result je prazdne pole `[ ]` co je validny json. 
Podobny problem by mal byt aj u ex fb a ex fb ads.
Som si takmer 100% isty ze predtym to fungovalo aj pri tom prazdnom poli, inac by sa nato prislo pri vyvoji ui. Navyse ked to vrati neprazdne pole tak to nespadne tj berie ako validny json napr:

```
[{"name":"Noonania","category":"Community","id":"17841401382855558","fb_page_id":"1960059394258217"}]
```

**Comment by odinuv** [comment]
Vidim cim to je - je tam blbe kontrola, ale je to tak 2 roky, takze pochybuju, ze to predtim fungovalo

**Comment by kacurez** [comment]
hmm mi pride divne ze sa nikto nestazoval, asi vacsina mala vzdy nejaky account. Ja som nato mohol narazit pri ex fb ads, tam som nemal ziadny account nejaku dobu, tak neviem, mozno to extraktor na zaciatku vracal v objekte..

**Comment by odinuv** [comment]
jo, s prazdnym objektem to fungovalo, ted uz to funguje i s prazdnym polem

fixed in 58639bf8b7238e60fb0367171e5667085730907a
