### ISSUE TITLE
oauth structure in config.json

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#245]
https://github.com/keboola/google-bigquery-extractor/issues/27

imho by to měl řešit docker runner a na výstupu vyhodit vše kromě `oauth_api.credentials`

**Comment by ondrejhlavacek** [comment]
@Halama nemáš náhodou po ruce link na nějakej takovejhle job? vůbec se mi nedaří to nasimulovat

**Comment by Halama** [comment]
mám, ta komponenta už je ale fixnutá

**Comment by Halama** [comment]
https://connection.keboola.com/admin/projects/3117/jobs/355267583?q=

**Comment by ondrejhlavacek** [comment]
jj vím, že je to fixnutý, ale zkusil jsem udělat failující test a nepodařilo se, tak musím hledat ještě jinde
https://github.com/keboola/docker-bundle/pull/246/files#diff-013b4b115746a6a14931eba57106299f

**Comment by Halama** [comment]
v tomhle commitu to naopak v tech testech davas pryc ne?

**Comment by ondrejhlavacek** [comment]
nene, naopak kontroluju celý pole, ne jen jeden uzel někde uvnitř

https://github.com/keboola/docker-bundle/blob/ee4cb062627e1ed24cdbe6e445e02f0ca90c0d35/Tests/Runner/AuthorizationTest.php#L51-L54

=>

https://github.com/keboola/docker-bundle/blob/b4d684a96f1c10ee387e1f82d4ce80f2712ba919/Tests/Runner/AuthorizationTest.php#L51-L54

**Comment by ondrejhlavacek** [comment]
Vytvořil a autorizoval jsem konfiguraci v UI a dumpnul si config.json, co to mělo vytořit pro komponentu

```json
{
    "authorization": {
        "oauth_api": {
            "credentials": {
...
            }
        }
    },
    "parameters": {
...
    },
    "processors": [],
    "image_parameters": [],
    "action": "run"
}
```

**Comment by ondrejhlavacek** [comment]
Job puštěnej pod starším tagem komponenty vyfailoval - https://connection.keboola.com/admin/projects/232/jobs/355314158?q=

**Comment by ondrejhlavacek** [comment]
Podle toho, co jsem si s extraktorem hrál, tak tam fakt muselo bejt 

```
{
    "authorization": {
        "id": 123456,
        "version": 3,
        "oauth_api": {
            "credentials": {
...
            }
        }
    },
    "parameters": {
...
    },
    "processors": [],
    "image_parameters": [],
    "action": "run"
}
```

**Comment by ondrejhlavacek** [comment]
closed via #246
