### ISSUE TITLE
Decrypt is executed on whole configuration response

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#248]
It should be executed only on `configuration` property content, otherwise for example `#` prefixed value in state breaks decryption.

 

> ObjectEncryptor->decrypt(array('id'=> '355250854', 'name' => 'Debug', 'description' => '', 'created' => '2018-02-12T09:13:27+0100', 'creatorToken' => array('id' => '82343', 'description' => 'martin.halamicek@keboola.com'), 'version' => '7', 'changeDescription' => 'Update parameters', 'isDeleted' => false, 'configuration' => array('parameters' => array('networkAnalyticsStandardPars' => null, 'networkAnalyticsPars' => null, 'reportDaysBack' => '0', 'clickTrackersPars' => null, 'userName' => 'debug', 'since' => '', 'endpointUrl' => 'https://api.appnexus.com', 'incremental' => '1', 'datasets' => array('Advertiser', 'Brand', 'Campaign'), '#password' => '')), 'rowsSortOrder' => array(), 'rows' => array(), 'state' => array(), 'currentVersion' => array('created' => '2018-02-14T14:31:35+0100', 'creatorToken' => array('id' => '82343', 'description' => 'martin.halamicek@keboola.com'), 'changeDescription' => 'Update parameters'))) in Executor.php line 161

https://keboola.slack.com/archives/C03JBGZDG/p1518615382000294

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C03JBGZDG/p1518615382000294
