### ISSUE TITLE
parse JSON events in streaming logs

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#25]
autodetekovat json v streamu logů, a pokud sturktura odpovídá tomu, co má v eventu být, použít objekt, jinak to poslat plaintextem

**Comment by kachnitel** [comment]
Porad se mi vic libi udelat flag, co rekne jestli log ma byt nejak strukturovany (JSON) nebo ne, a detekovat to jen pokud ano, resp. s tim pocitat, a kdyz nebude, vyhodit to jako err do PT. To se nehodi protoze R skripty nekdy vypisou neco nekontrolovatelnyho? 

Kdyz bysme ocekavali JSON, mohl by existovat nejaky vymysleny separator, co by nas mohl oprostit o regex pro rozdeleni dvojitych zaznamu.

**Comment by Halama** [comment]
rozdeleni novych zaznamu je novy radek. ten json to blije na stdount v neformatovany forme

**Comment by ondrejhlavacek** [comment]
Přesunuto do productboardu
https://keboola.productboard.com/feature-board/planning/features/38178
