### ISSUE TITLE
Encrypt by default

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#252]
Encryption could be supported by default for all components. Then we can remove `encrypt` flag support from docker runner and also from dev portal/UI.

**Comment by odinuv** [comment]
jo, nedavno jsem nad tim taky premyslel, proc to vlastne mame vypinatelny - jediny co me napadlo je, kvuli debug api callum - input data

**Comment by Halama** [comment]
Input data předopkládám ted nerozšifrovává nikdy?

**Comment by odinuv** [comment]
no on je udelanej tak, ze je zakazany, kdyz ma komponenta povoleny sifrovani - kdyby fungoval a jen to nerzsifrovaval tak by to bude asi podstatne chytrejsi, to by me zajimalo proc to tak neni :)
