### ISSUE TITLE
table manifests vs load instructions

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#257]
https://github.com/keboola/php-component/issues/21#issuecomment-374573666
https://github.com/keboola/php-component/issues/21#issuecomment-374590056

nápad:

v out manifestu jsou teď 2 věci spojený dohromady

- metadata tabulky/csv (sloupce, parametry csv, pk, ...)
- instrukce pro load do storage (incremental, delete_where_...)

kdybychom to od sebe dokázali odtrhnout, bude manifest univerzální na všechny strany a instrukce pro load se budou přenášet nezávisle

totéž by mohlo platit u souborů (tam jsou ty manifesty od sebe asi nejvíc rozdílný)

**Comment by tomasfejfar** [comment]
Není to zmatečné a složité? Bude potřeba další názvosloví, bude potřeba další soubor. Je otázka, jestli typicky potřebuješ oba dva nebo jen "storage manifest". 

Možná to málo chápu, ale ten problém nestejnosti manifestů není IMO dostatečný use-case na to, aby se oddělovali.

**Comment by ondrejhlavacek** [comment]
Nestejnost samotná nevadí, ale separation of concerns vadí.

**Comment by odinuv** [comment]
- input table manifest
  - id
  - name
  - uri
  - primary_key
  - created
  - last_import_date
  - last_change_date
  - (indexed_columns, rows_count, data_size_bytes, is_alias, attributes) (jsou deprecovany)
  - columns
  - s3
  - metadata
  - column_metadata

- output table manifest
  - destination
  - incremental
  - primary_key
  - columns
  - delete_where_column, delete_where_values, delete_where_operator
  - delimiter
  - enclosure
  - metadata
  - column_metadata

- input file manifest 
  - id
  - name
  - created
  - is_public
  - is_encrypted
  - is_sliced
  - tags
  - max_age_days
  - size_bytes

- output file manifest
  - tags
  - is_public
  - is_permanent
  - is_encrypted
  - notify

**Comment by odinuv** [comment]
coz me vede k nazoru, ze ani pri oddeleni metadat a load instrukci nedostaneme stejny in/out manifesty takze bych rekl, ze tu mame dva nesouvisejici problemy:
- separation of concerns
- nestejnos in/out manifestu

(ktere se projevuji oba tim, ze in/out manifesty jsou nestejne)

**Comment by ondrejhlavacek** [comment]
A co takhle

Table Manifest 

- primary_key
- columns
- delimiter
- enclosure
- metadata
- column_metadata

Output Instructions

- destination
- incremental
- delete_where_*

Input Instructions(?)

- id
- name
- uri
- created
- last_import_date
- last_change_date
- s3

Kromě S3 z toho všechno můžeme imho vyhodit

**Comment by tomasfejfar** [comment]
A nejdou ještě některé z těch "input" věcí přidat do manifestu? Nebo ty souvisí jen s tím vygenerovaným CSV souborem v "in" a ne s tou samotnou tabulkou ve storage?

**Comment by odinuv** [comment]
a ty Input Instructions(?) jsou co?

**Comment by ondrejhlavacek** [comment]
No to nevím, proto tam je ten otazník. Pokud tam bude jenom `s3` pro staging via S3, tak to jsou cca Input Instructions.

**Comment by ondrejhlavacek** [comment]
@tomasfejfar souvisí s tabulkou ve Storage, ale jsou read-only - zpátky do Storage se nic z toho nezapisuje.

**Comment by odinuv** [comment]
moved to https://github.com/keboola/internal/issues/2
