### ISSUE TITLE
Run container without internet access

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#26]
docker run --net="none"

https://keboola.slack.com/archives/luckyguess/p1449388545000002

**Comment by odinuv** [comment]
Net none nezabranuje containeru v pristupu ven, porad je mozny si pristup nakonfigurovat https://docs.docker.com/v1.8/articles/networking/#container-networking

**Comment by ondrejhlavacek** [comment]
Super! Komponenty budou mít přístup defaultně zakázaný a budou si o něj vývojáři muset říct (a budem to ukazovat na stránce aplikace). Mělo by to pak bejt v submission checklistu

**Comment by odinuv** [comment]
myslel jsem to tak, ze kdyz bude nekdo svine, tak si prave ten pristup muze nakonfigurovat v R transformaci

**Comment by ondrejhlavacek** [comment]
Aha, tak to bych tomu předhodil teda nějakej zkonfigurovanej interface, kterej nevede nikam, aby to nešlo občůrat.

**Comment by ondrejhlavacek** [comment]
fixed
