### ISSUE TITLE
Limit cpus and io bandwidth

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#271]
`--device-read-bps`, `--device-write-bps`, `--cpus`

https://keboola.slack.com/archives/C03JBGZDG/p1524126714000272

mohlo by pomoct s https://github.com/keboola/docker-bundle/issues/267

**Comment by ondrejhlavacek** [comment]
write benchmark

https://connection.keboola.com/admin/projects/232/transformations/bucket/383138731/transformation/383138744

~1G file za 18 vteřin => ~55 MB/s

**Comment by ondrejhlavacek** [comment]
read je zhruba 2x tak rychlej

https://connection.keboola.com/admin/projects/232/transformations/bucket/383138731/transformation/383144144

**Comment by ondrejhlavacek** [comment]
Oprava. Šel jsem na to ještě jendou čistým `dd`. Docela zámrd byl s tím, že `dd` při velikosti `2G` a větší dělá nějaký haluze, zřejmě mu přeteče nějaký interní počítadlo a píše nesmyslnej throughput (1,8 G/s). 

US - ~250 MB/s R/W
EU - ~120 MB/s R/W

**Comment by ondrejhlavacek** [comment]
Nastavil bych hard limit throughputu na 100 MB/s a uvedl to do limitů platformy. 
CPU bych nastavil na dva.

**Comment by Halama** [comment]
@ondrejhlavacek máš nějaký docker command který děláš benchmark disku?

**Comment by ondrejhlavacek** [comment]
dej mi minutku, připravím

**Comment by Halama** [comment]
zatím jsem si vygeneroval 1G soubor a zkouším ho v kontejneru kopírovat.

**Comment by ondrejhlavacek** [comment]
používá se na to `dd`, ale zápasím s něčím spolehlivým pro read, aby to neměl nacachovaný

**Comment by ondrejhlavacek** [comment]
benchmark na read je takhle

```
docker run --rm --volume /tmp:/tmp centos sh -c "dd if=/dev/zero of=/tmp/testfile bs=1500M count=1 oflag=dsync"
```

**Comment by Halama** [comment]
možná mi to začalo fungovat:
```
[root@syrup-testing-syrup-docker-i-0c238bf98f8467bf1 ec2-user]# docker run --rm --volume /tmp:/tmp --device-write-bps /dev/md0:10mb php sh -c "dd if=/dev/zero of=/tmp/testfile bs=100M count=1 oflag=dsync"
1+0 records in
1+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 45.1134 s, 2.3 MB/s
```

**Comment by ondrejhlavacek** [comment]
```
docker run --rm --volume /tmp:/tmp centos sh -c "dd if=/dev/zero of=/tmp/testfile bs=1500M count=1 oflag=direct && dd bs=1500M count=1 iflag=direct if=/tmp/testfile of=/dev/null"
```
write i read v jednom

**Comment by ondrejhlavacek** [comment]
hustě!!!

**Comment by Halama** [comment]
jo tak asi jo, 2x jsem zvětšil a 2x to stouplo:
```
[root@syrup-testing-syrup-docker-i-0c238bf98f8467bf1 ec2-user]# docker run --rm --volume /tmp:/tmp --device-write-bps /dev/md0:20mb php sh -c "dd if=/dev/zero of=/tmp/testfile bs=100M count=1 oflag=dsync"
1+0 records in
1+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 22.6084 s, 4.6 MB/s
```

**Comment by Halama** [comment]
Ze začátku jsem to zkoušel tak že jsem si na hostu pomocí dd vygeneroval do /tmp soubor a ten pak zkoušel kopírovat pomocí `cp` v kontejneru a tam mi to nezabíralo. 
Tímhle testem to ale vypadá že to limituje pro read i write z `/tmp`.

A s tím `/dev/md0` můžeš na docker runner instancích počítat, na něj se vždy mountuje `/tmp` https://github.com/keboola/syrup-router/blob/ad5c724851045981418a97bf0ae6f13c94138a1e/provisioning/docker-spot-fleet.json#L606

**Comment by ondrejhlavacek** [comment]
@Halama nenapadá tě, jak podobnej setup alespoň mocknout na devel2/3? nebo jak dynamicky zjistit ten device? propustnost testovat nebudu, ale pouští se všude stejnej command.

**Comment by Halama** [comment]
nevím devel2/3 považuju za věci k vypnutí:) Chceš to do testů? nebo si s tím hrát?

**Comment by ondrejhlavacek** [comment]
Bude to fungovat v kontejneru i mimo `/tmp`?

**Comment by ondrejhlavacek** [comment]
Do testů to nepotřebuju, ale potřebuju, aby se na devel2/3 pouštěly kontejnery stejným `docer run` commandem jako na produkci.

**Comment by ondrejhlavacek** [comment]
Note to self: je to v bps, takže 100 MB/s = 800 mbps.

**Comment by Halama** [comment]
Tohle nastavení se vztahuje jenom na `/tmp`. Můžu zkusit jestli půjde varianta že by to limitovalo uvnitř kontejneru?

**Comment by ondrejhlavacek** [comment]
Jo, mělo by se to limitovat všude, kde ten kontejner může něco zapisovat/číst.

**Comment by Halama** [comment]
^ tím `/tmp` myslím na hostu, takže v docker runneru se to bude vztahovat na vše pod `/data`

**Comment by Halama** [comment]
ok, vyzkouším to. předtím mi to nešlo, ale to bylo zas s tím `cp`.

**Comment by Halama** [comment]
> Do testů to nepotřebuju, ale potřebuju, aby se na devel2/3 pouštěly kontejnery stejným docer run commandem jako na produkci.

Tomuhle nerozumím, k čemu to teda potřebuješ?

**Comment by ondrejhlavacek** [comment]
Tohle je single-point-of-truth pro docker run commandy.

https://github.com/keboola/docker-bundle/blob/79d111cc81132a1661f662368479fc3214f3cbda/Docker/Container.php#L373-L398

Pokud tam přidám `--device-write-bps /dev/md0:20mb`, tak to na develu shnije. Na develu2/3 je ještě komplet dev/testing. 

```
[ondra@kbc-devel-03 ~]$ sudo docker run --rm --volume /tmp:/tmp --device-write-bps /dev/md0:20mb php sh -c "dd if=/dev/zero of=/tmp/testfile bs=100M count=1 oflag=dsync"
docker: Error response from daemon: linux runtime spec resources: no such file or directory.
```

**Comment by Halama** [comment]
to bych nedělal. Počkej mmnt já se k tomu pak vrátím a chci zkusit jestli to bude fungovat i na ten pool. Jak namapovat dynamicky ten tmp pak bude jednoduchý, i když mi to přijde zbytečný.

**Comment by ondrejhlavacek** [comment]
```
[root@kbc-devel-03 ondra]# lsblk --nodeps --output NAME --noheadings 2>/dev/null
xvda
xvdb
xvdh
xvdi
```

**Comment by Halama** [comment]
to schválně pak zkusím jestli to funguje i přímo na tech devices.

**Comment by ondrejhlavacek** [comment]
S těma bps a b/s to není tak jednoznačný. použil jsem teď `--device-write-bps /dev/xvda:10m` a dostávám 
```
1+0 records in
1+0 records out
104857600 bytes (105 MB) copied, 10.0322 s, 10.5 MB/s
```

**Comment by ondrejhlavacek** [comment]
jo, fungue to i přímo na devicech

**Comment by ondrejhlavacek** [comment]
```
[ondra@kbc-devel-03 ~]$ sudo docker run --rm --volume /tmp:/tmp --device-write-bps /dev/xvda:10m --device-write-bps /dev/xvdb:10m --device-write-bps /dev/xvdh:10m --device-write-bps /dev/xvdi:10m centos sh -c "dd if=/dev/zero of=/tmp/testfile bs=100M count=1 oflag=dsync"
1+0 records in
1+0 records out
104857600 bytes (105 MB) copied, 10.0322 s, 10.5 MB/s
[ondra@kbc-devel-03 ~]$ sudo docker run --rm --volume /tmp:/tmp --device-write-bps /dev/xvda:20m --device-write-bps /dev/xvdb:20m --device-write-bps /dev/xvdh:20m --device-write-bps /dev/xvdi:20m centos sh -c "dd if=/dev/zero of=/tmp/testfile bs=100M count=1 oflag=dsync"
1+0 records in
1+0 records out
104857600 bytes (105 MB) copied, 5.03839 s, 20.8 MB/s
```

**Comment by Halama** [comment]
jj, jede to:
docker run --rm --volume /tmp:/tmp --device-write-bps /dev/xvdh:40mb --device-write-bps /dev/xvdg:40mb php sh -c "dd if=/dev/zero of=/tmp/testfile bs=100M count=1 oflag=dsync"
1+0 records in
1+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 1.3112 s, 80.0 MB/s

Jenom je potřeba počítat s tím že jsou v raid takže to dává 2x více.

**Comment by ondrejhlavacek** [comment]
Takže kdyby do RAIDu přibylo víc disků, tak to zase vyletí nahoru.

**Comment by Halama** [comment]
Uvnitř kontejneru mi to zatím nelimituje:
```
docker run --rm --volume /tmp:/tmp --device-write-bps /dev/xvdh:40mb --device-write-bps /dev/xvdg:40mb --device-write-bps /dev/xvdi:40mb --device-write-bps /dev/xvdj:40mb php sh -c "dd if=/dev/zero of=/testfile bs=100M count=1 oflag=dsync"

```

**Comment by Halama** [comment]
hmm, tak jak na to uvnitř kontejneru nevím...

**Comment by ondrejhlavacek** [comment]
Ok, nechám to pár dní být a pak se k tomu zkusím vrátit. To je docela divný, ale potvrzuju, taky mi to nezalimitovalo!

**Comment by ondrejhlavacek** [comment]
nelimituje
```
sudo docker run --rm --volume /tmp:/tmp --device-write-bps /dev/xvda:10m --device-write-bps /dev/xvdb:10m --device-write-bps /dev/xvdh:10m --device-write-bps /dev/xvdi:10m centos sh -c "dd if=/dev/zero of=/testfile bs=100M count=1 oflag=dsync && dd if=/dev/zero of=/testfile bs=100M count=1 oflag=dsync"
```

**Comment by ondrejhlavacek** [comment]
Ještě jsem se v tom vrtal podle https://ogavrisevs.github.io/2016/07/11/isolation-in-docker/#disk-usage-base-device ale neúspěšně. Podle mě failuju na tom, že neumím identifikovat device, kterej používá storage driver pro `/` (třeba `/dev/dm-0`), nebo je taky možný, že se bypassuje.

**Comment by Halama** [comment]
pro `/` se používa device docker poolu

**Comment by ondrejhlavacek** [comment]
A jak zjístím, kterej to je?

**Comment by ondrejhlavacek** [comment]
Z tohodle nic nevykoukám
```
Storage Driver: devicemapper
 Pool Name: docker-thinpool-tpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 17.83 GB
 Data Space Total: 102 GB
 Data Space Available: 84.17 GB
 Metadata Space Used: 6.169 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.063 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.89-RHEL6 (2014-09-01)
```

**Comment by Halama** [comment]
`cat /etc/docker/daemon.json` 
https://github.com/keboola/cookbook-keboola-syrup/blob/04e2121a5faaf5bb245fce8ee5188a2398ba3e89/attributes/default.rb#L46

https://github.com/keboola/syrup-router/blob/ad5c724851045981418a97bf0ae6f13c94138a1e/provisioning/docker-spot-fleet.json#L2474

**Comment by ondrejhlavacek** [comment]
mám tam symlinky na `/dev/dm-*` a ty jsem měl namapovaný všechny a nepomohlo to

```
# ls /dev/mapper/ -la
total 0
drwxr-xr-x  2 root root     160 Apr 27 12:05 .
drwxr-xr-x 17 root root    3160 Apr 27 12:05 ..
crw-------  1 root root 10, 236 May 13  2016 control
lrwxrwxrwx  1 root root       7 Apr  6 10:01 docker-202:1-294926-7197dc0c036efa8d2a4546962f6caf8ab23f2a652a3ffd9c9b1936f44f499ed7 -> ../dm-7
lrwxrwxrwx  1 root root       7 Jun 10  2016 docker-thinpool -> ../dm-6
lrwxrwxrwx  1 root root       7 Jun 10  2016 docker-thinpool_tdata -> ../dm-4
lrwxrwxrwx  1 root root       7 Jun 10  2016 docker-thinpool_tmeta -> ../dm-3
lrwxrwxrwx  1 root root       7 Jun 10  2016 docker-thinpool-tpool -> ../dm-5
```

Pro jistotu jsem zkusil teda i ty symlinky

```
  --device-write-bps /dev/mapper/docker-thinpool:10m --device-read-bps /dev/mapper/docker-thinpool:10m \
  --device-write-bps /dev/mapper/docker-thinpool_tdata:10m --device-read-bps /dev/mapper/docker-thinpool_tdata:10m \
  --device-write-bps /dev/mapper/docker-thinpool-tpool:10m --device-read-bps /dev/mapper/docker-thinpool-tpool:10m \
```

a taky nic

**Comment by ondrejhlavacek** [comment]
Ale myslím, že můžeme udělat docela rozumnej workaround. Kontejner má omezení na 10 GB, do něj se mountuje `/data` a `/tmp` a ty už omezit musíme. Kdyby někdo četl nebo zapisoval nekonečnou smyčku, tak mu v `/` dojde velice rychle místo a v `/tmp` nebo `/data` už bude bandwidth omezená.

**Comment by ondrejhlavacek** [comment]
`--cpus 2` se bude muset revidovat
https://keboola.slack.com/archives/C02CGRFHN/p1525174913000069

**Comment by ondrejhlavacek** [comment]
#289 - omezil jsem defaultně IO na 50 MB/s

**Comment by odinuv** [comment]
merged in 51373ee5e2a2bde67e449e609f653187d1933c2c
