### ISSUE TITLE
move into library

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#275]
splits to syrup wrapper, api wrapper and a new wrapper runnable in docker

**Comment by ondrejhlavacek** [comment]
transformace bych zatím takhle nedělal

**Comment by odinuv** [comment]
nn, nic jinyho by se tak nemelo delat. Je to jen proto abysme mohli zacit delat novou queue

**Comment by odinuv** [comment]
slo by pri te prilzetosti odstranit taky tohle https://github.com/keboola/docker-bundle/commit/125c7e2c097a4e5558e34dc310fd39c53a1c97a0 ?

**Comment by odinuv** [comment]
vytvorit novy repo 
- `runner-sync` (symfony api obal pro sync, mel by se obejit bez syrupu), 
- `runner-encryption` (symfony api obal pro encryption, mel by se obejit bez syrupu) 
- `runner-syrup` (syrup, spusteni jobu, cleanup)

z docker-bundle repo udelat knihovnu - vetsina kodu zustane tu a podrzi si historii, vyhledove prejmenovat na docker-runner

**Comment by odinuv** [comment]
https://keboola.atlassian.net/browse/PS-1684
