### ISSUE TITLE
Chmod timeout tests not working

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#281]
a) tenhle kód vůbec nezavolá metodu `WorkingDirectory::normalizePermissions`

https://github.com/keboola/docker-bundle/blob/da555ae1657c3a55d95837f6f23aee49591a3a97/Tests/Runner/WorkingDirectoryTest.php#L30-L31

b) test by měl failnout, ale proběhne

navrhovaný řešení (+ update po #280)

- `WorkingDirectory` bude mít optional argumenty v ctoru, kterejma se bude setupovat počet retries a random range
- test se opraví, aby failoval
- test se nasetupuje tak, aby proběhl rychle a nemusel čekat dlouhý minuty
- přidá se logování retries
- otestuje se logování retries

**Comment by odinuv** [comment]
pridavat optional argumenty, kteryma se neco nasetupuje neco jen pro testy je cesta do pekel a neni to potreba, test je opravenej, staci pridat to logovani
ceka to jednu minutu, coz je u testu, ktery bezi skoro 2h uz jedno

**Comment by odinuv** [comment]
https://github.com/keboola/docker-bundle/pull/282 - neloguje to retry, ale ten normalize, protoze neni zadny snadny zpusob, jak do https://github.com/vkartaviy/retry pridat logovani na retry

-> mozna bysme mohli tu knihovnu forknout nebo udelat classu jako soucast phputils - @pivnicek by to taky potreboval v db ex/wr

**Comment by pivnicek** [comment]
@odinuv my draft class for that is here: https://github.com/keboola/db-extractor-common/pull/42/files#diff-c879445f100201b591e4e9c8e9cbfbd1

**Comment by odinuv** [comment]
prijde mi to ugly (podminka a promenna jen kvuli logu), ale funkci, btw $logger nepotrebujes usovat a musi to byt notice, jinak se to nezaloguje

**Comment by ondrejhlavacek** [comment]
no a jak bys to řešil? ideálně bys nechtěl říkat "loguj každej druhej a další pokus", ale "loguj podle pravidla X", který úplně stejně budeš nutit uživatele implementovat (a počet retries nemusí bejt jediná podmínka, kterou do toho chceš zanést), takže jen tuhle fuknci rozdělíš do dvou a ten if tam stejně bude. zmizí akorát `$retry = 0;` a `$retry++;`.

**Comment by odinuv** [comment]
idealne bych to resil tak, ze bude logovat ten retryproxy kdyz retrajuje :) aby logoval podle stejne logiky kterou retrajuje

**Comment by odinuv** [comment]
tak mam to tady zmenit na ten counter https://github.com/keboola/docker-bundle/pull/282/commits ?

**Comment by odinuv** [comment]
notice jde jen do PT
