### ISSUE TITLE
remove cpu-shares

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#286]
1) odstranit všechny použití cpu-shares (https://github.com/keboola/docker-bundle/pull/287)
2) ~odstranit cpu shares z developer portalu a synchronizačního skriptu (https://github.com/keboola/connection/pull/1332, https://github.com/keboola/developer-portal-php-client/pull/6, https://github.com/keboola/developer-portal-ui/pull/478, https://github.com/keboola/developer-portal/pull/195)~
3) smazat cpu shares z config definition (https://github.com/keboola/docker-bundle/pull/287)

**Comment by odinuv** [comment]
done in 08fdaf5
