### ISSUE TITLE
Do not store state when OM fails

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#290]

**Comment by Halama** [comment]
Dnes opět při internal erroru OM https://keboola.slack.com/archives/C09U3R1J4/p1532894468000065

**Comment by ondrejhlavacek** [comment]
U klienta si na to stěžovali, že je to dost vypeklo.

**Comment by ondrejhlavacek** [comment]
S deferred output mappingem to bude docela ořech.
https://keboola.slack.com/archives/C03JBGZDG/p1542719018003600
