### ISSUE TITLE
port in use?

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#300]
"message":"Warning: stream_socket_server(): unable to connect to tcp:\/\/0.0.0.0:13103 (Address already in use)"
https://keboola.slack.com/archives/C09U3R1J4/p1526015409000066
maybe, retry does not work?

**Comment by ondrejhlavacek** [comment]
a znovu, dělá to jen google sheets writer

https://keboola.slack.com/archives/C09U3R1J4/p1526346248000158

**Comment by MiroCillik** [comment]
Tusite o co ide? BTW ten port nie je furt rovnaky 0.0.0.0:13142.. 
Ma napadlo, ci to nebude suvisiet s tym GELF loggerom? Ake porty pouziva ten?

**Comment by MiroCillik** [comment]
Zrejme to bude ono, skusal som to googlit v spojitosti s Gelfom, ale nic som nenasiel :/ https://github.com/keboola/docker-bundle/blob/438421904d1f217c5c9a16e6827e81f0c85fe775/Service/Runner.php#L111

**Comment by ondrejhlavacek** [comment]
jj, určitě to souvisí s gelf loggerem, ale nepodařilo se nám zatím odhalit proč

**Comment by MiroCillik** [comment]
Good job 👍
