### ISSUE TITLE
parameters: []

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#318]
řeším problém na bigquery writeru. pustil jsem tuhle konfiguraci, která končí errorem

https://connection.keboola.com/admin/projects/232/writers/keboola.wr-google-bigquery/402210643

v Storage je v konfiguraci uloženo

```
{
    "authorization": {
        "oauth_api": {
            "id": "402210643"
        }
    },
    "storage": {
        "input": {
            "tables": [
                {
                    "source": "in.c-main.test",
                    "destination": "test.csv",
                    "where_column": "",
                    "where_values": [],
                    "where_operator": "eq",
                    "columns": []
                }
            ]
        }
    }
}
```
`parameters` úplně chybí. Pustil jsem na to `debug` API call a tohle dostal jako `config.json`.
```
{
    "authorization": {
        "oauth_api": {
            ...
        }
    },
    "storage": {
        ....
    },
    "parameters": [],
    "image_parameters": [],
    "action": "run"
}
```
`image_parameters` a `parameters` jsou jako prázdný pole místo objektu.

**Comment by odinuv** [comment]
na to uz jsme narazili, mozna by sla sem https://github.com/keboola/docker-bundle/blob/master/Docker/Configuration/Container.php pridat nejaka normalizace?

**Comment by ondrejhlavacek** [comment]
asi hej
