### ISSUE TITLE
Cannot remove container ***: The process "sudo docker rm -f '***'" exceeded the timeout of 120 seconds.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#321]
https://papertrailapp.com/groups/23635/events?q=%22Cannot%20remove%20container%22

nepouští se `docker run --rm` kvůli `docker inspect`

ještě to ověřím, jestli to je nutný a nejde to nějak obejít, případně jestli by to nevyřešil nějakej GC v cronu

**Comment by ondrejhlavacek** [comment]
dělo se to i před přepnutím volume type z `gp2` na `st1`

**Comment by odinuv** [comment]
10.6 se to stalo 2x
9.6 se to nestalo ani jednou

pricital bych to tem zahlcenym workerum a neresil to

**Comment by ondrejhlavacek** [comment]
už se to myslím chvíli nestalo, zavírám

**Comment by ondrejhlavacek** [comment]
pomohlo přejít na overlay2
