### ISSUE TITLE
Sliced file '/data/in/tables/website-forms' does not contain slices.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#323]
Hláška z `processor-create-manifest`, kterej od `processor-move-files` dostal prázdnej soubor.

https://connection.keboola.com/admin/projects/232/jobs/404706022

Je za tím aws-s3-extractor s New Files Only, kterej nestáhl nic.

**Comment by odinuv** [comment]
a co by s tim mel delat docker runner?

**Comment by ondrejhlavacek** [comment]
Nevěděl jsem, do kterýho z těch dvou procesorů to dát

**Comment by ondrejhlavacek** [comment]
nojo, jenže když máš `"columns_from": "header"`, tak nemáš co dělat. tady je imho chyba správně. kdyby za tím byl třeba `processor-add-filename-column`, tak ten bude přidávat sloupce k prázdnýmu listu

**Comment by ondrejhlavacek** [comment]
možná by ten `processor-move-files` měl vyhodit warning, že není co přesunout a nevytvářet adresář.

**Comment by odinuv** [comment]
ok, asi by nemel vytvaret prazdny adresar, kdyz bych to trosku zjednodusil a mel nejakej extractor, co vraci porad stejnou vec, tak by mel ten vystup byt konzistentni - tzn. kdyz vyextrahuje zadny data, tak vytvori prazdny soubory - aby mel vzdy stejnej vystup (generic to takhle dela). 
ty prazdny soubory jsou ale prazdny tabulky (cili maji hlavicku a zadny radky). Uplne prazdnej soubor skonci chybou pri importu. 
Jelikoz s3 ex nema pevne danou strukturu vystupu, tak je fair kdyz nevrati nic, v tom pripade, ale nemuze vracet ani prazdny adresar, v tom pripade by ho move-files nemel produkovat.

cili:
prazdnej soubor (0) = chyba
prazdny csv s hlavickou  = ok (prazdna tabulka)
prazdnej adresar = prazdnej soubor (0b) = chyba
prazdnej adresar s manifestem a columns = ok (prazdna tabulka)

coz vede k zajimave situaci, ze s3 ex nic nevyextrahuje, a create manifest ma pevne dany sloupce a timpadem by mel byt schopnej vytvorit manifest a to nic naimportovat jako prazdnou tabulku

**Comment by ondrejhlavacek** [comment]
`processor-move-files` by volitelně mohl nevytvářet adresář. pokud S3 extraktor (resp `processor-create-manifest`) bude mít fixní uživatelem zadaný sloupce, ať tam klidně je a vytvoří prázdnou tabulku.

**Comment by odinuv** [comment]
jak volitelne? jako myslis, ze by se to fixni nastaveni sloupcu promitlo i do nastaveni create manfist, kde by to reklo, vytvor prazdny adresar?

**Comment by ondrejhlavacek** [comment]
jj, přesně

**Comment by ondrejhlavacek** [comment]
nemusíme to mít chytrý na backendu, když to dokáže nastavit frontend

**Comment by Halama** [comment]
@odinuv myslím že tohle jak si to popsal tady je ok:

1. prazdnej soubor (0) = chyba
2. prazdny csv s hlavickou = ok (prazdna tabulka)
3. prazdnej adresar = prazdnej soubor (0b) = chyba
4. prazdnej adresar s manifestem a columns = ok (prazdna tabulka)

Je potřeba aby to implementoval OM který teď skipne zápis v případě 4 https://github.com/keboola/output-mapping/blob/da959a8ecc2db70b3d245ebe3a94410d40601ab6/Writer/Writer.php#L586

**Comment by Halama** [comment]
Nejsem si jistej u té 3. možná by taky mohla fungovat. Ověřím jak si poradí import do SAPI s prázdným slicem. Na straně exportu to funguje tak že prázdné slices se negenerují, pokud exportuju prázdnou tabulku dostanu sliced soubor s 0 slicy.

**Comment by odinuv** [comment]
ta 3. musi failnout, protoze nevi jaky sloupce by ta tabulka mela mit kdyz tam neni manifest

**Comment by Halama** [comment]
aha ja myslel jako ze tam manifest je ale  chybi adresar. takova situace teda nemuze nastat?

**Comment by Halama** [comment]
kvůli performance by ten skip tady možná https://github.com/keboola/output-mapping/blob/da959a8ecc2db70b3d245ebe3a94410d40601ab6/Writer/Writer.php#L586 mohl zůstat pro inkrementální loady.

**Comment by Halama** [comment]
související diskuze ve slacku https://keboola.slack.com/archives/C035LGNK5/p1528881338000127

**Comment by odinuv** [comment]
tak ten skip tam nebude ani pro inkrementalni loady, protoze tam potom chybi ten importni event, takze se potom jevi, ze to nic neudelalo a neni poznat, ze to naimportovalo prazdny data (inkrementalne nebo neinkremntalne)

**Comment by Halama** [comment]
jo jasně

**Comment by ondrejhlavacek** [comment]
A jak s tím `processor-create-manifest`? Už to bublá v zendesku - https://keboola.zendesk.com/agent/tickets/8808.

**Comment by ondrejhlavacek** [comment]
Máme 2 možnosti (pro use case v ticketu) - 

1) move files nevytvoří subfolder, když nemá co přesunout
2) create manifest nezařve chybu, když v subfolderu nenajde žádnej soubor pro načtení hlaviček (a `columns` nevyplní)

Na 2) mi přijde lepší to, že chování se vyřeší přímo v procesoru, kterej hází chybu, ale keboola/output-mapping stejně zařve chybu, když v manifestu nebudou `columns`, ne? 

1) je takový řešení za rohem, ale možná bude transparentnější?

Ještě by processor-create-manifest mohl prázdný foldery mazat?

**Comment by odinuv** [comment]
mela by to byt 2), protoze pokud vyplnis columns, tak je prazdnej adresar v poradku, pokud to bude 2 a create manifest zahlasi chybu, tak OM se neprovede

**Comment by ondrejhlavacek** [comment]
@odinuv a co se stane, když OM dostane manifest, ve kterým nebudou uvedený sloupce a bude prázdnej sliced folder? sloupce v create manifest jsou tady vyplňovaný ze souboru, zatím jsem neviděl, že by je někdo vyplňoval ručně.

**Comment by odinuv** [comment]
aha, ja to cetl 
> create manifest **zařve** chybu, když v subfolderu nenajde žádnej soubor pro načtení hlaviček (a columns nevyplni

kdyz 
>  a co se stane, když OM dostane manifest, ve kterým nebudou uvedený sloupce a bude prázdnej sliced folder? 
tak to napise `Sliced file 'table': columns specification missing.`

**Comment by odinuv** [comment]
ja bych rekl, ze pokud to ma tendenci extrahovat uplne prazdny soubory, tak musis `columns` zadat rucne, kvuli tomu tam to nastaveni je, jinak proste nemame sanci zjistit jaky sloupce tam maji byt

**Comment by odinuv** [comment]
takze pokud extrahuje uplne pradny slicy a neni zadany columns, tak create manifest zarve, ze je mas nastavit

**Comment by ondrejhlavacek** [comment]
Hm, tak to je docela chytrý. Zkusím si to nasimulovat a pokud to projde, tak jim to navrhnu jako řešení. A upravit create manifest, ať zahlásí lepší hlášku. Díky!

**Comment by ondrejhlavacek** [comment]
Jo, tak to funguje, akorát se bude muset ručně připojit `processor-skip-lines`, protože ty soubory, když to nějaký najde, hlavičku maj. Takže to pak bude v JSONu, ale furt lepší, než nic :-)

**Comment by odinuv** [comment]
no pockej, ale kdyz hlavicku maji, tak se da nacist z nich ne?

**Comment by ondrejhlavacek** [comment]
Tvl, motáme se dokolečka :-). S3 extraktor má nastaveno `newFilesOnly` a je možný, že v aktuálním runu žádný soubory nestáhne.

**Comment by odinuv** [comment]
no o newfilesonly tu doted nebyla rec :)

**Comment by ondrejhlavacek** [comment]
Eh, sorry, je to jen v tom zendeskovým ticketu.

**Comment by odinuv** [comment]
podle me to zalezi na tom, jak to chapeme, jako je mi jasny, ze newfilesonly se pouzije v 99% s incrementalnim loadem, ale kdyby se nepouzilo s inkrementalnim loadem, tak chces tu cilovou tabulku smazat nebo nechat byt? Kdyz zadny newfiles nejsou, ma se udelat importni event nebo se "nema stat nic"?

**Comment by odinuv** [comment]
osobne si myslim, ze by se to melo povazovat za prazdnou tabulku (udelat importni event) a v priapde neikrementalniho loadu tabulku vyprazdnit, v tom pripade je pitomy, ze to nema tu hlavicku a jediny co me k tomu napada je udelat to jako v genericu, kterej si do state uklada posledni hlavicky pro importovany tabulky

**Comment by ondrejhlavacek** [comment]
Mně teďka přijde nejvhodnější to přepnout do "power user režimu" (JSON), nastavit hlavičky ručně a přidat skip lines procesor. Tím dokážeš ošetřit všechny možný stavy a nepotřebuješ state. State bys chtěl ukládat kam? Musel by bejt v procesoru create manifest?

**Comment by odinuv** [comment]
taky bych to ted resil tak jak pises, state by musel byt u toho ex a tim se to cely komplikuje, procesor state nema

**Comment by ondrejhlavacek** [comment]
finálně by to šlo celý odbavit v UI, který by neumožnilo `newFilesOnly` + `columnsFrom: header` a napsalo by ti, co a jak máš udělat/vyplnit.

**Comment by ondrejhlavacek** [comment]
narazil jsem ještě na jednu věc - když v tomhle scénáři přidám na konec `processor-skip-lines`, tak ten vymaže prázdnej folder se slicy a nechá manifest

=>

![image](https://user-images.githubusercontent.com/497675/43127209-308c2f20-8f2f-11e8-8976-93a6113d3486.png)

stačí ho ručně dát na začátek a nebo upravit tak, aby nemazal prázdný foldery (a udělat z toho obecný doporučení pro všechny procesory?)

**Comment by odinuv** [comment]
IM i OM je upraveny podle https://github.com/keboola/docker-bundle/issues/323#issuecomment-396918614 a nasazeny, S3 resime v https://github.com/keboola/internal/issues/21
