### ISSUE TITLE
Allow longer error outputs if possible

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/docker-bundle#334]
Těch 250 znaků je fakt málo:  https://github.com/keboola/docker-bundle/blob/master/Docker/Container.php#L328-L330

**Comment by kacurez** [comment]
dalsi report https://keboola.zendesk.com/agent/tickets/8982

**Comment by kacurez** [comment]
dalsi report :)
![image](https://user-images.githubusercontent.com/1412120/44215687-6f92c200-a173-11e8-8e5e-6ece19199454.png)
Je to user error ale neni tam vidno u ktoreho stlpca sa to stalo(nasiel som to az v PT)

**Comment by Halama** [comment]
další dotaz https://keboolaglobal.slack.com/archives/C5K31TYKT/p1536741812000100
