### ISSUE TITLE
Application error: Image definition is empty or invalid: The child node "definition" at path "component" must be configured.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#335]
Patrně někdo pouští komponentu ještě než se poprvý deployne. User exception?

https://connection.keboola.com/admin/utils/logs?file=2018/07/30/11/2018-07-30-11-56-19-5b5ee0c3adb90-exception
https://connection.keboola.com/admin/utils/logs?file=2018/07/30/11/2018-07-30-11-56-19-5b5ee0c3c7222-log

**Comment by ondrejhlavacek** [comment]
mohlo by to hodit něco jako "Invalid component definition"?

**Comment by odinuv** [comment]
furt mi to prijde jako blbost - to bysme mohli resit, ze mas spatne `CMD` v dockerfilu a je to taky invalid component definition a uzivatel s itm nemuze nic udelat

spis by melo byt v devportalu obrovskej cervenej vykricnik u appky ktera to nema doplneny
a pokusit se pripadne zaridit, aby se to spravne forwardovalo autorovi appky

**Comment by ondrejhlavacek** [comment]
> spis by melo byt v devportalu obrovskej cervenej vykricnik u appky ktera to nema doplneny
a pokusit se pripadne zaridit, aby se to spravne forwardovalo autorovi appky

tak to stopro! narážel jsem jen na to, že teď to není a stejná chyba se opakovala víckrát od stejnýho člověka, takže byl očividně v pasti
