### ISSUE TITLE
Job images in results also for failed job

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#337]
Hodně by pomohlo debugu, ihned by šlo vidět že failnutý job jel na jiné verzi než předchozí zelený job.

**Comment by odinuv** [comment]
pomohlo, bohuzel to nejde protlacit pres syrup kvuli tomuhle https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L224

**Comment by Halama** [comment]
aha, jestli to nejde jednoduše tak až v novém docker runneru.

**Comment by odinuv** [comment]
fixed in new queue
