### ISSUE TITLE
Working hard on empty jobs

### ISSUE THREAD

**Issue by padak** [keboola/docker-bundle#338]
S3 extractor can spend 1.5min by running processors on no data. It looks weird (https://connection.eu-central-1.keboola.com/admin/projects/25/jobs/5741762):

![image](https://user-images.githubusercontent.com/1427901/43567694-d677b788-9632-11e8-909a-d7615f2e23de.png)

And it prevents us to run it much faster. What do you think? It would be great if empty job will be killed in few secs.

**Comment by Halama** [comment]
tohle bude způsobené S3 extractorem a nastavením newFilesOnly. S3 neumí filtrovat podle času, takže extractor musí vždy vylistovat uplně všechny soubory a pak je ofiltrovat https://github.com/keboola/aws-s3-extractor/blob/ff8687b5715a24e25dd6c0647f42ad1a79960f61/src/Keboola/S3Extractor/Extractor.php#L180

![image](https://user-images.githubusercontent.com/903531/43568148-2857cbdc-9634-11e8-8efe-754594cab08a.png)

Řešil jsem to právě u tahání [AWS logů](https://connection.keboola.com/admin/projects/258/extractors/keboola.ex-aws-s3/399279996) kde jsou tisíce souborů jak to správně schedulovat, to vylistování tam trvá 4 min:

![image](https://user-images.githubusercontent.com/903531/43568246-5bfcde3c-9634-11e8-801a-6eaaa8243a55.png)

**Comment by odinuv** [comment]
1.5min? i see 4secs

**Comment by ondrejhlavacek** [comment]
jo, to jo!
@padak job jede cca 100 vteřin, iteruje přes 6 rows (~16 vteřin na jeden row) z toho
- S3 extraktor jede 79 vteřin (většinu času z toho IMHO listuje existujícíma souborama v S3, protože `New Files Only` a ze S3 to jinak než listováním všech souborů dostat nejde), cca 13-14 vteřin v každým řádku
- Procesory v každým configu jsou do 3 vteřin hotový (18 vteřin total)
- Zbytek (řádově pár vteřin) je overhead Docker Runneru

Co z toho tě pálí nejvíc?

**Comment by padak** [comment]
Ach, ok! Tak to pak rozumím! Změním lifecycle, aby se soubory dávaly dřív
do řiti. Ve finále mě na tom pálí, že to dělá něco co nemusí. Je asi jedno,
že to je pár sec, instinktivně víme, že to je zbytečnej úkon, tak mi
přijde, že by ho chytrá KBC měla skipnout.

**Comment by ondrejhlavacek** [comment]
@padak nojo, jenže ti tady stejně dobře můžu vymyslet use case, kde chceš aby se procesory pouštěly, i když extraktor nic nestáhne.

**Comment by Halama** [comment]
zatim prave nevim jiste ze to je zbytecne ukon https://github.com/keboola/internal/issues/21#issuecomment-407393864

**Comment by ondrejhlavacek** [comment]
jj, přesně

**Comment by odinuv** [comment]
zaviram, bud je to otazka na S3 ex a listovani anebo celkove optimalizace runneru
