### ISSUE TITLE
don't handle container terminated by SIGTERM(143) as app error

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#347]
Ked sa vypina instance, vsetkym procesom vratane beziacich docker kontajnerov posle SIGTERM. Stalo sa ze pocas tohto docker-runner(predtym nez sa vypol) stihol spadnuty docker kontajner ukoncit ako app error. 
riesilo sa to tu:
https://github.com/keboola/ex-facebook-graph-api/issues/46#issuecomment-417218585

**Comment by kacurez** [comment]
tak problem bude asi specialne len u java apps(ako je ex fb). Tie totiz na SIGTERM(143) zareaguju tak ze sa hned skoncia. PHP aplikace ten SIGTERM zrejme ignoruju a ukoncia sa az na SIGKILL(137) ktory sa posle po nejakej dobe nato.
Docker runner taketo apky restartne:
`message: Application error: Application error: Application error: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-mysql:3.1.3 container terminated. Will restart.`
https://github.com/keboola/docker-bundle/blob/62ce8c589a946177045e1aef181386a4268a9638/src/Docker/Container.php#L343
https://papertrailapp.com/systems/kbc-us-east-1-syrup-docker-i-05e0d2eb104fa8177/events?focus=971608752161693731&selected=971608752161693731

**Comment by odinuv** [comment]
@kacurez tohle si ale nejak vyresil v te appce ne?

**Comment by kacurez** [comment]
jj a podla vsetkeho to zabralo.
https://github.com/keboola/ex-facebook-graph-api/pull/60

**Comment by odinuv** [comment]
supr, tak to zatim nechame tak jak to je
