### ISSUE TITLE
Processor is running for 34 hours

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#348]
![image](https://user-images.githubusercontent.com/903531/44979360-3a58e300-af6d-11e8-800a-9c1af699c64b.png)

https://keboola.zendesk.com/agent/tickets/9046

**Comment by Halama** [comment]
`docker stats` nad tím neproběhne. jdu ten kontejner killnout aby se to probralo.

**Comment by Halama** [comment]
blokuje to spouštění jobů té konfigruace.

**Comment by Halama** [comment]
V ui ten job vypadá takhle:
![image](https://user-images.githubusercontent.com/903531/44979669-00d4a780-af6e-11e8-862a-ec2803d886c7.png)

**Comment by Halama** [comment]
Nejde ani zabít, instance ale přitom jinak vypadá ok.

**Comment by Halama** [comment]
Vypnul jsem celou tu instanci a rozjelo se to, tím pádem tam i ten obalující PHP proces který drží zámek běžel.

**Comment by Halama** [comment]
Na té instanci se ale jinak joby spouštěly v pohodě. Docker commandy reagovaly rychle, jenom stats a kill nad tím konkrétním vytuhly.

**Comment by ondrejhlavacek** [comment]
to je divný teda :-( `docker inspect` taky nic neříkal?

**Comment by odinuv** [comment]
mohli bysme tam dat natvrdo `--stop-timeout` na 24h? sice to neresi pricinu, ale byla by to takova posledni zachrana (pokud to teda dockeru funguje)

**Comment by odinuv** [comment]
@ondrejhlavacek docker inspect nam stejne nic rekene, to musel vytuhnout ten systemovej  `timeout`, protoze kdyby se nespustil, tak se nespusti ten container vubec, kdyby se ukoncil, tak se ukonci ten symfony process a ten PHP skript dobehne a uvolni zamek

**Comment by odinuv** [comment]
asi unrelated https://gitub.com/moby/moby/issues/28207

**Comment by odinuv** [comment]
mozna bysme celou tu nasi habaduru mohli nahradit tim `--stop-timeout` ? v docker 17 uz by to melo byt available

**Comment by odinuv** [comment]
nemohli, nefunguje to

**Comment by ondrejhlavacek** [comment]
ale ten `timeout --foreground` by mohl stát za pokus

**Comment by Halama** [comment]
docker inspect jsem nezkoušel a ten nic zajímavého co by pomohlo debugu neřekne.

**Comment by Halama** [comment]
ten systémovej timeout asi mohl vytuhnout na tom že ten kontejner nešel vůbec killnout ne?

**Comment by ondrejhlavacek** [comment]
@Halama jakým signálem ses ten proces pokoušel zabít?

**Comment by ondrejhlavacek** [comment]
Kua, `timeout --signal=SIGKILL` už tam teď máme a proces to nezabilo :-(
Asi by se dalo tím systémovým `timeout`em obalit vše a vyprdnout se na timeout v `Symfony/Process`, ale pohledem do zdrojáků `Symfony/Process` by taky měl posílat SIGKILL.

**Comment by ondrejhlavacek** [comment]
Připomíná mi to situaci, když jsem benchmarkoval disky s limitama, nešly zabít ani ty `docker stats` commandy.

**Comment by odinuv** [comment]
ale tady to prece nezabiji symfony timeout, ale prave ten timeout sigkill kterej se na to vyprdl

**Comment by ondrejhlavacek** [comment]
a myslíš, že by symfony timeout byl úspěšnější? když to nezabil ani `docker kill`

**Comment by odinuv** [comment]
ne, ale tys to napsal:

> Asi by se dalo tím systémovým timeoutem obalit vše a vyprdnout se na timeout v Symfony/Process

**Comment by ondrejhlavacek** [comment]
to bylo na ty ostatní docker commandy, ne na `docker run`. 

pokud si pamatuju, tak naše verze a použití `Symfony/Process` neumí killnout proces za běhu, ale vyhodít timeout až na konci, je to tak? i když podle zdrojáku by to mělo dělat. proto jsme tam nahazovali ten systémovej `timeout`.

jestli ti přijde, že jsem zmatenej, tak ti to tak nepřijde, jsem. je to divný! :-)

**Comment by ondrejhlavacek** [comment]
Hm, jak se dostal `Process timed out` do jobu?

**Comment by Halama** [comment]
feature syrupu

**Comment by Halama** [comment]
tady https://github.com/keboola/syrup-queue/blob/8a874b5cd9a04f9688fb3e63d1a522b7150e071f/Strategy/LegacyStrategy.php#L37

**Comment by ondrejhlavacek** [comment]
Fulltext search mlčí, kde to najdu?

**Comment by ondrejhlavacek** [comment]
Super!

**Comment by ondrejhlavacek** [comment]
Hm, tak teď nemám pocit, že bychom s tím mohli něco udělat, nápady? Udělal bych nějakej search a notifikaci na podobný joby a když se to stane, šel bych to nějak na instanci víc oťukat?

**Comment by odinuv** [comment]
no tezko delat search a notifikaci na neco co neprodukuje eventy :/

**Comment by ondrejhlavacek** [comment]
V jobech to je

**Comment by odinuv** [comment]
obsolete
