### ISSUE TITLE
Limits defined for project

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#35]
Možnost přetížit limity komponent jako `process_timeout`, `memory`.

Limity by se definovaly pro projekt. Pak by se budˇ vraceli API callem projektu nebo by je možná přetížené mohlo vracet přímo https://connection.keboola.com/v2/storage ?
To se mi ale úplně nezdá možná by se to mohlo nějak spojit i s komponentama per projekt.

Souvisí s https://github.com/keboola/tableau-server-writer/issues/1

**Comment by odinuv** [comment]
Myslim, ze by to mel vracet nejakej API call projektu, jakmile by se melo v seznamu komponentu zobrazovat neco uz pretizene, tak z toho bude bordel (z ruznych mist bude videt ruzna hodnota)

**Comment by Halama** [comment]
jo toho se taky bojim, ten seznam nechame teda radsi globalni

**Comment by ondrejhlavacek** [comment]
přesunuto do productboardu - https://keboola.productboard.com/inbox/notes/22880
