### ISSUE TITLE
oauth credentials not working in sydney

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#351]
postup:

- zautorizovat fb extractor config v sydney: https://connection.ap-southeast-2.keboola.com/admin/projects/2/extractors/keboola.ex-facebook
- pustit job(alebo staci zavolat sync akci Select Pages)

skonci to na chybe:
```
Application error: OAuth API error: Client error: 
`GET https://syrup.ap-southeast-2.keboola.com/credentials/keboola.ex-facebook/1091` resulted in a `404 Not Found` response:
{"error":"Component credentials not found"}
```

je tam chybna url, konkretne v ceste chyba id syrup komponenty `oauth-v2`, spravne by ta url mala byt: `https://syrup.ap-southeast-2.keboola.com/oauth-v2/credentials/keboola.ex-facebook/1091`

**Comment by kacurez** [comment]
ked sa pozriem do https://connection.ap-southeast-2.keboola.com/v2/storage
tak u komponenty `keboola.oauth-v2` vidim spravnu uri `https://syrup.ap-southeast-2.keboola.com/oauth-v2`

**Comment by Halama** [comment]
bude to asi špatně v té template konfiguraci mmnt

**Comment by Halama** [comment]
Tady to dokonce je https://github.com/keboola/syrup-router/blob/master/provisioning/config-template/syrup/docker/parameters.yml
Mrkni jak to tam je v té konfiguraci vyplněné.

**Comment by kacurez** [comment]
tak ani stym lomitkom na konci to nefunguje..potreboval by som ale overit postup ze som to urobil dobre, ten reboot instanci

**Comment by kacurez** [comment]
tak bolo to lomitom
TODO: fixnut v template parameters.yml

**Comment by odinuv** [comment]
tak to tady muzem zavrit, ne?
