### ISSUE TITLE
Error response from daemon: manifest for *** not found

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#362]
Pokud pustím custom tag komponenty, který neexistuje, docker runner skončí app errorem. Mohl by to bejt user error a říct, co se stalo a aby nám to někde neuletělo, může se na tenhle user error hodit  notofikace do příslušnejch kanálů.

https://keboola.slack.com/archives/C09U3R1J4/p1540147867000100

https://connection.keboola.com/admin/utils/logs?file=2018/10/18/15/2018-10-18-15-48-08-5bc88f181945b-exception
https://connection.keboola.com/admin/utils/logs?file=2018/10/18/15/2018-10-18-15-48-08-5bc88f1833191-log

**Comment by odinuv** [comment]
obsolete
