### ISSUE TITLE
Retry on ThrottlingException / cache getAuthToken response?

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#375]
Ked nastane exception pri `GetAuthorizationToken`, mali by sme spravit retry.

Este mi napada, ci by sme si tie tokeny nemohli hodit do cache? Su platne 12h.

> Retrieves a token that is valid for a specified registry for 12 hours. This command allows you to use the docker CLI to push and pull images with Amazon ECR. If you do not specify a registry, the default registry is assumed.

Napriklad ak by to bolo per repozitar (vlastne per komponentu), mohlo by to usetrit par api callov.

**Comment by odinuv** [comment]
idealne by to melo byt imho tak, ze by devportal posilal image id, potom si muzem lokalne vylistovat jestli pozadovanej image mame s danym id pritomnej i lokalne, tim by se usetrila cela ta maskarada okolo login a pull a krasne by se to zrychylilo (hlavne sync akce)

**Comment by ondrejhlavacek** [comment]
tak to by bylo dost super!

**Comment by ondrejhlavacek** [comment]
co kdybychom mezi tím ještě zažádali o zvýšení limitů, ať se to nezpomaluje? tohle by to pak mohlo fixnout trvale

**Comment by ondrejhlavacek** [comment]
Jo, taky jsem k něčemu podobnýmu došel - https://keboola.slack.com/archives/C02CGK5CL/p1544867490268700

**Comment by ondrejhlavacek** [comment]
V okamžiku, kdy to zahlásilo ThrottlingException, tak bylo dohromady 5 requestů za vteřinu.

**Comment by Halama** [comment]
to je divný neměli by do toho sahat i ECS sapi?

**Comment by odinuv** [comment]
jo, obcas, obcas je tam taky dev portal, ale to jsou drobny

**Comment by ujovlado** [comment]
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/faq.html

> Throttling exceptions, including RequestLimitExceeded, Throttling, ProvisionedThroughputExceededException, ThrottlingException, RequestThrottled and BandwidthLimitExceeded, are also handled with retries.

https://github.com/aws/aws-sdk-php/blob/0e07e92ec7042316ffc79ef290cf7bbb7d7be24b/src/RetryMiddleware.php#L22-L32
