### ISSUE TITLE
run config rows with invalid input should be user error

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#394]
https://keboola.slack.com/archives/C02CGK5CL/p1549639567042800

run body: `{"config":"358642681","row":{"id":"463615221"},"component":"keboola.ex-aws-s3","mode":"run"}`

result:
`
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [params.row]"}],"type":"mapper_parsing_exception","reason":"failed to parse [params.row]","caused_by":{"type":"illegal_argument_exception","reason":"unknown property [id]"}},"status":400}
`

**Comment by ondrejhlavacek** [comment]
nemělo by to být spíš na syrup?

https://connection.keboola.com/admin/utils/logs?file=2019/02/08/16/2019-02-08-16-25-25-5c5d9f6587ddd-exception

https://connection.keboola.com/admin/utils/logs?file=2019/02/08/16/2019-02-08-16-25-25-5c5d9f65a2298-log

**Comment by kacurez** [comment]
ok prehodil som to do syrupu https://github.com/keboola/syrup/issues/133
