### ISSUE TITLE
Failure while adding metadata

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#401]
The extractor failed while adding metadata to `_timestamp` column.

https://keboola.slack.com/archives/C09U3R1J4/p1553613188034600

**Comment by odinuv** [comment]
hm, to by melo byt vyreseny timhle https://github.com/keboola/php-utils/pull/2

**Comment by tomasfejfar** [comment]
Není to vyřešené, nebo to je způsobené něčím jiným. 

https://keboola.slack.com/archives/C09U3R1J4/p1554111727013200 a https://keboola.slack.com/archives/C09U3R1J4/p1554113947014400

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/docker-bundle/commit/37c0a09e42398fac5d35115150599adda5c896eb
