### ISSUE TITLE
Support for table attributes in output mapping

### ISSUE THREAD

**Issue by pivnicek** [keboola/docker-bundle#42]
Would like to be able to set ui.maxSampleRows attribute for a table.
Some cases with large text/blob columns the storage console will freeze while fetching data, if the component knows that it has a table like this (emails for example) it can override the maxSampleRows to a low number for better performance.

**Comment by ondrejhlavacek** [comment]
@pivnicek this should go through productboard I suppose. The right solution is a more clever data sample.

**Comment by ujovlado** [comment]
Related to https://github.com/keboola/kbc-ui/issues/512
