### ISSUE TITLE
Podchytit vypinajici se worker

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#428]
cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory
a podobne se obcas objevuje a crashne to job, mozna se to vyresi prechodem an ecs, ale stejne to tu necham

**Comment by Halama** [comment]
Teď se stalo při pokusu o spuštění processoru :
```
message: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.processor.transpose:1.2.6 container '522839213-522839178.522839214--1-keboola-processor-transpose' failed: (125) docker: Cannot connect to the Docker daemon at unix:///var/run/docker.
```

**Comment by Halama** [comment]
Pokud už kontejner běží chová se to korektně https://github.com/keboola/docker-bundle/blob/9ba88e74509141871b0eea3d5f19d65f650cc1f8/src/Docker/Container.php#L354

**Comment by odinuv** [comment]
obsolete
