### ISSUE TITLE
Input Mapping State GC

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#433]
pokud pustím single job s adaptivním input mappingem non-config rows komponenty, která má víc adaptivních tabulek, tak se přepíše celý input mapping state tou single job tabulkou.

je tam kombinace `configData` (s jedním input mappingem) a `config`

https://keboola.slack.com/archives/C02C3GZUS/p1561627818021500

řešení by bylo vyhodit GC input mapping state, tj. job by state pouze aktualizoval a ne přepisoval a o GC by se staralo UI (smazat položku ze state při smazání tabulky ve writeru)

cc @odinuv

**Comment by odinuv** [comment]
podle me to bude silenej zamrd, nemuzes prece dat garbage collect nejakyho API na starost UI

reseni je mit snowflake writer jako config-rows komponentu

**Comment by ondrejhlavacek** [comment]
vyřeší https://github.com/keboola/kbc-ui/issues/3485

**Comment by ondrejhlavacek** [comment]
a taky souhlas s odinem, měla by to být config rows komponenta
