### ISSUE TITLE
processors & sync actions

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#447]
ukazalo se, ze procesory se spousti i pro sync akce, cili kdyz se prida procesor za db ex, tak ten procesor pak failuje na `testConnection`:

147946154733.dkr.ecr.us-east-1.amazonaws.com\/developer-portal-v2\/keboola.processor-add-metadata:0.2.0 container '0-541979862--1-keboola-processor-add-metadata' failed:
[]\n[2019-10-07 06:55:44] php-component.CRITICAL: Keboola\\Component\\Exception\\BaseComponentException:Unknown sync action \"testConnection\", method does not exist in class 

workaround je pochopitelne v tom ten procesor upravit tak, aby to snasel. Ale prijde mi, ze je to celkove ptakovina - sync akce maji NullDataLoader, tzn. null IM i OM, tzn. neexistuje podle me nic, co by mohl before i after procesor udelat.

**Comment by ondrejhlavacek** [comment]
jasně, to je nějaká blbost, pryč s tím

**Comment by odinuv** [comment]
no tak to slo rychle :D dik

**Comment by ondrejhlavacek** [comment]
hele! ale! ten api call pro sync akci připravuje UI, takže tam ty procesory vůbec nemá co strkat
