### ISSUE TITLE
Don't fail on pull image

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#46]
Protože Dockerhub registry může mít výpadky, chceme mít něco jako backoff na `docker pull`, aby se nestávalo tohle https://keboola.slack.com/archives/docker-notifications/p1459375464000020https://keboola.slack.com/archives/docker-notifications/p1459375464000020

Easy častečný řešení: pullovat pouze image, který mají tag master/latest (verzovaný tagy se stejně nemají co měnit)
Full řešení: backoff na docker pull, docker login atd.

**Comment by ondrejhlavacek** [comment]
Už je to hotový
