### ISSUE TITLE
Sleep in R seems to do nothing

### ISSUE THREAD

**Issue by odinuv** [keboola/docker-bundle#460]
Sys.sleep(10)
print('doing something')
Sys.sleep(3)
print('doing something else')
Sys.sleep(3)
write('still doing something', stdout())
Sys.sleep(3)
write('error message', stderr())
Sys.sleep(3)
app$logInfo("information")
Sys.sleep(3)
app$logError("error")
Sys.sleep(3)
TRUE

produces 

![image](https://user-images.githubusercontent.com/4319320/68428703-f682ee80-01ac-11ea-853c-f453a20ee67d.png)

there is no sleep between the events

**Comment by ujovlado** [comment]
Are you sure? :) I am able to see it 10 seconds at the beginning, then 3 seconds few times, etc.

**Comment by odinuv** [comment]
jop, je to spravne, zmatl me ten sloucenej error a ten je taky spravne
