### ISSUE TITLE
Validate component configuration

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#48]
Myslim, ze by sme mali validovat konfuguraciu komponent. Napr. preto aby sa predvyplnili jej default hodnoty.

**Comment by ujovlado** [comment]
Related to https://github.com/keboola/kbc-ui/pull/523

**Comment by odinuv** [comment]
Doplnim: sifrovani ano, ale config parser ne
[12:23] 
cili kdyz prijde konfigurace {"foo": "bar"}, udela se z ni stdclass, zasifurje se, potud ok, pak muzu vzit
[12:23] 
`$configuration = (new Container())->parse($configuration);`
[12:23] 
a to skonci na tom, ze config neni pole, protoze ho neumi zpracovat
[12:24] 
ale prevadet na pole to nemuzeme, protoze pri ulozeni konfigurace vadi kdyz se {} prevede na []

**Comment by ondrejhlavacek** [comment]
@ujovlado validovat konfiguraci kdy?

**Comment by ujovlado** [comment]
@ondrejhlavacek predtym nez sa pushne do Storage API ... ale myslim, ze sme to uz preberali :wink:

**Comment by ondrejhlavacek** [comment]
nojo vlastně :-) to bylo to, co se mi hrozně nelíbilo, tak jsem to vytěsnil :-)

**Comment by odinuv** [comment]
moved to https://github.com/keboola/internal/issues/5
