### ISSUE TITLE
sync api calls

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#51]
Potřebujeme mít možnost z UI volat akce na kontejnerech synchronně (ověření credentials, vylistování tabulek v DB/ souborů v dropboxu).

Poběží to na současných docker workerech (kvůli zdrojové IP, VPN/SSH tunelu), @Halama připraví vlastní hostname a load balancer. 

Docker bundle komponenty budou mít rozšířené API, kromě `{componentId}/run` bude možné pustit `{componentId}/action/{action}`. V definici komponenty bude řečené, jaké synchronní akce komponenta podporuje:

```
{
  "definition": {
    "type": "dockerhub",
    "uri": "blueskydigital/keboola-ex-itunes-connect-docker"
  },
  "synchronous_actions": ["verify", "list"],
  "vendor": {
  ...
  },
  "configuration_format": "json"
}
```

Docker-bundle ověří, zda komponenta synchronní akci podporuje a pokud ano, zavolá kontejner, kterému do serializované konfigurace přidá atribut `action`:
```
{
    "storage": {
        ...
    },
    "parameters": {
        ...
    },
    "action": "verify"
}
```

*Pozn: `action` bude vyplněný i pro async `run` api call*

Docker bundle nebude tahat konfiguraci ze Storage, konfigurace musí být vždy poslaná na synchronní API celá (UI musí konfiguraci načíst a poslat). Nebudeme zatím omezovat input/output mapping. 

Na běh kontejneru bude striktní časový limit (30 s), `docker pull` nebude do limitu zahrnutý. Pokud kontejner časový limit překročí, API vyhodí `504 Gateway Timeout`. Tyto akce nebude vidět v jobech.

**Comment by kacurez** [comment]
nebolo by lepsie cestu url sync akce rozlisovat cez `sync` v URL? tj namiesto `{componentId}/{action}` by bolo `{componentId}/sync/{action}`? Aby sa nahodou nekrizilo stym co uz tam je ako napr `{componentId}/encrypt,dry-run` atd..:
https://github.com/keboola/docker-bundle/blob/master/Resources/config/routing.yml
inac super popisane!

**Comment by odinuv** [comment]
Taky bych byl pro to dat tomu neco jinyho nez /run/

**Comment by odinuv** [comment]
+ mozna bych tomu predal ten action jeste jako parametr v run - aby se mohla aplikace rozhodnout, co chce delat bez potencialne slozityho cteni konfigu

**Comment by ondrejhlavacek** [comment]
@odinuv tomu se ale zabrání v controlleru, router bude fallbackovat na /{componentId}/{action} na `customAction`, a ta nic s configem dělat nebude

@odinuv určitě bych to dal něco jinýho než run, protože jinak bude `runAction` začínat
`if (method != 'run')` a bude to větvit celou funkcionalitu metody => má to bejt vlastní metoda.

@kacurez kdyby se to pojmenovalo jako `{componentId}/action/{action}`, tak by to šlo, jinak v tom nevidím problém, že by se popsalo, jaký názvy akci nejsou dovolený

**Comment by kacurez** [comment]
radsej to mat oddelene lebo v buducnosti by sa mohlo stat opak ze budete do docker bundlu chciet pridat novy api call(ako napr {componentId}/encrypt) a budete zistovat ci sa encrypt uz nepouziva v inej komponent pod sync_actions

**Comment by ondrejhlavacek** [comment]
@kacurez aaaaight!

**Comment by Halama** [comment]
API na workerech je připravený https://syrup-docker.keboola.com/

**Comment by odinuv** [comment]
solved in 78ffbed3db25c70df824e9b34d7dfb0a4fc23621
