### ISSUE TITLE
Legacy Syrup Component Cleanup

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#52]
Tady je soupis všech syrup komponent a co je s nima potřeba udělat.

## Deprecated komponent s novou docker runner verzí
U tehle komponent jenom stačí dotlačit uživatele k migraci a jakmile je nikdo nebude používat můžou se smazat.

- [x]  wr-google-drive - pozor spouštího i tde-exporter (Tableau writer)
  - [x] tde-exporter + google drive integrace - chce vyřešit jinak https://github.com/keboola/tde-exporter/issues/3 + https://github.com/keboola/docker-bundle/issues/175
- [x] ex-fb-ads 
- [x] ex-facebook
- [x] ex-google-drive
- [x] ex-zendesk
- [x] sapi-importer - použito na posledních 3 projektech, poslal jsem jim tickety, pak se to vyhodi.
- [x] wr-db
- [x] ex-salesforce  - Nemá migrační tool, používá ale jenom pár projektů

## Nemají zatím náhradu
Staré komponenty které pořád nabízíme a je možné je založit.
Je potřeba vyřešit co s nima. Bud je zkusit nahodit genericem, naimplementovat znovu pro docker runner nebo je uplne zavrhnout.

- [x] ex-getstat - Používá jeden projekt. Mrknem jestli půjde použít generic https://keboolaglobal.slack.com/archives/C5CDKU5DK/p1505812750000071
Projekt který to používal je vypnutej
- [x] ex-magento - Používá jeden projekt, jde o starou verzi Magento 1, pokud neupgradují budueme muset asi zabalit do dockeru. Nebo začít tahat data přímo z db? https://keboolaglobal.slack.com/archives/C5CDKU5DK/p1505812750000071
- [x] ag-forecastio - https://keboola.slack.com/archives/C6AHFV89W/p1505905062000028 Mame ready novou verzi, jenom jsme byli kously na tom kdo doda credentials. Updatnu aby uzivatel zadaval jeho token a releasneme. Udelam to ja.
- [x] ex-youtube - používá to pět projektů. bude potřeba nový extractor. Kdo ho napíše? Mohl by udělat někdo externí? Zároven bude asi potřeba posbírat co by to mělo u mět a k čemu se to používá
- [x] pigeon - Napsat ASAP novou verzi https://keboola.productboard.com/feature-board/6271-planning/features/38038 Myslím že tohle bysme mohli napsat my, tak jak to najlos vymyslel to bude jednoduchý.
- [x] restbox - nahradí ho S3 extractor + procesory. Zbývá podpora mulit-rows konfigurace - připravuje @ondrejhlavacek 
- [x] rt-lucky-guess - https://github.com/keboola/app-luckyguess je připravena nová verze ale ještě není public. tohle je na @odinuv 

Aktuální používání extractorů je vidět tady https://keboola.looker.com/dashboards/5 

## Speciální komponenty které by měly zmizet
- [x] table-importer - s největší pravděpodobností používá jenom pigeon, nedá se to ale moc ověřit. První bude teda potřeba zmigrovat pigeon a pak se uvidí jestli něco zbyde nebo ne.
- [x] oauth - zmigrovat komponenty které ho používají a pak se může vyhodit
  - [x] wr-dropbox - používá jenom jeden projekt (976), je to ale už v dockeru a udělat novou verzi z oauth-2 a migrací by neměl být problém https://github.com/keboola/dropbox-writer

- [x] timeout - vyhodíme, postará se o to @ErikZigo 

## Komponenty které zatím necháme tak jak jsou
Co s nima dál je nastřeleno tady https://github.com/keboola/connection/wiki/Infrastructure-&-Architecture-Roadmap#komponenty-docker-runner--syrup
- oauth-v2
- queue
- orchestrator
- docker
- transformation
- gooddata-writer
- provisioning

**Comment by Halama** [comment]
Udělal jsem skriptik který vypíše všechny syrup komponenty a počet jejich použití za posledních 30 dní:
```
➜  syrup-check php check.php
Components usage in last 30 days 
gooddata-writer - 47873
transformation - 20718
orchestrator - 19475
docker - 14081
pigeon - 4556
ex-google-drive - 4104
ex-db - 4045
wr-google-drive - 3881
restbox - 3210
ex-google-analytics - 3173
ag-geocoding - 1072
ex-salesforce - 994
ex-twitter - 500
ex-gooddata - 426
ex-fb-ads - 410
ex-facebook - 372
wr-db - 309
table-importer - 289
ex-zendesk - 281
shinyapps - 202
ex-youtube - 163
rt-lucky-guess - 141
ex-generic - 120
ex-adwords - 71
ex-magento - 60
ex-doubleclick - 48
ex-getstat - 43
ag-forecastio - 34
ex-instagram - 30
ex-appannie - 27
oauth - 0
oauth-v2 - 0
ex-linkdex - 0
ex-mandrill - 0
ex-sklik - 0
ex-currency - 0
ex-elasticsearch - 0
ex-marketo - 0
ex-telfa - 0
ex-google-bigquery - 0
provisioning - 0
rt-split - 0
sapi-importer - 0
timeout - 0
wr-elasticsearch - 0
queue - 0
```

**Comment by Halama** [comment]
ex-instagram a ex-appannie jsou taky na vypnuti, mel je v projektu jen kachna

**Comment by Halama** [comment]
+ `ex-generic`

**Comment by Halama** [comment]
Tyhle byly skryté, nikdo je nepoužíval, jdu je teď odstranit z provisioningu syrupu:
- wr-elasticsearch
- rt-split
- ex-telfa
- ex-marketo
- ex-elasticsearch
- ex-currency
- ex-sklik
- ex-linkdex

**Comment by Halama** [comment]
Komponenty výše odstraněny ze syrupu i connection.
Aktuálně to vypadá:
```
Components usage in last 30 days 
gooddata-writer - 47979
transformation - 20725
orchestrator - 19489
docker - 14114
pigeon - 4549
ex-google-drive - 4099
ex-db - 4043
wr-google-drive - 3891
restbox - 3205
ex-google-analytics - 3173
ag-geocoding - 1078
ex-salesforce - 997
ex-twitter - 499
ex-gooddata - 425
ex-fb-ads - 405
ex-facebook - 372
wr-db - 313
table-importer - 286
ex-zendesk - 281
shinyapps - 202
ex-youtube - 163
rt-lucky-guess - 140
ex-generic - 120
ex-adwords - 71
ex-magento - 60
ex-doubleclick - 48
ex-getstat - 43
ag-forecastio - 34
ex-instagram - 30
ex-appannie - 27
ex-mandrill - 0
ex-google-bigquery - 0
```

**Comment by ondrejhlavacek** [comment]
ex-salesforce a ex-facebook mám v productboardu, zkusil bych je nejdřív pomocí genericu a pak teprv jako samostatný komponenty

**Comment by Halama** [comment]
jo tehle postup plati pro vsechno:) Super ale je ze docker v poctu jobu uz je na  4. miste ...

**Comment by kacurez** [comment]
aha shit som zabudol ze syrup ma tiez index :), nedala by sa ta statistika(Components usage in last 30 days ) vytiahnut tiez z shared konfigu?

**Comment by Halama** [comment]
jo dala

**Comment by Halama** [comment]
jenom tam chybi ten seznam co je v syrupu https://syrup.keboola.com/ ale ten by vlastne asi sel stahnout genericem:)

**Comment by Halama** [comment]
to jsem vlastne jednou uz zkousel a ten format neni uplne idealni protoze to zalozi jeden radek a pro kazdou komponentu jeden sloupec, protoze to neni pole

**Comment by ondrejhlavacek** [comment]
stáhnout jako string a zpracovat ve snowflake :-)

**Comment by kacurez** [comment]
upravil som ten zoznam vyssie podla Martinovho, btw som zistil ze ex-facebook-ads/ex-fb-ads su rozdielne id na connection/syrup indexu.

**Comment by odinuv** [comment]
Orchestrator a Luckyguess chceme taky prepisovat do dockeru?

**Comment by Halama** [comment]
jo nektery extraktory jsou takhle blbe zaregistrovany, pak u nich v jobech nevidis jmeno apod.

**Comment by Halama** [comment]
@odinuv zatim asi ne, na ty jsem zapomnel

**Comment by Halama** [comment]
do luckyguessu teda vubec nevidim tak nevim jestli potrebuje byt jako komponenta nebo by bezel v dockeru

**Comment by Halama** [comment]
Smazano:
- Instagram
- App Annie
- Mandrill

**Comment by odinuv** [comment]
LG pouziva primy pristup k Redshiftu, takze ani moc nevim jak to do dockeru strcit

**Comment by Halama** [comment]
Aktualne:
```
Components usage in last 30 days 
gooddata-writer - 33785
transformation - 19840
docker - 18895
orchestrator - 15806
wr-google-drive - 4524
pigeon - 4458
ex-google-drive - 3952
restbox - 3387
ex-google-analytics - 3081
ex-db - 1640
ex-salesforce - 887
ex-zendesk - 803
ex-gooddata - 443
ex-fb-ads - 414
table-importer - 264
wr-db - 245
ex-facebook - 243
ex-youtube - 222
ex-twitter - 178
ag-forecastio - 76
ex-getstat - 52
rt-lucky-guess - 49
ag-geocoding - 36
shinyapps - 33
ex-magento - 30
ex-doubleclick - 7
ex-google-bigquery - 3
```

**Comment by Halama** [comment]
pro `ex-db` bude chtit nove nejak zaprudit z migraci, nebo rict termin kdy to zmigrujeme automaticky.

**Comment by Halama** [comment]
Update:
```
Components usage in last 30 days 
gooddata-writer - 31572
transformation - 18884
docker - 17473
orchestrator - 14444
pigeon - 4489
ex-google-drive - 3924
restbox - 3627
wr-google-drive - 3178
ex-google-analytics - 3039
ex-db - 1381
ex-salesforce - 609
ex-zendesk - 545
ex-fb-ads - 508
ex-gooddata - 469
wr-db - 272
table-importer - 264
ex-facebook - 254
ex-youtube - 237
ex-twitter - 135
ag-forecastio - 74
ag-geocoding - 58
rt-lucky-guess - 57
ex-getstat - 53
shinyapps - 52
ex-magento - 30
ex-doubleclick - 4
ex-google-bigquery - 3
```

**Comment by Halama** [comment]
Tady je transformace která vyplivne používání legacy komponent https://connection.keboola.com/admin/projects/258/transformations/bucket/301257118/transformation/301257187

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/30485694-82e4b3ce-9a2e-11e7-90ee-0d460e32be15.png)

**Comment by Halama** [comment]
Tři projekty používají stále starý importer který měl být vypnutý v prosinci 2016. http://status.keboola.com/new-storage-api-importer Přemýšlím jestli jim ještě zkusit dát vědět nebo to prostě vypnout?
![image](https://user-images.githubusercontent.com/903531/30535610-38b25d10-9c63-11e7-9d0b-c4aac1b137e9.png)

**Comment by odinuv** [comment]
jsem myslel, ze jsme vsem poslali tickety pres zendesk?

**Comment by Halama** [comment]
to byl synchronní export https://github.com/keboola/connection/issues/911#issuecomment-328489287 :) tohle jej ještě starší věc. Posílám jim to ted taky přes zendesk.

**Comment by odinuv** [comment]
jo importer, uz to vidim, jsem taky mimo

**Comment by Halama** [comment]
- 490, 1503 https://keboola.zendesk.com/agent/tickets/7338
- 1068 https://keboola.zendesk.com/agent/tickets/7339

**Comment by Halama** [comment]
Připravena čistka nepoužívaných deprecated syrup komponent, zítra nahodím:
- https://github.com/keboola/syrup-router/pull/63
- https://github.com/keboola/cookbook-keboola-syrup/pull/33

**Comment by Halama** [comment]
Odstraněny komponenty:
- shinyapps
- ex-google-bigquery
- ex-gooddata
- ex-google-analytics
- ag-geocoding 
- ex-db

**Comment by Halama** [comment]
Salesforce https://keboola.slack.com/archives/C02CGRFGU/p1505809520000362

**Comment by Halama** [comment]
Magento https://keboola.slack.com/archives/C02CGRFGU/p1505811865000346

**Comment by Halama** [comment]
Getstat + Magento https://keboolaglobal.slack.com/archives/C5CDKU5DK/p1505812750000071

**Comment by Halama** [comment]
Náš legacy Salesforce deprecated a nabízíme už jenom nový od HTNS:
![image](https://user-images.githubusercontent.com/903531/30586397-1babc332-9d30-11e7-8fd9-09b1bbbe96c6.png)

**Comment by Halama** [comment]
Magento taky tady https://keboola.zendesk.com/agent/tickets/7274

**Comment by Halama** [comment]
ex-gooddata se porad nabizi jako novy

**Comment by Halama** [comment]
ex-gooddata skrytý.

**Comment by Halama** [comment]
Magento které nabízíme je stará verze jedna, z nabídky jsem ho skryl. Extraktor pro aktuální verzi 2 připravuje Leo.
Staré Magento zatím musíme nechat běžet.

**Comment by Halama** [comment]
getstats API jsem nalinkoval tady https://github.com/keboola/getstat-extractor-bundle/tree/master uz umi json tak by mozna mohlo jit genericem, hodil jsem to vokurkovi.

**Comment by Halama** [comment]
Forecast.io se řeší tady https://keboola.productboard.com/feature-board/6271-planning/features/41744

**Comment by Halama** [comment]
Youtube - reporting ex https://github.com/blueskydigital/keboola-ex-youtube-reporting umi jenom neco. Stary pracuje s Data a Analytics API - bude potreba teda udelat novy.

**Comment by Halama** [comment]
Používání deprecated komponent po projektech https://keboola.looker.com/dashboards/5?Date=14%20days&Project%20ID=&filter_config=%7B%22Date%22:%5B%7B%22type%22:%22past%22,%22values%22:%5B%7B%22constant%22:%2214%22,%22unit%22:%22day%22%7D%5D,%22id%22:2%7D%5D,%22Project%20ID%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:5%7D%5D%7D

![image](https://user-images.githubusercontent.com/903531/30643891-dc6add8e-9e10-11e7-828c-e9b0b294a2a3.png)

**Comment by Halama** [comment]
Jde to ofiltrovat i na komponentu:
![image](https://user-images.githubusercontent.com/903531/30643964-19d59754-9e11-11e7-9e70-3b2a1c32bc36.png)

**Comment by Halama** [comment]
wr-db je ready na smazani, je v poslednim projektu kde od 29.8 konci chybou smaszane sys tabulky https://keboola.slack.com/archives/C02CGK5CL/p1505899383000296

**Comment by Halama** [comment]
Ještě jsem narazil že Tableau writer pracuje ze starým google drive deprecate writerem!
![image](https://user-images.githubusercontent.com/903531/30685383-051b7cd0-9eb5-11e7-943d-cbbf965b36ec.png)

**Comment by Halama** [comment]
`table-importer` s největší pravděpodobností používá jenom pigeon, nedá se to ale moc ověřit. První bude teda potřeba zmigrovat pigeon a pak se uvidí jestli něco zbyde nebo ne.

**Comment by Halama** [comment]
Starý `ouath` používají:
- `ex-adwords-v2`
- `ex-dropbox` 
- `keboola.wr-vizable`
- `wr-dropbox`

**Comment by Halama** [comment]
Přístupy na `oauth` https://insights.newrelic.com/accounts/218779/explorer/events?eventType=Transaction&filters=%255B%257B%2522key%2522%253A%2522appName%2522%252C%2522value%2522%253A%2522syrup%2522%257D%252C%257B%2522key%2522%253A%2522syrupComponent%2522%252C%2522value%2522%253A%2522oauth%2522%257D%255D&duration=604800000&facet=syrupComponent

**Comment by Halama** [comment]
https://insights.newrelic.com/accounts/218779/dashboards/396129

**Comment by Halama** [comment]
`keboola.wr-vizable` nefunguje z ui, chce to credentials z wr-dropboxu. Vyhodím ho z nabídky.

**Comment by Halama** [comment]
- [ ] Zkontrolovat v dev portalu jestli všechny appky appky co už mají novou verzi jsou označené jako deprecated

**Comment by ujovlado** [comment]
Az to budeme mat skontrolovane, mozeme z nich oznacit suffix `Deprecated` a do UI pripravit upravu, ktora to bude citat z toho flagu. (https://github.com/keboola/kbc-ui/issues/1062)

**Comment by Halama** [comment]
@kacurez připravil nový Dropbox writer https://github.com/keboola/dropbox-writer-v2

**Comment by Halama** [comment]
Při mazání komponenty ze syrupu  je taky potřeba odebrat podporu migrace (pokud ji má) https://github.com/keboola/config-migration-tool/commit/98afbb9fa529e46af542191bba2324994f94c574

**Comment by Halama** [comment]
Releasnutý nový drobpox writer a starý deprecovaný.

**Comment by Halama** [comment]
Použití starého sapi-importeru https://localhost:9001/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(project.id,project.name,token.id,token.name,message),index:'events-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'event:%22ext.sapi-importer.%22')),sort:!(created,desc))

**Comment by Halama** [comment]
sapi-importer pořád používají dva projekty, ticket tady https://keboola.zendesk.com/agent/tickets/7338

**Comment by Halama** [comment]
^ Zapadlo jim to a už to začínají řešit https://keboola.zendesk.com/agent/tickets/7431

**Comment by Halama** [comment]
Deprekoval jsem přes dev portal všechny appky které mají byt deprecated, tzn. mají správně nastavený deprecated flag.

**Comment by Halama** [comment]
Starej forecast.io deprekovanej. Releasnutej novej Dark sky weather extractor https://apps.keboola.com/apps/keboola.dark-sky-augmentation

**Comment by Halama** [comment]
Vypadá to že ex-getstat bude taky na vypnutí. Projekt 777 který ho používal je smazaný.
![image](https://user-images.githubusercontent.com/903531/33174625-19f74d16-d059-11e7-9ae5-1e2cbcc6fa5b.png)

**Comment by Halama** [comment]
Deprecoval jsem ho.

**Comment by Halama** [comment]
Jdu odstranit pár komponent https://github.com/keboola/syrup-router/pull/76

**Comment by Halama** [comment]
ex-google-drive taky ke smazání, je to v nějakém projektu kde to jenom háže chyby:
![image](https://user-images.githubusercontent.com/903531/33176650-12ec8ed0-d060-11e7-857c-09ff5e1b8433.png)

**Comment by Halama** [comment]
`wr-dropbox` který používal starý oauth už v posledním projektu vypnuli. `oauth` už by teda taky měl být ke smazání:
![image](https://user-images.githubusercontent.com/903531/33558076-51d9c4bc-d909-11e7-99fa-d6bff1c5b984.png)

**Comment by Halama** [comment]
^ `GET /oauth/credentials/ex-dropbox/267520630`!

**Comment by Halama** [comment]
Odebrány další tři komponenty https://github.com/keboola/syrup-router/pull/78/files
https://github.com/keboola/cookbook-keboola-syrup/pull/37/files
API přerolovány, worker stack updatnutý a roluju jednu instanci na vyzkoušení.

**Comment by Halama** [comment]
Odstraněný komponenty zaarchivovány na githubu

**Comment by ErikZigo** [comment]
Finalizuju testy orchestratoru, tak aby nepouzivali `timeout` komponentu. Nejspis zitra bude mozne `timeout` smazat

**Comment by ErikZigo** [comment]
Tak `timeout` se muze definitivne odebrat z komponent.
Testy orchestratoru ho uz k nicemu nepouzivaj a k nicemu jinymu to nebylo.

**Comment by Halama** [comment]
super v dalsi davce komponent ho dam pryc.

**Comment by Halama** [comment]
Nový youtube je releasnutý, starý deprecated

**Comment by Halama** [comment]
Novej pigeon taky připravenej, ted se delá na ui potom bude možné releasnouta  deprecovat/zmigrovat starý.

**Comment by JakubMatejka** [comment]
Magento v1 přepsaný, dal jsem jim (Ticket #354 v Keboola SG) cca měsíc na migraci, v půlce února se jim připomenu jak to vypadá

**Comment by Halama** [comment]
Další komponenty ke smazání:
- `ex-fb-ads`

**Comment by JakubMatejka** [comment]
`ex-magento` zmigrovaný, může se smazat

**Comment by JakubMatejka** [comment]
Takže zbývají
- `wr-google-drive`
- `ex-zendesk`
- `ex-salesforce`
- `restbox`
- `rt-lucky-guess`
- `table-importer`
?

**Comment by Halama** [comment]
`pigeon` už je taky ready k vyhození

**Comment by Halama** [comment]
Legacy komponenty k odstranění:
https://keboola.looker.com/dashboards/5
![image](https://user-images.githubusercontent.com/903531/39522787-9bf42162-4e13-11e8-88ba-701947d9ceff.png)

**Comment by Halama** [comment]
Smazány a archivovány:
 - pigeon
 - ex-fb-ads
 - ex-magento

Odebráno z provisioningu i receptů.
Updatnul jsem ASG api i workerů, API servery přerolovány.

Zapomněl jsem na `timeout` tak ten půjde s příští várkou.

**Comment by Halama** [comment]
Legacy komponenty https://keboola.looker.com/dashboards/7?Component=wr-google-drive,table-importer,ex-salesforce,ag-forecastio,ex-youtube,ex-zendesk&KBC%20Stack=&Date%20Range=6%20months&Project=&filter_config=%7B%22Component%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22wr-google-drive,table-importer,ex-salesforce,ag-forecastio,ex-youtube,ex-zendesk%22%7D,%7B%7D%5D,%22id%22:8%7D%5D,%22KBC%20Stack%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:9%7D%5D,%22Date%20Range%22:%5B%7B%22type%22:%22past%22,%22values%22:%5B%7B%22constant%22:%226%22,%22unit%22:%22mo%22%7D,%7B%7D%5D,%22id%22:10%7D%5D,%22Project%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:11%7D%5D%7D

**Comment by Halama** [comment]
Vypadá to že už se používají jenom v deseti projektech. `ex-zendesk` a `ex-youtube` už vůbec.

![image](https://user-images.githubusercontent.com/903531/45345550-f2f2d800-b5a6-11e8-886d-e232aaca479f.png)

**Comment by Halama** [comment]
Zatím tam nedávám restbox, ten byl deprecated poměrně nedávno. Vypínat se bude 1.11. http://status.keboola.com/restbox-component-deprecation-announcement

**Comment by ujovlado** [comment]
Podla https://github.com/keboola/docker-bundle/issues/52#issuecomment-348980736 je uz `wr-dropbox` k zmazaniu, stale mi vsak fici. Neostal tam len zabudnuty? Ked kukam na `wr-dropbox` cez looker, nevidim tam, ziadny job. T.j. uz by ho nemal pouzivat ani tde exporter, ak to spravne chapem (cc @kacurez).

**Comment by Halama** [comment]
Restbox včera vypnut https://github.com/keboola/restbox-bundle/pull/4 
Bude se moct potom odstranit s ostatními komponentami. Ještě bych ale nechal čas na smazání konfigurací.
Používání po vypnutí https://papertrailapp.com/events?q=%22Restbox%20was%20shut%20down%20on%20November%2012%22

**Comment by ujovlado** [comment]
Na ten wr-google-drive trosku zatlacim, je deprekovany vyse roka a v Decembri 2017 (!), sme mali migrovat konfiguracie automaticky.

Dotlacim ten datum deprekovania na Overview stranku, potom by sme mohli oznamit finalne vypnutie na 31.1.2019.

**Comment by Halama** [comment]
jo to zní dobře

**Comment by ondrejhlavacek** [comment]
Neoznámíme na stejný datum i vypnutí MySQL?

**Comment by Halama** [comment]
@ujovlado podařilo se ti dotlačit to deprekování na overview?

**Comment by Halama** [comment]
jo a to mysql bych tam dal taky.

**Comment by Halama** [comment]
a všechno ostatní co zbylo tady https://syrup.keboola.com/

**Comment by ujovlado** [comment]
> @ujovlado podařilo se ti dotlačit to deprekování na overview?

Ten PR na connection sme nasadili min. tyzden, potom uz som sa k tomu nedostal. Bude to tam urcite tento tyzden

**Comment by ujovlado** [comment]
> Ten PR na connection sme nasadili min. tyzden, potom uz som sa k tomu nedostal. Bude to tam urcite tento tyzden

bude to v priebehu dneska: https://github.com/keboola/kbc-ui/pull/2493 ;)

**Comment by Halama** [comment]
super, s tím teda nahodíš pak i ten status?

**Comment by ujovlado** [comment]
Status napisem, hned ako fixneme https://github.com/keboola/config-migration-tool/issues/27

**Comment by ujovlado** [comment]
Ak spravne kukam tak `rt-lucky-guess` bol za poslednych 60 dni spusteny raz - `13.11.2018`. Nevypneme to rovno? Vyhodil by som som to z UI a potom rovno aj zo syrup-router.

**Comment by Halama** [comment]
jo vyhodil bych to

**Comment by ujovlado** [comment]
youtube, zendesk a rt-lucky-guess: https://github.com/keboola/syrup-router/pull/196, https://github.com/keboola/cookbook-keboola-syrup/pull/56

**Comment by Halama** [comment]
@ujovlado připravíš prosím ten status? ty komponenty se můžou fyzicky odmazat až potom i ty starší.

**Comment by Halama** [comment]
To už vypadá docela dobře. Ten `table-importer` je teda podezřelej:)
![image](https://user-images.githubusercontent.com/903531/50677919-a8391800-0ffc-11e9-8e86-6749c486557e.png)

**Comment by Halama** [comment]
Ten `table-importer` je jenom na jednom projektu naštěstí https://keboola.looker.com/dashboards/7?Component=table-importer&KBC%20Stack=&Date%20Range=2%20months&Project=&filter_config=%7B%22Component%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22table-importer%22%7D,%7B%7D%5D,%22id%22:8%7D%5D,%22KBC%20Stack%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:9%7D%5D,%22Date%20Range%22:%5B%7B%22type%22:%22past%22,%22values%22:%5B%7B%22constant%22:%222%22,%22unit%22:%22mo%22%7D,%7B%7D%5D,%22id%22:10%7D%5D,%22Project%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:11%7D%5D,%22Job%20Status%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:5%7D%5D%7D&Job%20Status=

![image](https://user-images.githubusercontent.com/903531/50736448-1bd65300-11be-11e9-83b8-767cc1b3414a.png)

**Comment by ujovlado** [comment]
K tomu table-importer som im napisal do slacku - mame shared channel. ;)

**Comment by ujovlado** [comment]
^ robi to stary Pigeon Importer.

**Comment by JakubMatejka** [comment]
OMG, ten má být od dubna vypnutej

**Comment by ujovlado** [comment]
jo, dopisal som im to pred chvilkou aj na Slack. Myslim, ze s kludom to mozeme vypnut toho 31.1.2019. (ak to dovtedy neporiesia, zacne im to failovat, a opravia to)

**Comment by ujovlado** [comment]
Po mergi/nasadeni https://github.com/keboola/syrup-router/pull/210 a https://github.com/keboola/cookbook-keboola-syrup/pull/58 je toto issue done.

**Comment by ujovlado** [comment]
Takze toto mozem asi prehlasit za hotove, mame uz len core syrup komponenty!  🎉 🎉 🎉
