### ISSUE TITLE
Filter sensitive data out of logs

### ISSUE THREAD

**Issue by kachnitel** [keboola/docker-bundle#55]
We should prevent sending content of encrypted values from config to the output and sending them to KBC events.
I'm not entirely sure if it should be docker bundle's responsibility, though somehow it would make sense for the bundle to filter it out, as it does the decryption and knows the value that must not be made visible to user.
However, if docker bundle handles the job, then let's say the application prints out a value of `Basic` auth, and docker only provides an encrypted password, there's no reasonable way for docker bundle to do this. That particular case should clearly be prevented by the application.
We might simply do a plaintext search for the encrypted string on the output buffer that's being sent out to KBC (or even PT?), but there's a potential of catching a string that was both decrypted AND legitimately printed out by the application elsewhere (say a header `Authorization: Token Authorization`)

**Comment by odinuv** [comment]
https://keboola.productboard.com/inbox/notes/53465

**Comment by odinuv** [comment]
Related issues https://github.com/keboola/generic-extractor/issues/12 https://github.com/keboola/generic-extractor/issues/8 and https://keboola.slack.com/archives/C03JBGZDG/p1509716429000084

**Comment by odinuv** [comment]
fixed in 79d111cc81132a1661f662368479fc3214f3cbda
