### ISSUE TITLE
Sync actions don't work with default bucket

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#57]
Ked pouzivam `default_bucket`, volanie sync action skonci na:
https://github.com/keboola/docker-bundle/blob/89761b5/Docker/Executor.php#L390

![screenshot_2016-05-17_17-49-18](https://cloud.githubusercontent.com/assets/419849/15329102/b8f3c9ce-1c57-11e6-9a0c-cc7f786234f1.png)

**Comment by ondrejhlavacek** [comment]
fixed by adcbb32df0e6e407d69d9335b6acc9f926585586
