### ISSUE TITLE
input table manifest

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#62]
přidat `export_options`, kam se dá nastavení exportu (fitry, sloupce) a do dokumentace napsat, že manifest se týká původního souboru!

**Comment by odinuv** [comment]
@ondrejhlavacek - jakej smysl ma mit, tam `columns` puvodni tabulky? podle me by se columns mely proste zmenit na ty exportovany, takhle to navic zavani nejakym leakem dat ke komponente - columns asi nic hyper-sensitive obsahovat nebude, ale columns_metada uz muze a taky to tam nema co delat kdyz si uzivatel zvolil, ze to nechce exportovat. 

tzn. udelal bych to tak, ze se columns a columns_metadata zmeni na skutecne exportovane sloupce

**Comment by ondrejhlavacek** [comment]
ok! souhlas.

**Comment by Halama** [comment]
We writeru bysme zatim udelali fix kdy to nebude  s tema `columns` manifestu pracovat ale bude pracovat jenom s `storage.input.tables[].columns` viz. https://github.com/keboola/db-writer-redshift/pull/12#pullrequestreview-92492533

**Comment by Halama** [comment]
Nebo bude lepší počkat na fix v docker runneru?

**Comment by odinuv** [comment]
zrovna se do toho poustim (teda chtel jsem vcera, ale odlozil jsem to kvuli tomu RS - ten je na to zrovna potreba)

**Comment by Halama** [comment]
super v tom pripade asi pockame. je to asi lepsi to cist z toho manifestu nez `storage.input.tables[].columns`? - propaguje se to vubec co `config.json` ?

**Comment by odinuv** [comment]
co jestli se propaguje do config.json ?

**Comment by odinuv** [comment]
s tim poradim je to teda tak, ze exportoptions=columns v sapi klientovi zaridi, ze fyzicky vyexportovany sloupce budou tak jak jsou uvedeny v tom exportoptions, cili v tom stejnym poradi by mely byt v manifestu, je tak?

**Comment by odinuv** [comment]
no koukam, ze podobnej problem je jeste s `data_size_bytes` a `rows_count`, ktery se taky tahaji z puvodni tabulky a ne z exportu

**Comment by Halama** [comment]
to propagaci do `config.json`. Jsem myslel jestli tam clovek dostane i tu sekci `storage` celou tak jak ji ma v configu, ale asi jo ne?

**Comment by Halama** [comment]
Jinak potvrzuju ze je to tak ze do manifestu jako columns by melo prijit to co si poslal do export options jako columns.
U tech `data_size_bytes` a `rows_count` by to taky bylo dobry. Koukam ze se toho vlastne tyka tohle issue https://github.com/keboola/connection/issues/1084

**Comment by odinuv** [comment]
jo, to je ta stejna vec

**Comment by Halama** [comment]
myslim ze bych to na SAPI mohl teda udelat

**Comment by odinuv** [comment]
aha, ja mel pocit, ze uz jsem to nekde videl

**Comment by ondrejhlavacek** [comment]
Můžem `data_size_bytes` a `rows_count` deprecovat a uvést v dokumentaci, že se týkají původních souborů.

**Comment by Halama** [comment]
To by možná stačilo, nenapadá mě k čemu by to autor komponenty potřeboval.

**Comment by Halama** [comment]
Potom se můžou naimplementovat jenom ty `columns` a je to.

**Comment by ondrejhlavacek** [comment]
Jj, hodil jsem to tam bez rozmyslu o skutečné potřebě.

**Comment by Halama** [comment]
Ono to vlastne asi plati pro vetsinu poli v tom manifestu https://developers.keboola.com/extend/common-interface/manifest-files/#tables je to info o SAPI tabulce.

**Comment by odinuv** [comment]
id -> identifikator, zustava
uri -> identifikator, zustava
name -> nevim jestli je to k necemu dobry
primary_key -> jasny, zustava
indexed_columns -> dal bych dopredele hned
created -> nechal bych
last_change_date -> nechal bych
last_import_date -> nechal bych
rows_count -> deprecovat
data_size_bytes -> deprecovat
is_alias -> nevim, jestli po tom nekomu neco je
columns -> jasny, zustava
attributes -> je trosku deprecated, ale jeste ne uplne
metadata -> jasny, zustava
column_metadata -> jasny, zustava

**Comment by Halama** [comment]
blby je ze pri vyhazovani tech attributu vubec netusime jestli s tim nekdo pracuje. To samy ted bude cekat sapi pri vyhozeni `indexedColumns` a tam si rikam ze to proste v odpovedich asi nechame i kdyz prazdne.

**Comment by odinuv** [comment]
no tak mame asi 3 moznosti: 
- muzem napsat na status, ze to deprecujem a at si to vsichni opravi, (coz stejne nejspis nikdo neudela) a pak to po case vyhodit
- nebo to tam nechat s prazdnyma hodnotama a pockat kde se co vysere a pak to pocase vyhodit
- nebo to vymazat uplne a pockat kde se co vysere

**Comment by ondrejhlavacek** [comment]
Zkombinoval bych 1+2.

**Comment by Halama** [comment]
Zase me napada jestli to neni zbytecny pruzeni, jestli to tam nemuzeme proste nechat, jenom napsat ze se to vztahuje k puvodni tabulce?

**Comment by ondrejhlavacek** [comment]
Nebo tak, původně mě napadlo k tomu v dokumentaci napsat, že to je deprecated. Pokud v input mappingu budou nějaký filtry, tak to v manifestu není řečený a může to akorát mást.

**Comment by odinuv** [comment]
Zbavil bych se toho, protoze pro to nemame pouziti a akorat se na tom nekdy nekde zbytecne zajebem

**Comment by odinuv** [comment]
pokracovani v https://github.com/keboola/input-mapping/pull/14

**Comment by odinuv** [comment]
sloupce a poradi spravene v f962df6ce9bbea9d5505fb2acaab1c0219ab1a22
