### ISSUE TITLE
stderr vidno v logoch

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#75]
Vyzera, ze ten stderr sa tam ukaze napriek tomu, ze by tam malo byt len application error.

![screenshot_2016-09-09_12-55-11](https://cloud.githubusercontent.com/assets/419849/18385949/e23858b8-7693-11e6-9c3a-1eaf082f676c.png)

^v tom cervenom by teda malo byt len "Application error" a zvysok by som si asi chcel pozriet az v detaile tej exception.

^to ze je to aj v stdout je myslim chyba toho image (takze netreba riesit).

**Comment by ujovlado** [comment]
cc @ondrejhlavacek (bavili sme sa o tom)

**Comment by ondrejhlavacek** [comment]
- stderr se bude bufferovat a pak se pošle ven, když exit 1, nebo do logu, když exit > 1
- pokud nekdo bude chtít poslat jinej log, tak přes gelf

**Comment by odinuv** [comment]
podle me to je wontfix, my nemame jak zjistit, ze zrovna ta zprava se nema uzivateli zobrazit

**Comment by ondrejhlavacek** [comment]
STDERR se může celou dobu bufferovat (fido vyhazovat pro malej buffer) a
podle exit kódu pak s tim naložit.

**Comment by ujovlado** [comment]
skusim sa na to kuknut

**Comment by odinuv** [comment]
Tak jestli to spravne chapu, tak staci vyhodit tenhle radek https://github.com/keboola/docker-bundle/blob/master/Docker/Container.php#L194

**Comment by ondrejhlavacek** [comment]
No, tady to bude potřeba uložit do nějakýho vlastního bufferu a na konci běhu rozhodnout, zda to poslat do eventy, nebo do aplikačního logu (při app exception)

**Comment by ujovlado** [comment]
Alebo si mozeme povedat, ze do STDERR sa ma zapisovat len na konci  a bola by tam len posledna message.

**Comment by odinuv** [comment]
@ondrejhlavacek No ja myslim, ze nebude, potom bude tady https://github.com/keboola/docker-bundle/blob/master/Docker/Container.php#L298 vystup celyho procesu, ne jen posledni zprava ne?

**Comment by odinuv** [comment]
@ujovlado no tak to urcite ne, posledni zprava je vetsinou na pikatchu

**Comment by ondrejhlavacek** [comment]
@odinuv no hele, snad jo!

**Comment by odinuv** [comment]
ref https://github.com/keboola/docker-bundle/commit/43ab12d338303705d6c00df24f6a6817cddd7401

**Comment by odinuv** [comment]
finished in 125c7e2c097a4e5558e34dc310fd39c53a1c97a0
