### ISSUE TITLE
default_bucket_stage error

### ISSUE THREAD

**Issue by ujovlado** [keboola/docker-bundle#76]
Looks like run function expecting `default_bucket_stage` option, otherwise it ends with error.

We should handle it in more proper way or make this configuration variable required/default. For example `in` for writers and `out` for extractors?

Sample:
`docker-af3885faf24566e54353b31e36ee86f3`

**Comment by odinuv** [comment]
Fixed by ae7c3580d47e04724bcd2365db5e410ca6e185eb
