### ISSUE TITLE
Processors configuration in UI configuration (JSON schemas)

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#81]
Trochu jsem narazil v S3 extraktoru, který má sám o sobě hrozně jednoduchou konfiguraci a šel by použít s JSON schématem, že nedokážu správně zkonfigurovat procesory.

Základní konfigurace je cca takhe (schválně píšu ve vizuálu UI)

```
Output mapping:
data.csv -> SAPI 

Parameters:
__________ AWS Access Key
__________ AWS Secret Key ID
__________ Key
__________ Bucket
```

Což vygeneruje konfiguraci

```
{
  "parameters": {
    "accessKeyId": "",
    "#secretAccessKey": "",
    "bucket": "",
    "key": ""
  },
  "storage": {
    "output": {
      "tables": [
        {
          "source": "data.csv",
          "destination": ""
        }
      ]
    }
  }
}
```

A teď bych chtěl zapojit procesor třeba unzip (soubor je zipovanej)

```
Output mapping:
data.csv -> SAPI 

Parameters:
__________ AWS Access Key
__________ AWS Secret Key ID
__________ Key
__________ Bucket
[ ]        Unzip
```

A z toho bych potřeboval vygenerovat konfiguraci

```
{
  "parameters": {
    "accessKeyId": "",
    "#secretAccessKey": "",
    "bucket": "",
    "key": ""
  },
  "storage": {
    "output": {
      "tables": [
        {
          "source": "data.csv",
          "destination": "in.c-main.s3"
        }
      ]
    }
  },
  "processors": {
    "after": [
      {
        "definition": {
          "component": "keboola.processor.unziper"
        }
      }
    ]
  }
}
```

Problém je v tom, že JSON Schéma ukládá do `parameters`, zatímco cokoliv, co dělaj procesory, je v `processors`. Ty procesory můžou bejt
a) zapínatelný checkboxem (unzipování)
b) defaultní (move-files)
c) zapínatelný/konfigurovatelný hodnotou (iconv)

Moc nevím, co s tím, abychom procesory nevyřadili JSON schéma.

Generické UI extraktorů bude mít asi vlastní sekci `processors`, ve kterých si je bude možno zapínat dle libosti a budou konfigurovatelný přes JSON schémata (každý procesor bude mít vlastní konfigurační JSON schéma), ale pro takovýhle simple komponenty je skoro škoda vytvářet custom UI... Nápady?

**Comment by odinuv** [comment]
Bych to řešil tak, že se půjde v konfiguraci procesoru odkázat do sekce parameters, např takhle:

```
{
    'storage': ...,
    'parametrs': {
        'awsKey': 'foobar',
        '#awsSecret': 'bazbar',
        'sourceEncoding': 'CP1250',
        'unzip': true
    },
    'processors': {
        'after': [
            {
                'definition': {'component' => 'keboola.processor.unzipper'},
                'enabled': @parameters.unzip                
            },
            {
                'definition': {'component' => 'keboola.processor.iconv'},
                'parameters': {'source_encoding' => '@parameters.sourceEncoding'}
            }
        ]
    }
}
```

**Comment by odinuv** [comment]
ale to vyžaduje ještě jednu úpravu a to, že půjde sekci `processor` nastavit i v definici komponenty (mimo jiné i proto, aby šly udělat defaultní procesory). A s tím souvisí to, že pak musíme rozhodnout jak se to bude přetěžovat.

**Comment by ondrejhlavacek** [comment]
to by se právě mohlo udělat v UI Options komponenty a byla by to UI záležitost, nikoliv komponenty

**Comment by odinuv** [comment]
jakoze by v definici komponenty bylo UI options nastaveni procesoru, ktere ta komponenta pouziva a UI by potom vygenerovalo sekci `processors` do konfigurace komponenty? co tim ziskame? UI je to prece burt (pokud tam bude mit json schema)

**Comment by ondrejhlavacek** [comment]
Jestli to chápu dobře, tak kdyby byla definice procesorů uložená v definici komponenty, tak by se znovu neukládala do konfigurace?

**Comment by odinuv** [comment]
No to prave uplne nevim:

- bud by to mohlo fungovat tak, ze pokud bude zadany `processors` v definici komponenty, tak nepujde zadat v konfiguraci (nebo se bude ignorovat) 

- nebo (a to se me asi libi vic), by `processor` v konfiguraci komponenty pretizilo `processors` v definici komponenty, pricemz to pretizeni bude uplny a jednoduchy (zadny mergovani nebo nejaky ptakoviny, proste pokud to tam bude, tak to 'prepise' to, co je v definici)

**Comment by ondrejhlavacek** [comment]
mně se to na dvou místech moc nelíbí, zase nějaký mergování, nejasnosti při pohledu do konfigurace ... :-(

**Comment by odinuv** [comment]
No tak me to zas tak nejasny neprijde, ale mohlo by se to resolvnout pri ukladani konfigurace, to ale zase zpusobi zabetonovani definice do konfigurace, takze se pak bude blbe menit.

A jak bys teda resil ty defaultni procesory?

**Comment by ondrejhlavacek** [comment]
Co bys na tom měnil? Buď je konfigurace funkční a nepotřebuješ jí měnit (a už vůbec jí nepotřebujeme měnit my) a nebo není funkční a uživatel jí bude měnit sám a nebo nám reportovat bug.

Pokud se změní chování komponenty tak, že bude pro všechny existující komponenty vyžadovat nějakej novej defaultní procesor, tak to je špatně napsaná komponenta imho. A pokud budeš potřebovat např změnit major verzi procesoru a ten nebude zpětně kompatibilní, tak se udělá nová komponenta procesoru a nový konfigurace budou s ní (a starý furt pojedou).

**Comment by odinuv** [comment]
No myslel jsem nejaka zmena v definici processoru, jenze ted je tam stejne jen odkaz na zaregistrovanou komponentu, takze asi jediny, co by se na tom kdy mohlo menit by bylo to, ze kdyz bysme umoznovali spoustet konkretni verze komponent (nenapada me, co jinyho by se dalo do definice komponenty pridat), tak by se to tam zadratovalo, ale nevim jestli to neni prilis hypoteticky.

**Comment by odinuv** [comment]
no takze, kdyby to bylo jak navrhujes - komponenta by mela seznam defaultnich procesoru, UI by je nacetlo a ulozilo ty, ktere uzivatel povoli do konfigurace.  Timpadem nebude potreba `enbled` atribut a zapinani/vypinani procesoru.

Co s temi parametry ? Pokud tam bude jedno schema - coz asi budem nekdy potreboavat, tak je musime mit vsechny v `params`, pokud tam bude vic schemat (coz asi taky budem nekdy potrebovat), tak je naopak budeme mit rozhazeny

**Comment by ondrejhlavacek** [comment]
Tyjo, jsem z toho nějakej zamotanej. Dáme HO/Slack call?

**Comment by ondrejhlavacek** [comment]
Pro S3: custom UI
Pro FTP extraktor: v UI Options zadefinovat (pole objektů) procesory, který je možný v komponentě použít. komponenta bude mít json schéma a pod tím bude v UI zobrazený dostupný procesory (ty budou mít taky JSON schéma)

**Comment by ondrejhlavacek** [comment]
Konfigurace FTP extraktoru bude čistá - tj budou tam parameters a processors a ty nebudou mezi sebou mít vazbu. Celé to bude řešit UI přes definici povolených procesorů v UI Options.

**Comment by odinuv** [comment]
@ondrejhlavacek neni tohle uz uplne obsolete?

**Comment by ondrejhlavacek** [comment]
uplně ne, ale uzavřel bych to, nějaký +- funkční řešení máme, nechal bych to chvíli bejt a pak se na to podíval čerstvejma očima. dík za ping
