### ISSUE TITLE
Primary Key in Output Mapping

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#82]
https://github.com/keboola/kbc-ui/issues/681

**Comment by Halama** [comment]
https://keboola.zendesk.com/agent/tickets/6071

Stejný problém u komponenty. V konfiguraci je nastvený PK ale tabulka ho z nějakého důvodu nastavený nemá. Docker-runner to ale zřejmě narozdíl od transfromací nekontroluje a vše prochází a díky tomu se data duplikují.

**Comment by ondrejhlavacek** [comment]
Tady je na to search - všechny warningy je potřeba fixnout, než můžeme zavést striktní kontrolu, jinak to lidem popadá. 

https://papertrailapp.com/searches/14566533

**Comment by ondrejhlavacek** [comment]
Možný neagresivní řešení - https://github.com/keboola/kbc-ui/issues/681#issuecomment-276352114

**Comment by odinuv** [comment]
finished in 6480a4f96aa117577ee4421d598f9f628168420d
