### ISSUE TITLE
Docker image temp folder

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#85]
na docker workeru došlo místo - docker stahoval nějaký tempy do `/var/lib/docker/tmp`

```
[root@kbc-vpc-syrup-docker-worker-i-b23562a4 tmp]# pwd
/var/lib/docker/tmp
[root@kbc-vpc-syrup-docker-worker-i-b23562a4 tmp]# ls -la
total 54212
drwx------ 2 root root     4096 Oct 24 03:06 .
drwx--x--x 9 root root     4096 Sep 29 06:40 ..
-rw------- 1 root root 55498841 Sep 30 00:01 GetImageBlob483203690
[root@kbc-vpc-syrup-docker-worker-i-b23562a4 tmp]# df 
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda1       8123812 8068600         0 100% /
devtmpfs        16466992     124  16466868   1% /dev
tmpfs           16475568       0  16475568   0% /dev/shm
/dev/md0       104798208 2526728 102271480   3% /tmp
```

jdu nahodit novej worker a pokusit se zastavit vybírání novejch jobů na tomhle workeru

ve spot fleetu jsem zvedl počet instancí o 1 

dal jsem return do queue:receive commandu

```
[root@kbc-vpc-syrup-docker-worker-i-b23562a4 Command]# pwd
/www/syrup-router/components/queue/current/Command
[root@kbc-vpc-syrup-docker-worker-i-b23562a4 Command]# git diff
diff --git a/Command/ReceiveCommand.php b/Command/ReceiveCommand.php
index b9d6533..471b45e 100644
--- a/Command/ReceiveCommand.php
+++ b/Command/ReceiveCommand.php
@@ -84,6 +84,7 @@ class ReceiveCommand extends ContainerAwareCommand

     protected function execute(InputInterface $input, OutputInterface $output)
     {
+        return;
         $queueId = $queueId = $input->getArgument('queueId');

         if (is_null($queueId)) {
[root@kbc-vpc-syrup-docker-worker-i-b23562a4 Command]# 
```

a nechávám instanci `i-b23562a4` zapnutou pro debug.

**Comment by odinuv** [comment]
Generic tedka nekolikrat zhavaroval na tom, ze mu doslo misto v tempu:
"output": "[2018-03-12 03:00:11] logger.WARNING: Using legacy JSON parser, because it is in configuration state. [] []\n[2018-03-12 03:32:24] logger.ERROR: Cannot open file \/tmp\/ex-parser-data\/run-5aa5f1cd800025.19839700\/5aa5f4b204f46-taggings {\

https://papertrailapp.com/groups/170211/events?focus=909695568039792690&selected=909695568039792690

napr jobid: 365622930

stalo se to asi 10x a nezda se, ze by se stalo cokoliv jinyho, nez ze to proste nemohlo zapsat do tempu a chciplo to

**Comment by ondrejhlavacek** [comment]
tohle jsem našel v newrelicu

![image](https://user-images.githubusercontent.com/497675/37329024-6b1aeb46-269c-11e8-9c73-636468036185.png)

jdu to ještě chvíli zkoumat

**Comment by ondrejhlavacek** [comment]
tak ještě pár screenu z NR

![image](https://user-images.githubusercontent.com/497675/37329695-09bc6a0c-269f-11e8-8c6f-6de06c805d08.png)

![image](https://user-images.githubusercontent.com/497675/37330071-308372ce-26a0-11e8-9354-38b746ef7021.png)

podle PIDu ani ničeho dalšího se mi to nedaří dohledat, jediný vodítko zatím mám container image `b3843e87469fe623b43f2c31278a88a725876e4581951e8849e37e806e03d2fa`

**Comment by ondrejhlavacek** [comment]
```
# docker images | grep b3843e
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/ex-generic-v2                             3.4.0               b3843e87469f        2 months ago        430 MB
```

**Comment by ondrejhlavacek** [comment]
takže se ten kontejner musí nějak zacyklit a začít plivat nějaký nesmysly

**Comment by odinuv** [comment]
ne nezacykli se, oni tam maji proste takovou konfiguraci, ktera stahne asi 10GB dat a generic to sype nejdriv do tempu az potom to procesuje a uklada do /data/
dal jsem to sem proto, ze to neudelalo nic jinyho, nez ze generic chcipl -> coz mi prijde dobre

**Comment by ondrejhlavacek** [comment]
aha, tak to jsem za cpt obvious teda 🤦‍♂️

**Comment by Halama** [comment]
Ale asi to byl internal error u toho genericu ne?

**Comment by odinuv** [comment]
jo

**Comment by odinuv** [comment]
/tmp/ uz se od 66713cbef5517bcd148cf8f5f4f7601f54f0b869 mountuje
