### ISSUE TITLE
Failed to remove files from /data/tde-files

### ISSUE THREAD

**Issue by kacurez** [keboola/docker-bundle#87]
tde-exporter po novom generuje tde subory do zvlastnej zlozky /data/tde-files. Po starom ich generoval do zlozky /tde-files kde je len 10GB volny disk. 
Vsetko prebehne ok ale nakonci ked docker-runner cisti zlozku /data tak spadne s hlaskou:
`Failed to remove file \"\/tmp\/docker\/run-5818d548182f87.75572486\/data\/tde-files\/in.c_test._pokus.tde.manifest\"`
viac tu:
https://keboola.slack.com/archives/docker-notifications/p1478022570000096

novu verziu tde-exporteru som teda rollbackoval a nechavam to po starom dokym so toto nesolvne.

**Comment by odinuv** [comment]
known, v adresari /data/ si nemas vytvaret zadne dalsi podadresare, maji blbe permissions a nejdou potom smazat

**Comment by ondrejhlavacek** [comment]
přesně jak říká @odinuv, docker kontejner tam vyrobí adresáře pod rootem a ty pak docker runner (user deploy) nemá jak smazat. v /data/* nikdy nevytvářet žádný adresáře ani podadresáře. je to chyba v dockeru, ale zatím není fixnutá.

**Comment by ondrejhlavacek** [comment]
pardon, nechávám otevřený, ať se na to nezapomene, ale brzo to fixnutý určitě nebude, je potřeba upravit tde-exporter, ať si ukládá dočasný data do /tmp

**Comment by kacurez** [comment]
nakoniec som to vyriesil tak ze tde subory sa generuju do `/data/out/files` ktora sa inak vobec nepouziva a na konci obsah tejto zlozky zmaze. 
zamna to mozme zavriet.

**Comment by ondrejhlavacek** [comment]
A proč se to negeneruje do /tmp?

**Comment by odinuv** [comment]
protoze to ma 50gb

**Comment by ondrejhlavacek** [comment]
fixed by #97
