### ISSUE TITLE
OAuth integration - hardcoded syrup URL

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#90]
Používá verzi oauth v2 klienta kterému není možné nastavit url oauth bundle.
https://github.com/keboola/docker-bundle/blob/626676c18c6385bd7862f24e49e355165831bd19/Service/Runner.php#L99

## Fix: 
 - Release nového oauth klienta https://github.com/keboola/oauth-v2-php-client/blob/master/src/Common.php kterému půjde nastavit `apiUrl`. Defaultní `https://syrup.keboola.com/oauth-v2/` se odstraní - nově bude zadání URL povinné - major release

- Update docker bundle na nového oauth klienta. Adresa oauth bundle bude v `parameters.yml` docker runneru.

**Comment by Halama** [comment]
ukázka chyby: https://papertrailapp.com/events?q=docker-f9799c121e1486ebced5a621e52e04b7

**Comment by odinuv** [comment]
tak nejdriv by se mel pridat ten parameter do docker runner a poslat do ctoru, aby to pak slo hladce updatnout

**Comment by Halama** [comment]
hladky update neni problem staci ho hodit do tech parametru

**Comment by Halama** [comment]
pripravim release toho klienta

**Comment by Halama** [comment]
Oauth client 2.0.0 releasnutej https://github.com/keboola/oauth-v2-php-client

**Comment by ondrejhlavacek** [comment]
No a nebylo by lepší URL přebírat se seznamu komponent? `keboola.oauth-v2` tam je, parameters by se vůbec nemusely upravovat.

**Comment by Halama** [comment]
no prave bych radsi aby to stejne jako je v parameters url queue tak tam bylo i url oauth bundle.

**Comment by Halama** [comment]
takhle by se nekde musel zavolat index komponent z nej to sosnout atd, to muze zpomalit sync akci atd. Pridat to do parametru neni problem.

**Comment by ondrejhlavacek** [comment]
Chtělo by se mi říct, že i queue se může načíst ze seznamu komponent, bude to navíc furt jenom jeden api call. Sync akce stějně chvilku trvaj, líbí se mi na tom ta flexibilita. Ale parametry jsou taky v pohodě.

**Comment by Halama** [comment]
no jak myslis jestli to nic nezpomali. Hlavne aby se to nevolalo treba vickrat v ramci jednoho api callu.

**Comment by ondrejhlavacek** [comment]
Hrabu se v tom a musel bych zase jít do Syrupu a vymejšlet, jak tam cachovat seznam komponent. No, na to teďka asi prdím, ty parametry budou nejjednodušší.

**Comment by ondrejhlavacek** [comment]
fixed by 16e48aa4ac38572b5f39ecacf2a030a8781840ae
