### ISSUE TITLE
KBC_URL to env variable

### ISSUE THREAD

**Issue by Halama** [keboola/docker-bundle#91]
Je to důležité pro kompoenty které vyžadují SAPI token tzn. komunikují ze SAPI https://developers.keboola.com/extend/common-interface/environment/

Takže docker runner by do env `KBC_URL` měl injectnout storage url z konfigruace.

**Comment by odinuv** [comment]
Fixed in 88c56d06c07091f8780153b9a01b88ad8b7129b2
