### ISSUE TITLE
KBC::EncryptedStack

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#92]
Aby Docker Runner mohl mít pro každej region vlastní šifrovací klíč, je potřeba vyřešit šifrování definic komponent. Konfigurace jsou v pohodě, ty nejsou mezi projektama, komponentama ani regionama přenosný. 

Současný definice maj např
```
{
  "#password": "KBC::Encrypted==..."
}
```

Vytvoří se novej CryptoWrapper, např `EncryptedStack`, kterej bude umožňovat uložit víc hodnot, ze kterých se rozšifruje jen ta, co odpovídá současnýmu stacku. Např
```
{
  "#password": "KBC::EncryptedStack==[connection-us-east-1]{encrypted}[connection-eu-west-1]{encrypted}"
}
```

`connection-us-east-1` bude v parameters uložený jako `KeboolaStack` a bude pro každou instanci KBC unikátní. 

Jediný, co se bude muset udělat je, že při povolení komponenty do novýho stacku bude potřeba poslat současnej celej encrypted string a nezašifrovanou hodnotu a Docker Runner API na daným stacku přidá další encrypted část stringu.

**Comment by odinuv** [comment]
Nebo muzeme udelat wrapper KBC::EncryptedV2, 

V definici komponenty bude treba:

```
"#password": "KBC::EncryptedV2==..."
```

po rosifrovani z toho vznikne:

```
{
	"component": null,
	"project": null,
	"payload": [
		"connection-us-east-1": "KBC::Encrypted==..."
		"connection-eu-west-1": "KBC::Encrypted==..."
	]
}
```

Overi se, ze v payloadu je aktualni region, pokud ano KBC::Encrypted== se rozsifruje soucasnym wrapperem s klicem, ktery ma docker-bundle (kazdy stack bude mit svuj). Pokud
v payloadu neni aktualni region vyhodi vyjimku (klic nelze rozsifrovat v danem regionu).

Pro konfiguraci komponenty by to vypadalo tak, ze:

```
"#password": "KBC::EncryptedV2==..."
```

po rosifrovani z toho vznikne:

```
{
	"component: "keboola.ex-mysql",
	"project": "1234",
	"payload": [
		"connection-us-east-1": "KBC::Encrypted==..."
	]
}
```

Overi se, ze v payloadu je aktualni region, pokud v payloadu neni aktualni region vyhodi vyjimku (klic nelze rozsifrovat v danem regionu) - to znamena, ze sifrovanou hodnotu v projektu nepujede prenest mezi regiony. 
Overi se, ze 'keboola.ex-mysql' je aktualne spoustena komponenta; pokud ne, vyhodi vyjimku - sifra neni pro komponentu).
Overi se, ze '1234' je aktualni projekt (aktualni token); pokud ne, vyhodi vyjimku - sifra neni pro projekt.
Pokud vsechno souhlasi, rozsifruje payload KBC::Encrypted==... soucasnym wrapperem s klicem, ktery ma docker-bundle (kazdy stack bude mit svuj).

Wrapper KBC::EncryptedV2 muze byt:

- jen serializer v pripade, ze neni tajny, pro jaky projekt, region a komponentu je hodnota platna
- encryptor v pripade, ze to tajny je (tzn. podle sifry nejde zjistit, kde ji mam rozsiforvat - soucasne chovani)

**Comment by odinuv** [comment]
Jeste doplnim, ze kdyby wrapper KBC::EncryptedV2 byl encryptor, tak to vyzaduje existenci globalniho klice (se kterym se ale nepujde dostat k zadne hodnote), a vytvoreni noveho API callu pro pridani hodnoty do sifru - `encryptMerge`, ktery vezme zasfirvanou hodnotu a payload, rozsifruje ji, prida payload pro novy region a vrati zasifrovanou hodnotu

**Comment by ondrejhlavacek** [comment]
Serializer to asi bejt nemůže, protože je public, nebo i kdyby nebyl, tak ho reverse engineerovat bude snadný. 

Útočník deserializuje KBC::EncryptedV2== a v 
```
{
    "component: "keboola.ex-mysql",
    "project": "1234",
    "payload": [
        "connection-us-east-1": "KBC::Encrypted==..."
    ]
}
```

změní komponentu, projekt na svoje a v nějaký svojí appce si heslo dešifruje. Region/Stack zůstane stejnej. 

Nicméně to stejný může udělat, i když to bude encryptor a dostal by se ke globálnímu klíči - takhle by si mohl dešifrovat hesla v jakýmkoliv regionu/komponentě/projektu.

**Comment by odinuv** [comment]
jeste by se musel dostat k tomu klici, kterej bude v regionu v komponente

**Comment by ondrejhlavacek** [comment]
nemusel, tu hodnotu mu rozšifrujem, protože nastaví svoji komponentu a svůj projekt

**Comment by odinuv** [comment]
a musel by si to zase zasifrovat (pres funkci, ne pres api) a spustit ve spravnym regionu, tak to samy muze udelat i dneska

**Comment by ondrejhlavacek** [comment]
Tak nevím, jak to popsat, asi to nakreslím - přijde mi, že celková úroveň security bude na úrovni toho master globálního hesla.

**Comment by odinuv** [comment]
nebude, bude to sifrovany 2x, jednou globalnik klicem, jednou region klicem. Tedka je to sifrovany jednou globalnim klicem.

**Comment by ondrejhlavacek** [comment]
Jo, ale když z toho šifrovacího mechanismu vyndáme tu validaci, tak si přeneseš data jinam pouze se znalostí globálního klíče, místo toho, abys pořeboval aspoň regionální.

**Comment by Halama** [comment]
napadlo me ze misto `keboolaStack` by se mohl použít prostě hostname instance connection který už v parametrech je a je unikátní.

**Comment by ondrejhlavacek** [comment]
Tohle musí jít jako první, protože nový šifrování neumí podstrčit klič, ve kterým se přidá project id a component id.

**Comment by ondrejhlavacek** [comment]
- [ ] doplnit poslední chybějící wrapper
- [ ] upravit controllery na šifrování/ukládání konfigurace
- [ ] lepší parametr v konfiguraci než `KeboolaStack`, ostatní jsou s podtržítkama

**Comment by odinuv** [comment]
replaced by https://github.com/orgs/keboola/projects/16
