### ISSUE TITLE
Podpora slicovaných souborů, step 1

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#95]
Step 1 je podpora pro slicované soubory dodané aplikací. Viz https://github.com/keboola/connection/issues/575

Normální stav folderu pro upload je
```
/data/out/tables/file.csv
/data/out/tables/file.csv.manifest
```
Aplikace by dodala soubory ve formátu
```
/data/out/tables/file.csv.part_01
/data/out/tables/file.csv.part_02
/data/out/tables/file.csv.part_03
/data/out/tables/file.csv.manifest
```

a v `/data/out/tables/file.csv.manifest` by bylo uvedeno

```
{
    "source": "file.csv",
    "isSliced": true,
    "destination": "in.c-bucket.data"
}
```
nebo
```
{
    "source": "file.csv",
    "destination": "in.c-bucket.data",
    "isSliced": true,
    "slices": ["file.csv.part_01", "file.csv.part_02", "file.csv.part_03"]
}
```

To první mi přijde lepší, protože vynucuje aspoň prefixování souborů, to druhý jako by říkalo, že tam můžeš nacpat cokoliv a to pak hrozí potenciálníma konfliktama nebo chybama, že by si tam někdo dal špatný soubory.

Osobně by se mi nejvíc líbilo, kdyby to aplikace dodala jako 

```
/data/out/tables/file.csv/part_01
/data/out/tables/file.csv/part_02
/data/out/tables/file.csv/part_03
/data/out/tables/file.csv.manifest
```

ale my ten `file.csv` adresář neumíme smazat.

**Comment by odinuv** [comment]
jj, souhlas - idealni by byl ten adresar - porad to jeste nefunguje? to by bylo fakt asi nejcistsi, asi se me taky vic libi jednicka. Ma to jeden potencialni nedostatek, ze to nema definovany konec - treba kdyz budou v adresari soubory part_01 part_02 part_04. Musime detekovat, ze tam chybi trojka - aby to neskoncilo ani 2 ani 4.

**Comment by ondrejhlavacek** [comment]
Právěže to vůbec nemusí bejt řada. Na pořadí souborů nesmí záležet a můžou to bejt klidně úplný nesmysly. Vezme to prefix a všechno pod ním kromě manifestu.

Ten adresář ověřím.

**Comment by odinuv** [comment]
no tak to asi nechapu, tak tam potom budem potrebovat manifesty dva?
prece to poradi slicu je dulezity

**Comment by ondrejhlavacek** [comment]
Proč? Import do snowflake například pořadí neřeší, takže nevím, proč bychom to měli řešit my tady. Ve Storage pořadí řádků nezaručujem.

**Comment by odinuv** [comment]
Nevim, protoze su blbec? :)

**Comment by odinuv** [comment]
takze to bude neco jako if sliced, upload file.csv.*

**Comment by ondrejhlavacek** [comment]
Jj upload `file.csv.* ~file.csv.manifest`. Ten folder by byl ideální, protože by asi vklidu zvládl i nemít manifest.

**Comment by ondrejhlavacek** [comment]
Tyvolééééé slááááva!

```
$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

$ ls -la
total 8
drwxr-xr-x  2 ondra apache 4096 Nov 25 06:41 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..

$ sudo docker run --volume=/home/ondra/usertest:/code alpine sh -c 'mkdir /code/private && echo "x" > /code/private/x'

$ ls -la
total 12
drwxr-xr-x  3 ondra apache 4096 Nov 25 06:44 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..
drwxr-xr-x  2 root  root   4096 Nov 25 06:44 private

$ rm -rf ./private/
rm: cannot remove ‘./private/x’: Permission denied

$ rm ./private/x
rm: remove write-protected regular file ‘./private/x’? y
rm: cannot remove ‘./private/x’: Permission denied

$ sudo docker run --volume=/home/ondra/usertest:/code alpine sh -c 'rm -rf /code/private'

$ ls -la
total 8
drwxr-xr-x  2 ondra apache 4096 Nov 25 06:46 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..

$ id
uid=503(ondra) gid=501(apache) groups=501(apache),10(wheel)

$ sudo docker run --volume=/home/ondra/usertest:/code --user=503:501 alpine sh -c 'mkdir /code/private && echo "x" > /code/private/x'

$ ls -la
total 12
drwxr-xr-x  3 ondra apache 4096 Nov 25 06:46 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..
drwxr-xr-x  2 ondra apache 4096 Nov 25 06:46 private

$ rm -rf ./private/

$ ls -la
total 8
drwxr-xr-x  2 ondra apache 4096 Nov 25 06:47 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..
```

**Comment by odinuv** [comment]
takze kdyz tam dame --user id_apache_usera tak to bude na workeru fungovat?

**Comment by ujovlado** [comment]
toto je ale standardne chovanie dockeru ... ked to vytvorim ako root, musim mat root permissions aby som to mohol na hoste zmazat ... t.j. presne ako si si testol, treba to vytvorit pod userom, ktory na hoste existuje. napr. ten deploy.

**Comment by odinuv** [comment]
tak na to je prave to `--user` ne? tezko muzem chtit po nekom, aby mel ve svym image user `deploy`

**Comment by ujovlado** [comment]
skor som sa chcel ale spytat, ci je nutne to mat v dalsom priecinku? nemoze to byt viac standardnejsie chovanie, ako napr. rar a len si k tomu pridame manifest?

napr.:
```
xxx.part0001.rar
xxx.part0002.rar
xxx.part0003.rar
xxx.part0004.rar
xxx.part0005.rar
xxx.part0006.rar
xxx.manifest
```
^nejde mi o filenames skor, aby tam nebol ten dir.

**Comment by odinuv** [comment]
no o tom jsme se doted bavili :) ze potom vyzadujeme, aby ty soubory byly nejak pojmenovany, coz bude podivny a nachylny k chybam. Kdyz to bude v adresari, tak to proste znamena adresar = tabulka

**Comment by ondrejhlavacek** [comment]
@odin jojo, už to testuju na všech možnejch serverech, nechal bych to všechno běžet pod userem deploy  
```
sudo docker run ... --user=`id -u` ...
```

**Comment by ujovlado** [comment]
ano, ved ja som si to cital ... pomenovanie by som nechal na userovi a nech to vymenuje v manifeste, tak ako bola ta druha moznost:
```
"slices": ["file.csv.part_01", "file.csv.part_02", "file.csv.part_03"]
```

t.j. my by sme len nasli manifesty a pozreli si subory z nich

**Comment by ondrejhlavacek** [comment]
A když to bude v adresáři, nebude potřeba manifest. Celkově mi ty adresáře přijdou jednodušší na implementaci, může v tom vzniknout hroznej bordel

```
in.c-main.part001
in.c-main.manifest
in.c-main.mytable.part001
in.c-main.mytable.muj-nahodnej-slice.s.tečkou
in.c-main.mytable.manifest
```
Tohle je chaos, kterej tam legitimně může vzniknout. Mně se na takovýhle situace ani nechce psát testy :-)

**Comment by ondrejhlavacek** [comment]
No, jak jsem psal, pokud umožníš uživatelovi napsat soubory v manifestu, tak se to úplně zesere

```
hovno.csv
sračka.csv
mrdka.csv
kurva.osamělá.bez.manifestu.csv
kydy.manifest # [hovno.csv, sračka.csv]
hovna.manifes # [mrdka.csv]
```

A pak to v manifestech budeš párovat a hledat, jakej soubor není náhodou v žádným manifestu.

**Comment by odinuv** [comment]
presne

a ta kontrola jestli je soubor sparovanej s manifestem je celkem dulezita, uz jsme na tom odchytili nekolik peknejch chyb

**Comment by ondrejhlavacek** [comment]
A navíc se nějakej tvůj part může jmenovat manifest

```
hovna/sračky
hovna/manifest
hovna.manifest
```

A v budoucnu si vymyslíme ještě nějaký další speciální soubory a jsme v kelu.

**Comment by ujovlado** [comment]
mne ten manifest az taky uleteny neprisiel :) ale dobre, useri su kreativni.

ok, cize akonahle bude v `/data/out/tables/` nejaky adresar, tak sa ocakava, ze je to sliced subor a v tom adresasri musia byt jenodtlive casti a je nam uplne jedno ako su pomenovane?

Cize s tohto:
```
/data/out/tables/kurva.osamělá.bez.manifestu.csv
/data/out/tables/meno-tabulky/hovno.csv
/data/out/tables/meno-tabulky/sračka.csv
/data/out/tables/meno-tabulky/mrdka.csv
```
Budu 2 tabulky:
```
meno-tabulky
kurva.osamělá.bez.manifestu
```

**Comment by ondrejhlavacek** [comment]
Přesně tak. Mohli bychom určit třeba nějaký maximální limit, kolik těch slajsů bude (1000) a v tom adresáři se to bude pohodlně počítat.

**Comment by odinuv** [comment]
kam dame hlavicku ?

**Comment by ondrejhlavacek** [comment]
Ta bude muset bejt v manifestu

**Comment by ondrejhlavacek** [comment]
A kurva, problém

```
1) Keboola\DockerBundle\Tests\Functional\NetworkTest::testNetworkBridge
Keboola\Syrup\Exception\ApplicationException: Application error: builder-5838197e0d56a container 'docker-network-test' failed: (2) ping: icmp open socket: Operation not permitted
```

Takže to pod jiným userem asi spouštět nemůžeme. Nicméně se to asi dá ohackovat a chownovat po doběhnutí kontejneru - klidně i nějakým mikro kontejnerem, kterej udělá jenom 
```
chown `id -u` /data -R
```

Cca

```
$ sudo docker run --volume=/home/ondra/usertest:/code alpine sh -c 'mkdir /code/private && echo "x" > /code/private/x'

$ ls -la
total 12
drwxr-xr-x  3 ondra apache 4096 Nov 25 11:19 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..
drwxr-xr-x  2 root  root   4096 Nov 25 11:19 private

$ sudo docker run --volume=/home/ondra/usertest:/code alpine sh -c 'chown `id -u` /code/private -R'

$ ls -la
total 12
drwxr-xr-x  3 ondra apache 4096 Nov 25 11:17 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..
drwxr-xr-x  2 ondra root   4096 Nov 25 11:17 private
$ rm -rf private

$ ls -la
total 8
drwxr-xr-x  2 ondra apache 4096 Nov 25 11:18 .
drwx------ 27 ondra ondra  4096 Nov 25 06:41 ..
```

**Comment by ondrejhlavacek** [comment]
Takže toho usera asi vlastně vůbec nepotřebujem a mohlo mě to napadnout dřív! :D

**Comment by odinuv** [comment]
a nefunguje to jen nahodou, protoze ma stejny PID?

**Comment by ondrejhlavacek** [comment]
Ne, v tom alpine žádnej user s takovým PID není. Klidně si to vyzkoušej u sebe... V tom docker kontejneru to chownuje na usera, kterej pro něj neexistuje, ale zvládne to.

**Comment by ondrejhlavacek** [comment]
Použít na to alpine image.

**Comment by ondrejhlavacek** [comment]
Mazání subfolderů v `/data` řeší #97

**Comment by ondrejhlavacek** [comment]
@odinuv mě ještě napadlo, že by vlastně v manifestu nemuselo bejt vůbec nic - stačí, když docker runner zjistí, že uploadovanej soubor je adresář a bere to jeho obsah jako slicovaný, co ty na to?

tj

```
/data/out/tables/file.csv
/data/out/tables/file.csv.manifest

/data/out/tables/file.csv/part01
/data/out/tables/file.csv/part02
/data/out/tables/file.csv.manifest
```

**Comment by ondrejhlavacek** [comment]
Jo vlastně tam budou muset bejt ty sloupce :-/, ale to je nezávislá featura

**Comment by odinuv** [comment]
a co by ta melo byt jinyho? vsechny ostatni veci v manifestu jsou nepovinny

**Comment by ondrejhlavacek** [comment]
No sloupce jsou nepovinný, ale pro slicovaný soubory budou povinný. Nebo nerozumim otázce :-)

**Comment by odinuv** [comment]
no nijak, ze tam manifest bude a v nem budou povinny sloupce, pokud bude soubor sliced

**Comment by ondrejhlavacek** [comment]
Ještě můžou bejt v output mappingu (config)

**Comment by odinuv** [comment]
to nemas jak zjistit - kdyz ftp ex stahne soubor z ftpka, tak nevi co v nem bude, dokud se nepodiva

**Comment by ondrejhlavacek** [comment]
ano, ale u slicovanejch souborů (vokurkův případ) to neví ani komponenta (žádnej slajs nemá hlavičku) a může se to tam dodat zvenčí

**Comment by ondrejhlavacek** [comment]
podpora pro headless csv je tady - https://github.com/keboola/docker-bundle/pull/100
snažím se ty změny atomizovat :-) teď už fakt chybí jen podpora slicovanejch souborů, ty budou vždycky headless

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/docker-bundle/pull/102

**Comment by ondrejhlavacek** [comment]
fixed by #102
