### ISSUE TITLE
Switch pro ENV variables z parametrů

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/docker-bundle#96]
Parametry se budou do ENVů injectovat pouze při zapnutém flagu v definici komponenty a bude to řvát, když v parameters bude nějaká neskalární variable.

Default hodnota bude false, všem procesorům, kromě Mirova, se to zapne na true.

**Comment by odinuv** [comment]
upravit environment tak, aby se vytvarel pro kazdej image zvlast a ne jak ted, ze se do nej predavaji parametry
